Repository bitwarden/clients, pull requests merged in 2022-10, with the labels that each got.

#3383 [CL-27] [EC-455] Ng-Select Integration
  apps/web/src/locales/en/messages.json
  libs/components/src/form-field/form-field-control.ts
  libs/components/src/form-field/form-field.component.html
  libs/components/src/form-field/form-field.component.ts
  libs/components/src/form-field/form-field.module.ts
  libs/components/src/form-field/index.ts
  libs/components/src/form-field/multi-select.stories.ts
  libs/components/src/input/input.directive.ts
  libs/components/src/multi-select/models/select-item-view.ts
  libs/components/src/multi-select/multi-select.component.html
  libs/components/src/multi-select/multi-select.component.ts
  libs/components/src/multi-select/multi-select.module.ts
  libs/components/src/multi-select/scss/bw.theme.scss
  libs/components/src/styles.scss
  package-lock.json
  package.json
Labels: enhancement

#3744 [EC-601] Remove Device Verification UI from Web
  apps/web/src/app/organizations/settings/two-factor-setup.component.ts
  apps/web/src/app/settings/two-factor-setup.component.html
  apps/web/src/app/settings/two-factor-setup.component.ts
Labels: web

#3646 [PS-1604] Design: Tweak styles for browser/desktop selects and desktop form groups
  apps/browser/src/popup/scss/base.scss
  apps/desktop/src/scss/base.scss
  apps/desktop/src/scss/misc.scss
Labels: community-pr

#3675 [PS-1598] Desktop/browser: explicitly define themed text `::selection` styles
  apps/browser/src/popup/scss/misc.scss
  apps/desktop/src/scss/misc.scss
Labels: community-pr

#3347 [PS-1341] Add folder to item view
  apps/browser/src/popup/vault/view.component.html
  apps/browser/src/popup/vault/view.component.ts
  apps/desktop/src/app/vault/view.component.html
  apps/desktop/src/app/vault/view.component.ts
  libs/angular/src/components/view.component.ts
Labels: community-pr

#3502 [PS-1465] Fix #2806 - The "Import Data" page's file selector button cannot be translated
  apps/web/src/app/tools/import-export/import.component.html
  apps/web/src/app/tools/import-export/import.component.ts
  apps/web/src/locales/en/messages.json
Labels: community-pr

#3805 [PS-1693] feat(browser): implement theming for notification bar
  apps/browser/src/background/notification.background.ts
  apps/browser/src/content/notificationBar.ts
  apps/browser/src/images/close.png
  apps/browser/src/images/close.svg
  apps/browser/src/manifest.json
  apps/browser/src/manifest.v3.json
  apps/browser/src/notification/bar.html
  apps/browser/src/notification/bar.js
  apps/browser/src/notification/bar.scss
  apps/browser/src/notification/variables.scss
Labels: community-pr

#3552 [SM-260] Fix #2800 - Handle already verified email when resending verification email
  apps/web/src/app/settings/verify-email.component.ts
  apps/web/src/app/vault/vault.component.html
  apps/web/src/app/vault/vault.component.ts
Labels: community-pr
