Repository bitwarden/clients, pull requests merged in 2022-06, with the labels that each got.

#2893 EC-263 - Deactivate/activate in user management
  apps/web/src/app/common/base.people.component.ts
  apps/web/src/app/modules/loose-components.module.ts
  apps/web/src/app/organizations/manage/bulk/bulk-deactivate.component.html
  apps/web/src/app/organizations/manage/bulk/bulk-deactivate.component.ts
  apps/web/src/app/organizations/manage/people.component.html
  apps/web/src/app/organizations/manage/people.component.ts
  apps/web/src/app/organizations/manage/user-add-edit.component.html
  apps/web/src/app/organizations/manage/user-add-edit.component.ts
  apps/web/src/locales/en/messages.json
  bitwarden_license/bit-web/src/app/providers/manage/people.component.ts
  libs/common/src/abstractions/api.service.ts
  libs/common/src/enums/organizationUserStatusType.ts
  libs/common/src/enums/providerUserStatusType.ts
  libs/common/src/services/api.service.ts
Labels: enhancement, web

#2964 [SG-387] [Vault Filter] - Clicking the dropdown header while menu is open does not close overlay
  apps/browser/src/popup/vault/vault-select.component.ts
Labels: bug

#2674 [PS-1029] Browser: suppress `user-select` for most interface elements
  apps/browser/src/popup/scss/misc.scss
Labels: community-pr, browser

#2650 [PS-1030] Desktop: suppress `user-select` for most interface elements
  apps/desktop/src/scss/misc.scss
Labels: community-pr

#2985 [EC-282/EC-286] Update queryParams to use new filter object
  apps/web/src/app/modules/vault/modules/individual-vault/individual-vault.component.ts
  apps/web/src/app/modules/vault/modules/organization-vault/organization-vault.component.ts
Labels: bug
