Repository bitwarden/clients, pull requests merged in 2022-02, with the labels that each got.

#2305 [bug] Update gulp and webpack to include new font sheet
  gulpfile.js
  webpack.config.js
Labels: bug

#2306 [Icons] FF - requested icon changes
  package-lock.json
  package.json
  src/popup/tabs.component.html
  src/popup/vault/add-edit.component.html
  src/popup/vault/ciphers.component.html
  src/popup/vault/groupings.component.html
Labels: enhancement

#2398 Created workflow file
  .github/workflows/workflow-linter.yml
Labels: DevOps
