Repository bitwarden/clients, pull requests merged in 2022-11, with the labels that each got.

#3842 [EC-641] Browser Ext UI Update
  apps/browser/src/popup/components/set-pin.component.html
  apps/browser/src/popup/scss/base.scss
  apps/browser/src/popup/scss/box.scss
  apps/browser/src/popup/scss/buttons.scss
  apps/browser/src/popup/scss/misc.scss
  apps/browser/src/popup/scss/pages.scss
  apps/browser/src/popup/scss/variables.scss
  apps/browser/src/popup/vault/current-tab.component.html
Labels: needs-qa

#4047 [EC-743] Call super to ngOnInit to include policy observable changes
  apps/browser/src/popup/send/send-add-edit.component.ts
Labels: bug

#4029 [PS-1856] Added Mastodon to follow us menu
  apps/desktop/src/main/menu/menu.help.ts
Labels: community-pr

#3928 [PS-1783] Fix file selector input bug from PS-1465 ( #3502 )
  apps/web/src/app/tools/import-export/import.component.html
  apps/web/src/app/tools/import-export/import.component.ts
Labels: community-pr

#3561 [PS-1512] Desktop: Fix inconsistent line height in cipher box footer
  apps/browser/src/popup/scss/misc.scss
  apps/desktop/src/scss/misc.scss
Labels: community-pr

#4123 [PS-1922] Fix 'clients section' link in README
  README.md
Labels: community-pr
