Repository bitwarden/clients, pull requests merged in 2022-08, with the labels that each got.

#3234 [SG-501] [Defect] - More Actions and Disabled Org Icon No Longer Right Aligned
  apps/web/src/app/modules/vault-filter/components/organization-filter.component.html
  apps/web/src/scss/vault-filters.scss
Labels: bug

#3198 [PS-1161] Keeping focus on vault selector after selecting a vault
  apps/browser/src/popup/vault/current-tab.component.ts
Labels: accessibility, browser

#3195 [PS-1162] Preventing escape from closing popup when vault selector is open
  apps/browser/src/popup/vault/vault-select.component.ts
Labels: accessibility, browser

#3242 fix: link sso button
  apps/web/src/app/modules/vault-filter/components/link-sso.component.html
Labels: bug

#3126 [Component Library] Text/Button Links
  .vscode/launch.json
  jest.config.js
  libs/components/src/index.ts
  libs/components/src/link/index.ts
  libs/components/src/link/link.directive.ts
  libs/components/src/link/link.module.ts
  libs/components/src/link/link.stories.ts
  libs/components/src/tabs/tab-item.component.ts
  libs/components/src/tw-theme.css
  libs/components/tailwind.config.base.js
  package.json
Labels: enhancement

#3210 [PS-1224] Don't suppress outline for input[type="file"] controls
  apps/browser/src/popup/scss/box.scss
  apps/desktop/src/scss/box.scss
Labels: community-pr

#3308 [PS-1303] Desktop/browser: tweak `.box-header-expandable` styles
  apps/browser/src/popup/scss/box.scss
  apps/desktop/src/scss/box.scss
Labels: community-pr

#2916 [PS-1201] Allow bw sync without unlocking
  apps/cli/src/program.ts
Labels: community-pr

#3208 [PS-1222] Remove `appBlurClick` throughout the popup and web code
  apps/browser/src/popup/vault/vault-select.component.html
  apps/web/src/app/components/password-reprompt.component.html
  libs/angular/src/directives/blur-click.directive.ts
  libs/angular/src/jslib.module.ts
Labels: community-pr

#3323 [PS-1321] Web: fix twoStepLogin modal `title` > `id`
  apps/web/src/app/settings/two-factor-duo.component.html
Labels: community-pr

#3313 [PS-1307] Desktop: Change box-headers from `<div>` to semantic headings
  apps/desktop/src/app/accounts/delete-account.component.html
  apps/desktop/src/app/accounts/environment.component.html
  apps/desktop/src/app/accounts/premium.component.html
  apps/desktop/src/app/accounts/settings.component.html
  apps/desktop/src/app/accounts/two-factor-options.component.html
  apps/desktop/src/app/components/password-reprompt.component.html
  apps/desktop/src/app/send/add-edit.component.html
  apps/desktop/src/app/vault/add-edit-custom-fields.component.html
  apps/desktop/src/app/vault/add-edit.component.html
  apps/desktop/src/app/vault/attachments.component.html
  apps/desktop/src/app/vault/collections.component.html
  apps/desktop/src/app/vault/export.component.html
  apps/desktop/src/app/vault/folder-add-edit.component.html
  apps/desktop/src/app/vault/generator.component.html
  apps/desktop/src/app/vault/password-generator-history.component.html
  apps/desktop/src/app/vault/password-history.component.html
  apps/desktop/src/app/vault/share.component.html
  apps/desktop/src/app/vault/view-custom-fields.component.html
  apps/desktop/src/app/vault/view.component.html
  apps/desktop/src/scss/base.scss
Labels: community-pr

#3305 [PS-1301] Accessibility: improve item edit for URIs and custom fields
  apps/browser/src/popup/vault/add-edit-custom-fields.component.html
  apps/browser/src/popup/vault/add-edit.component.html
  apps/desktop/src/app/vault/add-edit-custom-fields.component.html
  apps/desktop/src/app/vault/add-edit.component.html
  apps/web/src/app/vault/add-edit-custom-fields.component.html
  apps/web/src/app/vault/add-edit.component.html
Labels: community-pr

#3306 [PS-1302] added duckduckgo's email forwarding service 🦆
  apps/browser/src/popup/generator/generator.component.html
  apps/desktop/src/app/vault/generator.component.html
  apps/web/src/app/tools/generator.component.html
  apps/web/webpack.config.js
  libs/angular/src/components/generator.component.ts
  libs/common/src/services/usernameGeneration.service.ts
Labels: community-pr

#3352 [PS-1347] Fix "Check for Updates..." URL (for clients without auto-updater)
  apps/desktop/src/main.ts
Labels: community-pr
