Repository bitwarden/clients, pull requests merged in 2022-09, with the labels that each got.

#3402 [PS-1383] fix typo: 'salted hashtag' to 'salted hashing'
  apps/browser/store/locales/en/copy.resx
Labels: community-pr

#3153 [CL-7] Avatar
  apps/web/src/app/vault/organization-badge/organization-name-badge.component.ts
  libs/angular/src/components/avatar.component.ts
  libs/common/src/misc/utils.ts
  libs/components/src/avatar/avatar.component.ts
  libs/components/src/avatar/avatar.module.ts
  libs/components/src/avatar/avatar.stories.ts
  libs/components/src/avatar/index.ts
Labels: enhancement

#3223 SM-90: Add Server Version to Browser About Page
  apps/browser/src/_locales/en/messages.json
  apps/browser/src/popup/app.module.ts
  apps/browser/src/popup/settings/about.component.html
  apps/browser/src/popup/settings/about.component.ts
  apps/browser/src/popup/settings/settings.component.ts
  libs/angular/src/services/jslib-services.module.ts
  libs/common/src/abstractions/config/config-api.service.abstraction.ts
  libs/common/src/abstractions/config/config.service.abstraction.ts
  libs/common/src/abstractions/config/server-config.ts
  libs/common/src/abstractions/environment.service.ts
  libs/common/src/abstractions/state.service.ts
  libs/common/src/models/data/server-config.data.ts
  libs/common/src/models/domain/account.ts
  libs/common/src/models/response/server-config-response.ts
  libs/common/src/services/config/config-api.service.ts
  libs/common/src/services/config/config.service.ts
  libs/common/src/services/environment.service.ts
  libs/common/src/services/state.service.ts
Labels: needs-qa

#3406 [PS-1387] Desktop: Remove "delete account" from settings
  apps/desktop/src/app/accounts/settings.component.html
  apps/desktop/src/app/accounts/settings.component.ts
Labels: community-pr

#3282 [CL-44] [EC-525] Update button disabled state
  libs/components/src/button/button.directive.ts
Labels: enhancement

#3321 [PS-1318] Desktop/browser: Make all item fields (except linked fields) draggable
  apps/browser/src/popup/vault/view-custom-fields.component.html
  apps/browser/src/popup/vault/view.component.html
  apps/desktop/src/app/vault/view-custom-fields.component.html
  apps/desktop/src/app/vault/view.component.html
  libs/angular/src/components/view-custom-fields.component.ts
Labels: community-pr

#3188 [PS-1111] Added prefix "Vault:" for accessibility on vault selector items
  apps/browser/src/popup/vault/vault-select.component.html
  apps/desktop/src/app/vault/vault-filter/filters/organization-filter.component.html
  apps/desktop/src/locales/en/messages.json
  apps/web/src/app/vault/vault-filter/organization-filter/organization-filter.component.html
Labels: accessibility, browser

#3328 [SM-223] Web: change `<h2>` modal title to `<h1>`, tweak styles to keep same look
  apps/web/src/app/accounts/two-factor-options.component.html
  apps/web/src/app/components/password-reprompt.component.html
  apps/web/src/app/organizations/manage/bulk/bulk-confirm.component.html
  apps/web/src/app/organizations/manage/bulk/bulk-remove.component.html
  apps/web/src/app/organizations/manage/bulk/bulk-restore-revoke.component.html
  apps/web/src/app/organizations/manage/bulk/bulk-status.component.html
  apps/web/src/app/organizations/manage/collection-add-edit.component.html
  apps/web/src/app/organizations/manage/entity-events.component.html
  apps/web/src/app/organizations/manage/entity-users.component.html
  apps/web/src/app/organizations/manage/group-add-edit.component.html
  apps/web/src/app/organizations/manage/policy-edit.component.html
  apps/web/src/app/organizations/manage/reset-password.component.html
  apps/web/src/app/organizations/manage/user-add-edit.component.html
  apps/web/src/app/organizations/manage/user-confirm.component.html
  apps/web/src/app/organizations/manage/user-groups.component.html
  apps/web/src/app/organizations/settings/billing-sync-api-key.component.html
  apps/web/src/app/organizations/settings/delete-organization.component.html
  apps/web/src/app/organizations/users/enroll-master-password-reset.component.html
  apps/web/src/app/send/add-edit.component.html
  apps/web/src/app/settings/api-key.component.html
  apps/web/src/app/settings/billing-sync-key.component.html
  apps/web/src/app/settings/deauthorize-sessions.component.html
  apps/web/src/app/settings/delete-account.component.html
  apps/web/src/app/settings/emergency-access-add-edit.component.html
  apps/web/src/app/settings/emergency-access-confirm.component.html
  apps/web/src/app/settings/emergency-access-takeover.component.html
  apps/web/src/app/settings/purge-vault.component.html
  apps/web/src/app/settings/two-factor-authenticator.component.html
  apps/web/src/app/settings/two-factor-duo.component.html
  apps/web/src/app/settings/two-factor-email.component.html
  apps/web/src/app/settings/two-factor-recovery.component.html
  apps/web/src/app/settings/two-factor-webauthn.component.html
  apps/web/src/app/settings/two-factor-yubikey.component.html
  apps/web/src/app/settings/update-key.component.html
  apps/web/src/app/tools/password-generator-history.component.html
  apps/web/src/app/vault/add-edit.component.html
  apps/web/src/app/vault/attachments.component.html
  apps/web/src/app/vault/bulk-delete.component.html
  apps/web/src/app/vault/bulk-move.component.html
  apps/web/src/app/vault/bulk-restore.component.html
  apps/web/src/app/vault/bulk-share.component.html
  apps/web/src/app/vault/collections.component.html
  apps/web/src/app/vault/folder-add-edit.component.html
  apps/web/src/app/vault/share.component.html
  apps/web/src/scss/modals.scss
Labels: community-pr

#3596 [PS-1544] Fix CLI Snap permissions
  apps/cli/stores/snap/snapcraft.yaml
Labels: community-pr

#3607 [PS-1550] Fix #2806 - The "Import Data", "Premium Membership", "Subscription" and "Edit User" pages contain strings that cannot be translated (PARTIAL)
  apps/web/src/app/organizations/manage/user-add-edit.component.html
  apps/web/src/locales/en/messages.json
Labels: community-pr
