Repository bitwarden/clients, pull requests merged in 2022-12, with the labels that each got.

#3727 [PS-1635] Desktop: Accessibility: tweak left-hand filters
  apps/desktop/src/app/vault/vault-filter/filters/folder-filter.component.html
  apps/desktop/src/app/vault/vault-filter/filters/organization-filter.component.html
Labels: community-pr

#4172 [PS-1962] Fix typo for DuckDuckGo form field
  apps/browser/src/popup/generator/generator.component.html
  apps/desktop/src/app/vault/generator.component.html
  apps/web/src/app/tools/generator.component.html
Labels: community-pr

#4183 [PS-1976] fix url
  apps/web/README.md
Labels: community-pr

#3893 [PS-1017] corrected web vault accessibility when deleting an item with keyboard
  apps/web/src/app/core/web-platform-utils.service.ts
  apps/web/src/app/organizations/manage/collection-add-edit.component.ts
  apps/web/src/app/organizations/manage/group-add-edit.component.ts
  apps/web/src/app/organizations/manage/user-add-edit.component.ts
  apps/web/src/app/organizations/vault/add-edit.component.ts
  apps/web/src/app/send/add-edit.component.ts
  apps/web/src/app/settings/emergency-add-edit.component.ts
  apps/web/src/app/vault/add-edit.component.ts
  apps/web/src/app/vault/attachments.component.ts
  apps/web/src/app/vault/folder-add-edit.component.ts
  libs/angular/src/components/add-edit.component.ts
  libs/angular/src/components/attachments.component.ts
  libs/angular/src/components/folder-add-edit.component.ts
  libs/angular/src/components/send/add-edit.component.ts
  libs/common/src/abstractions/platformUtils.service.ts
Labels: accessibility, web

#3951 [PS-1793] Desktop/Browser/Web: tweak disclosure widget design
  apps/browser/src/popup/scss/box.scss
  apps/browser/src/popup/send/send-add-edit.component.html
  apps/browser/src/popup/settings/options.component.html
  apps/desktop/src/app/accounts/environment.component.html
  apps/desktop/src/app/accounts/settings.component.html
  apps/desktop/src/app/send/add-edit.component.html
  apps/desktop/src/app/vault/generator.component.html
  apps/desktop/src/scss/box.scss
  apps/web/src/app/send/add-edit.component.html
  apps/web/src/scss/buttons.scss
  bitwarden_license/bit-web/src/app/organizations/manage/sso.component.html
  libs/components/src/link/link.stories.ts
  libs/components/src/stories/icons.stories.mdx
Labels: community-pr

#4050 [PS-1874] Manage zoom factor when opening / closing the application
  apps/desktop/src/main/window.main.ts
  libs/common/src/models/domain/window-state.ts
Labels: community-pr

#4001 [PS-1830] Updated the autofill.js file to no longer add the 'data.com' attribute to tags
  apps/browser/src/content/autofill.js
Labels: community-pr

#4093 Web - SG-668 update flows for free 2 person orgs
  apps/web/src/app/organizations/billing/organization-subscription.component.ts
  apps/web/src/app/organizations/manage/collections.component.ts
  apps/web/src/app/organizations/manage/org-upgrade-dialog/org-upgrade-dialog.component.html
  apps/web/src/app/organizations/manage/org-upgrade-dialog/org-upgrade-dialog.component.ts
  apps/web/src/app/organizations/manage/people.component.html
  apps/web/src/app/organizations/manage/people.component.ts
  apps/web/src/app/organizations/organization.module.ts
  apps/web/src/locales/en/messages.json
  libs/components/src/dialog/dialog.module.ts
Labels: web

#4094 Defect/SG-825 - users in org w/ no personal vault still see personal vault (disabled org policies now still apply)
  apps/browser/src/popup/scss/base.scss
  apps/browser/src/popup/vault/vault-select.component.html
  apps/desktop/src/app/vault/vault-filter/filters/organization-filter.component.html
  apps/web/src/app/vault/vault-filter/organization-filter/organization-filter.component.html
  libs/common/src/services/policy/policy.service.ts
Labels: web

#3262 [EC-474] Add hidden char count toggle to web and desktop
  apps/browser/src/popup/app.module.ts
  apps/browser/src/popup/scss/misc.scss
  apps/browser/src/popup/scss/variables.scss
  apps/browser/src/popup/vault/password-history.component.html
  apps/desktop/src/app/app.module.ts
  apps/desktop/src/app/vault/password-generator-history.component.html
  apps/desktop/src/app/vault/password-history.component.html
  apps/desktop/src/app/vault/view-custom-fields.component.html
  apps/desktop/src/app/vault/view.component.html
  apps/desktop/src/locales/en/messages.json
  apps/desktop/src/scss/box.scss
  apps/desktop/src/scss/misc.scss
  apps/desktop/src/scss/variables.scss
  apps/web/src/app/shared/shared.module.ts
  apps/web/src/app/tools/generator.component.html
  apps/web/src/app/tools/password-generator-history.component.html
  apps/web/src/app/vault/add-edit.component.html
  apps/web/src/app/vault/add-edit.component.ts
  apps/web/src/locales/en/messages.json
  apps/web/src/scss/pages.scss
  apps/web/src/scss/variables.scss
  libs/angular/src/jslib.module.ts
  libs/components/src/color-password/color-password.component.ts
Labels: community-pr

#3802 [PS-1692] Use `aria-describedby` for all help blocks/hints
  apps/browser/src/popup/accounts/environment.component.html
  apps/browser/src/popup/accounts/hint.component.html
  apps/browser/src/popup/accounts/lock.component.html
  apps/browser/src/popup/accounts/register.component.html
  apps/browser/src/popup/accounts/set-password.component.html
  apps/browser/src/popup/accounts/update-temp-password.component.html
  apps/browser/src/popup/components/password-reprompt.component.html
  apps/browser/src/popup/components/user-verification.component.html
  apps/browser/src/popup/generator/generator.component.html
  apps/browser/src/popup/send/efflux-dates.component.html
  apps/browser/src/popup/send/send-add-edit.component.html
  apps/browser/src/popup/settings/export.component.html
  apps/browser/src/popup/settings/options.component.html
  apps/browser/src/popup/settings/settings.component.html
  apps/browser/src/popup/settings/sync.component.html
  apps/browser/src/popup/vault/attachments.component.html
  apps/browser/src/popup/vault/share.component.html
  apps/desktop/src/app/accounts/accessibility-cookie.component.html
  apps/desktop/src/app/accounts/delete-account.component.html
  apps/desktop/src/app/accounts/environment.component.html
  apps/desktop/src/app/accounts/hint.component.html
  apps/desktop/src/app/accounts/lock.component.html
  apps/desktop/src/app/accounts/register.component.html
  apps/desktop/src/app/accounts/set-password.component.html
  apps/desktop/src/app/accounts/settings.component.html
  apps/desktop/src/app/accounts/update-temp-password.component.html
  apps/desktop/src/app/accounts/vault-timeout-input.component.html
  apps/desktop/src/app/components/password-reprompt.component.html
  apps/desktop/src/app/components/user-verification.component.html
  apps/desktop/src/app/send/add-edit.component.html
  apps/desktop/src/app/send/efflux-dates.component.html
  apps/desktop/src/app/vault/attachments.component.html
  apps/desktop/src/app/vault/export.component.html
  apps/desktop/src/app/vault/generator.component.html
  apps/desktop/src/app/vault/share.component.html
  apps/desktop/src/scss/misc.scss
Labels: community-pr

#3405 [PS-1386] Browser/Desktop/Web: Accessibility - Stop username regenerator button from losing focus
  apps/browser/src/popup/generator/generator.component.html
  apps/desktop/src/app/vault/generator.component.html
  apps/web/src/app/tools/generator.component.html
  apps/web/src/scss/buttons.scss
Labels: community-pr
