Repository bitwarden/clients, pull requests merged in 2022-07, with the labels that each got.

#3022 [PS-1078] Refactor FolderService to use Observables
  apps/browser/src/background/main.background.ts
  apps/browser/src/background/notification.background.ts
  apps/browser/src/popup/services/services.module.ts
  apps/browser/src/popup/settings/folders.component.html
  apps/browser/src/popup/settings/folders.component.ts
  apps/browser/src/popup/vault/add-edit.component.html
  apps/browser/src/popup/vault/ciphers.component.ts
  apps/browser/src/popup/vault/vault-filter.component.ts
  apps/cli/src/bw.ts
  apps/cli/src/commands/get.command.ts
  apps/cli/src/commands/list.command.ts
  apps/desktop/src/app/modules/vault-filter/vault-filter.component.html
  apps/desktop/src/app/vault/add-edit.component.html
  apps/web/src/app/modules/vault-filter/vault-filter.component.html
  apps/web/src/app/settings/change-password.component.ts
  apps/web/src/app/settings/update-key.component.ts
  apps/web/src/app/vault/add-edit.component.html
  apps/web/src/app/vault/bulk-move.component.html
  apps/web/src/app/vault/bulk-move.component.ts
  libs/angular/src/components/add-edit.component.ts
  libs/angular/src/modules/vault-filter/vault-filter.component.ts
  libs/angular/src/modules/vault-filter/vault-filter.service.ts
  libs/angular/src/services/jslib-services.module.ts
  libs/common/spec/services/export.service.spec.ts
  libs/common/spec/services/folder.service.spec.ts
  libs/common/src/abstractions/folder/folder.service.abstraction.ts
  libs/common/src/abstractions/state.service.ts
  libs/common/src/models/domain/account.ts
  libs/common/src/services/export.service.ts
  libs/common/src/services/folder/folder.service.ts
  libs/common/src/services/state.service.ts
  libs/common/src/services/vaultTimeout.service.ts
Labels: ee

#2952 [CL-17] Tabs - Router
  libs/components/src/index.ts
  libs/components/src/tabs/index.ts
  libs/components/src/tabs/tab-group.component.html
  libs/components/src/tabs/tab-group.component.ts
  libs/components/src/tabs/tab-item.component.html
  libs/components/src/tabs/tab-item.component.ts
  libs/components/src/tabs/tabs.module.ts
  libs/components/src/tabs/tabs.stories.ts
  libs/components/tailwind.config.base.js
Labels: enhancement

#3079 [PS-1122] Adds Mir payment system
  apps/browser/src/_locales/en/messages.json
  apps/desktop/src/locales/en/messages.json
  apps/web/src/locales/en/messages.json
  libs/angular/src/components/add-edit.component.ts
  libs/angular/src/components/icon.component.ts
  libs/angular/src/images/cards/mir-dark.png
  libs/angular/src/images/cards/mir-light.png
  libs/angular/src/pipes/credit-card-number.pipe.ts
  libs/angular/src/scss/icons.scss
  libs/common/src/importers/baseImporter.ts
Labels: community-pr

#3152 [CL-17] Use focus-visible for keyboard selection
  libs/components/src/tabs/tab-item.component.ts
Labels: enhancement

#2662 [PS-1182] Desktop / Browser: Accessibility - remove appBlurClick, change remaining links to buttons
  apps/browser/src/popup/accounts/environment.component.html
  apps/browser/src/popup/accounts/hint.component.html
  apps/browser/src/popup/accounts/home.component.html
  apps/browser/src/popup/accounts/lock.component.html
  apps/browser/src/popup/accounts/login.component.html
  apps/browser/src/popup/accounts/register.component.html
  apps/browser/src/popup/accounts/set-password.component.html
  apps/browser/src/popup/accounts/two-factor-options.component.html
  apps/browser/src/popup/accounts/two-factor.component.html
  apps/browser/src/popup/accounts/update-temp-password.component.html
  apps/browser/src/popup/components/password-reprompt.component.html
  apps/browser/src/popup/components/set-pin.component.html
  apps/browser/src/popup/generator/generator.component.html
  apps/browser/src/popup/generator/password-generator-history.component.html
  apps/browser/src/popup/send/send-add-edit.component.html
  apps/browser/src/popup/send/send-groupings.component.html
  apps/browser/src/popup/send/send-type.component.html
  apps/browser/src/popup/settings/excluded-domains.component.html
  apps/browser/src/popup/settings/export.component.html
  apps/browser/src/popup/settings/folder-add-edit.component.html
  apps/browser/src/popup/settings/folders.component.html
  apps/browser/src/popup/settings/options.component.html
  apps/browser/src/popup/settings/premium.component.html
  apps/browser/src/popup/settings/settings.component.html
  apps/browser/src/popup/settings/sync.component.html
  apps/browser/src/popup/tabs.component.html
  apps/browser/src/popup/vault/add-edit-custom-fields.component.html
  apps/browser/src/popup/vault/add-edit.component.html
  apps/browser/src/popup/vault/attachments.component.html
  apps/browser/src/popup/vault/ciphers.component.html
  apps/browser/src/popup/vault/collections.component.html
  apps/browser/src/popup/vault/current-tab.component.html
  apps/browser/src/popup/vault/password-history.component.html
  apps/browser/src/popup/vault/share.component.html
  apps/browser/src/popup/vault/vault-filter.component.html
  apps/browser/src/popup/vault/view.component.html
  apps/desktop/src/app/accounts/set-password.component.html
  apps/desktop/src/app/components/set-pin.component.html
  apps/desktop/src/app/layout/account-switcher.component.html
  apps/desktop/src/app/send/send.component.html
Labels: community-pr, browser, desktop

#3175 Fix missing settings button
  apps/browser/src/popup/scss/pages.scss
  apps/desktop/src/scss/environment.scss
  apps/desktop/src/scss/pages.scss
Labels: browser, desktop

#3145 [SG-451] [Defect] - Safari Extension Does Not Display Icon for Long Named Orgs
  apps/browser/src/popup/vault/vault-select.component.html
  apps/desktop/src/app/modules/vault-filter/components/organization-filter.component.html
  apps/desktop/src/scss/base.scss
  apps/web/src/app/modules/vault-filter/components/organization-filter.component.html
  apps/web/src/scss/vault-filters.scss
Labels: bug

#2689 [PS-1181] Desktop: Accessibility - ARIA/structure fixes
  apps/desktop/src/app/modules/vault-filter/components/collection-filter.component.html
  apps/desktop/src/app/modules/vault-filter/components/folder-filter.component.html
  apps/desktop/src/app/modules/vault-filter/components/organization-filter.component.html
  apps/desktop/src/app/modules/vault-filter/components/type-filter.component.html
  apps/desktop/src/app/send/send.component.html
  apps/desktop/src/scss/left-nav.scss
Labels: community-pr

#3190 [SG-494] [Defect] - Disabled Organization Icon Causing Incorrect Alignment in Web For Long Names
  apps/web/src/app/modules/vault-filter/components/organization-filter.component.html
  apps/web/src/scss/vault-filters.scss
Labels: bug
