Repository bitwarden/clients, pull requests merged in 2023-04, with the labels that each got.

#5152 Fix broken export spec
  libs/common/spec/services/export.service.spec.ts
Labels: needs-qa

#5139 Defect / PM-1354 - Fix master password not auto focused on web login flow
  apps/web/src/auth/login/login.component.html
  libs/angular/src/auth/components/login.component.ts
Labels: needs-qa

#4802 [PS-2390] Passing folder and collection id on import
  libs/common/src/admin-console/models/request/collection-with-id.request.ts
  libs/common/src/models/export/collection-with-id.export.ts
  libs/common/src/models/export/folder-with-id.export.ts
  libs/common/src/models/request/import-ciphers.request.ts
  libs/common/src/models/request/import-organization-ciphers.request.ts
  libs/importer/src/importers/base-importer.ts
  libs/importer/src/importers/bitwarden/bitwarden-json-importer.ts
  libs/importer/src/services/import.service.ts
Labels: web

#5137 [PM-1684] Broken roboform importer
  libs/importer/spec/roboform-csv-importer.spec.ts
  libs/importer/spec/test-data/roboform-csv/empty-folders.ts
  libs/importer/spec/test-data/roboform-csv/with-folders.ts
  libs/importer/src/importers/base-importer.ts
Labels: web

#5065 [SM-612] Highlighting selected product properly
  apps/web/src/app/layouts/product-switcher/product-switcher-content.component.html
  apps/web/src/app/layouts/product-switcher/product-switcher-content.component.ts
Labels: needs-qa

#5100 [SM-679] placeholder text being cut off
  bitwarden_license/bit-web/src/app/secrets-manager/projects/projects/projects.component.html
  bitwarden_license/bit-web/src/app/secrets-manager/secrets/secrets.component.html
  bitwarden_license/bit-web/src/app/secrets-manager/service-accounts/service-accounts.component.html
Labels: needs-qa

#4242 [PS-1147] Added keyboard accessibility to 2FA disable confirmation popup
  apps/web/src/auth/settings/two-factor-authenticator.component.ts
  apps/web/src/auth/settings/two-factor-base.component.ts
  apps/web/src/auth/settings/two-factor-duo.component.ts
  apps/web/src/auth/settings/two-factor-email.component.ts
  apps/web/src/auth/settings/two-factor-webauthn.component.ts
  apps/web/src/auth/settings/two-factor-yubikey.component.ts
Labels: accessibility, web

#5162 [EC-850] ProviderUser permissions should prevail over member permissions
  apps/browser/src/vault/popup/components/vault/vault-select.component.ts
  apps/web/src/app/admin-console/components/organization-switcher.component.ts
  apps/web/src/app/layouts/navbar.component.ts
  apps/web/src/app/vault/individual-vault/vault-filter/services/vault-filter.service.spec.ts
  apps/web/src/app/vault/individual-vault/vault-filter/services/vault-filter.service.ts
  libs/angular/src/components/share.component.ts
  libs/angular/src/vault/components/add-edit.component.ts
  libs/angular/src/vault/vault-filter/services/vault-filter.service.ts
  libs/common/spec/services/organization/organization.service.spec.ts
  libs/common/spec/services/policy.service.spec.ts
  libs/common/src/admin-console/abstractions/organization/organization.service.abstraction.ts
  libs/common/src/admin-console/models/data/organization.data.ts
  libs/common/src/admin-console/models/domain/organization.ts
  libs/common/src/admin-console/services/organization/organization.service.ts
  libs/common/src/admin-console/services/policy/policy.service.ts
  libs/common/src/vault/services/sync/sync.service.ts
Labels: needs-qa

#5234 Ps 2079/desktop biometrics Rework
  .github/whitelist-capital-letters.txt
  .vscode/settings.json
  apps/desktop/desktop_native/Cargo.lock
  apps/desktop/desktop_native/Cargo.toml
  apps/desktop/desktop_native/index.d.ts
  apps/desktop/desktop_native/src/biometric/macos.rs
  apps/desktop/desktop_native/src/biometric/mod.rs
  apps/desktop/desktop_native/src/biometric/unix.rs
  apps/desktop/desktop_native/src/biometric/windows.rs
  apps/desktop/desktop_native/src/crypto/cipher_string.rs
  apps/desktop/desktop_native/src/crypto/crypto.rs
  apps/desktop/desktop_native/src/crypto/mod.rs
  apps/desktop/desktop_native/src/error.rs
  apps/desktop/desktop_native/src/lib.rs
  apps/desktop/src/app/accounts/settings.component.html
  apps/desktop/src/app/accounts/settings.component.ts
  apps/desktop/src/app/services/services.module.ts
  apps/desktop/src/auth/lock.component.html
  apps/desktop/src/auth/lock.component.ts
  apps/desktop/src/locales/en/messages.json
  apps/desktop/src/main.ts
  apps/desktop/src/main/biometric/biometric.darwin.main.ts
  apps/desktop/src/main/biometric/biometric.windows.main.ts
  apps/desktop/src/main/biometric/biometrics.service.abstraction.ts
  apps/desktop/src/main/biometric/biometrics.service.spec.ts
  apps/desktop/src/main/biometric/biometrics.service.ts
  apps/desktop/src/main/desktop-credential-storage-listener.ts
  apps/desktop/src/models/account.ts
  apps/desktop/src/scss/misc.scss
  apps/desktop/src/services/electron-crypto.service.ts
  apps/desktop/src/services/electron-platform-utils.service.ts
  apps/desktop/src/services/electron-state.service.abstraction.ts
  apps/desktop/src/services/electron-state.service.ts
  apps/desktop/src/services/encrypted-message-handler.service.ts
  apps/desktop/src/services/state.service.ts
  apps/desktop/src/types/biometric-message.ts
  libs/common/spec/misc/utils.spec.ts
  libs/common/spec/models/domain/enc-string.spec.ts
  libs/common/spec/services/encrypt.service.spec.ts
  libs/common/spec/services/stateMigration.service.spec.ts
  libs/common/src/abstractions/cryptoFunction.service.ts
  libs/common/src/abstractions/state.service.ts
  libs/common/src/auth/types/biometric-key.d.ts
  libs/common/src/enums/encryption-type.enum.ts
  libs/common/src/enums/state-version.enum.ts
  libs/common/src/models/domain/account.ts
  libs/common/src/models/domain/enc-string.ts
  libs/common/src/models/domain/global-state.ts
  libs/common/src/models/domain/symmetric-crypto-key.ts
  libs/common/src/services/crypto.service.ts
  libs/common/src/services/state.service.ts
  libs/common/src/services/stateMigration.service.ts
  libs/common/src/services/webCryptoFunction.service.ts
  libs/common/src/types/csprng.d.ts
  libs/node/src/services/node-crypto-function.service.ts
Labels: needs-qa

#5240 Defect/[PM-1887] - Fix Account Creation Terms of Service Checkbox not clickable in Safari
  apps/web/src/auth/register-form/register-form.component.html
Labels: needs-qa

#5241 [PM-1890] Lock active account first
  apps/desktop/src/app/app.component.ts
Labels: needs-qa

#5244 [PM-1889] Debounce value changes
  apps/browser/src/popup/settings/settings.component.ts
Labels: needs-qa

#5255 [AC-1340] [Defect] Provider users unable to restore vault items for client organizations
  apps/web/src/app/vault/org-vault/vault.component.ts
  libs/angular/src/vault/components/add-edit.component.ts
  libs/common/src/vault/abstractions/cipher.service.ts
  libs/common/src/vault/services/cipher.service.ts
Labels: needs-qa

#5237 [PM-1877] Spellcheck
  apps/browser/src/alarms/register-alarms.ts
  apps/browser/src/autofill/browser/cipher-context-menu-handler.ts
  apps/browser/src/autofill/content/autofill.js
  apps/browser/src/autofill/models/autofill-field.ts
  apps/browser/src/popup/settings/excluded-domains.component.ts
  apps/browser/src/services/browserPlatformUtils.service.ts
  apps/browser/src/services/vaultTimeout/vaultTimeout.service.ts
  apps/browser/src/tools/popup/send/send-add-edit.component.ts
  apps/desktop/native-messaging-test-runner/src/commands/bw-credential-create.ts
  apps/desktop/native-messaging-test-runner/src/ipc.service.ts
  apps/desktop/native-messaging-test-runner/src/variables.ts
  apps/desktop/src/app/layout/account-switcher.component.ts
  apps/desktop/src/services/encrypted-message-handler.service.ts
  apps/web/src/app/admin-console/organizations/members/people.component.ts
  apps/web/src/app/core/core.module.ts
  apps/web/src/app/settings/adjust-storage.component.html
  apps/web/src/app/settings/change-password.component.ts
  apps/web/src/app/vault/components/vault-items/vault-items.stories.ts
  apps/web/src/app/vault/individual-vault/vault-header/vault-header.component.ts
  apps/web/src/auth/two-factor-options.component.html
  bitwarden_license/bit-web/src/app/admin-console/providers/clients/clients.component.ts
  bitwarden_license/bit-web/src/app/admin-console/providers/services/web-provider.service.ts
  bitwarden_license/bit-web/src/app/secrets-manager/shared/access-policies/access-selector.component.ts
  libs/angular/src/auth/components/login-with-device.component.ts
  libs/angular/src/pipes/color-password.pipe.ts
  libs/angular/src/scss/icons.scss
  libs/angular/src/tools/generator/components/generator.component.ts
  libs/angular/src/tools/send/efflux-dates.component.ts
  libs/common/spec/matchers/toEqualBuffer.ts
  libs/common/src/abstractions/organization-user/organization-user.service.ts
  libs/common/src/abstractions/organization-user/responses/organization-user.response.ts
  libs/common/src/abstractions/state.service.ts
  libs/common/src/auth/abstractions/auth.service.ts
  libs/common/src/auth/services/auth.service.ts
  libs/common/src/models/domain/window-state.ts
  libs/common/src/services/anonymousHub.service.ts
  libs/common/src/services/organization-user/organization-user.service.implementation.ts
  libs/common/src/services/state.service.ts
  libs/common/src/tools/send/services/send-api.service.ts
  libs/components/src/async-actions/bit-submit.directive.ts
  libs/components/src/link/link.stories.ts
  libs/components/src/multi-select/scss/bw.theme.scss
  libs/components/src/navigation/nav-group.stories.ts
  libs/components/src/stories/button-docs.stories.mdx
  libs/components/src/stories/table-docs.stories.mdx
  libs/components/src/toggle-group/toggle.component.ts
  libs/exporter/src/vault-export/services/vault-export.service.spec.ts
  libs/importer/spec/myki-csv-importer.spec.ts
  libs/importer/spec/test-data/myki-csv/user-id-card.csv.ts
  libs/importer/src/importers/dashlane/dashlane-csv-importer.ts
Labels: community-pr

#5283 [SM-602] Inital PR for checking if the Link is still valid/the user still has …
  bitwarden_license/bit-web/src/app/secrets-manager/projects/project/project.component.ts
Labels: needs-qa

#5296 [SM-602] Fixing merge conflict, changing handleError to return ProjectView instead of deprecated ProjectPermissionDetailView
  bitwarden_license/bit-web/src/app/secrets-manager/projects/project/project.component.ts
Labels: needs-qa

#5239 [PM-1267] Update cli receive command to use api.bitwarden.com
  apps/cli/src/tools/send/commands/receive.command.ts
Labels: cli, needs-qa

#5229 [PM-730] Corrected EventType when copying password
  apps/browser/src/vault/popup/components/action-buttons.component.ts
  apps/web/src/app/vault/individual-vault/add-edit.component.ts
  apps/web/src/app/vault/individual-vault/vault.component.ts
  apps/web/src/app/vault/org-vault/vault.component.ts
  libs/angular/src/vault/components/view.component.ts
Labels: web

#5181 [PM-1400] Update IconComponent to use OnPush ChangeDetection
  apps/browser/src/popup/settings/options.component.ts
  apps/browser/src/services/browser-settings.service.ts
  apps/desktop/src/app/accounts/settings.component.ts
  apps/web/src/app/settings/preferences.component.ts
  apps/web/src/app/vault/components/vault-items/vault-items.stories.ts
  libs/angular/src/auth/components/lock.component.ts
  libs/angular/src/auth/components/login.component.ts
  libs/angular/src/auth/components/sso.component.ts
  libs/angular/src/auth/components/two-factor.component.ts
  libs/angular/src/vault/components/icon.component.html
  libs/angular/src/vault/components/icon.component.ts
  libs/common/src/abstractions/settings.service.ts
  libs/common/src/abstractions/state.service.ts
  libs/common/src/services/settings.service.ts
  libs/common/src/services/state.service.ts
Labels: needs-qa
