Repository bitwarden/clients, pull requests merged in 2023-06, with the labels that each got.

#5518 [DEVOPS-1395] build and deploy web vault
  .github/workflows/build-web.yml
  .github/workflows/deploy-non-prod-web.yml
  apps/web/config/eudevtest.json
  apps/web/package.json
Labels: hold

#5131 [PM-1687] Add collection name to title attribute
  apps/desktop/src/admin-console/vault-filters/collection-filter.component.html
Labels: community-pr, desktop, needs-qa

#4809 [PM-1060] Added new forwarder (Forward Email <https://forwardemail.net>)
  apps/browser/src/tools/popup/generator/generator.component.html
  apps/desktop/src/app/tools/generator.component.html
  apps/web/src/app/tools/generator.component.html
  apps/web/webpack.config.js
  libs/angular/src/tools/generator/components/generator.component.ts
  libs/common/src/tools/generator/username/email-forwarders/forward-email-forwarder.ts
  libs/common/src/tools/generator/username/email-forwarders/forwarder-options.ts
  libs/common/src/tools/generator/username/email-forwarders/index.ts
  libs/common/src/tools/generator/username/username-generation.service.ts
Labels: community-pr

#5204 [PM-1823] Defining the card brand according to its number
  apps/browser/src/vault/popup/components/vault/add-edit.component.html
  apps/desktop/src/vault/app/vault/add-edit.component.html
  apps/web/src/app/vault/individual-vault/add-edit.component.html
  libs/angular/src/vault/components/add-edit.component.ts
  libs/common/src/vault/models/view/card.view.ts
  libs/importer/src/importers/avast/avast-json-importer.ts
  libs/importer/src/importers/base-importer.ts
  libs/importer/src/importers/dashlane/dashlane-csv-importer.ts
  libs/importer/src/importers/dashlane/dashlane-json-importer.ts
  libs/importer/src/importers/encryptr-csv-importer.ts
  libs/importer/src/importers/enpass/enpass-csv-importer.ts
  libs/importer/src/importers/enpass/enpass-json-importer.ts
  libs/importer/src/importers/fsecure/fsecure-fsk-importer.ts
  libs/importer/src/importers/lastpass-csv-importer.ts
  libs/importer/src/importers/myki-csv-importer.ts
  libs/importer/src/importers/nordpass-csv-importer.ts
  libs/importer/src/importers/onepassword/onepassword-1pif-importer.ts
  libs/importer/src/importers/onepassword/onepassword-1pux-importer.ts
  libs/importer/src/importers/onepassword/onepassword-csv-importer.ts
  libs/importer/src/importers/passwordboss-json-importer.ts
  libs/importer/src/importers/remembear-csv-importer.ts
  libs/importer/src/importers/truekey-csv-importer.ts
Labels: community-pr

#5588 New Feature Flag Route Guard introduced in #5465 uses a translation w…
  apps/browser/src/_locales/en/messages.json
  apps/desktop/src/locales/en/messages.json
Labels: needs-qa

#4921 [PM-1320] Argon2 SIMD support
  apps/desktop/webpack.main.js
  package-lock.json
  package.json
  patches/argon2-browser+1.18.0.patch
Labels: community-pr

#5619 Change ownership of autofill from vault to client integrations
  .github/CODEOWNERS
Labels: needs-qa

#5620 Add EU Prod environment to Web build
  .github/workflows/build-web.yml
  .github/workflows/deploy-prod-web.yml
  apps/web/config/euprd.json
  apps/web/config/poc.json
  apps/web/package.json
Labels: needs-qa

#5604 [PM-2475][PM-2536] Clicking "US" in region selector sets base URL
  apps/desktop/src/auth/login/login.component.ts
  apps/web/src/app/layouts/frontend-layout.component.html
  apps/web/src/app/layouts/frontend-layout.component.ts
  libs/angular/src/auth/components/environment-selector.component.ts
  libs/angular/src/components/environment.component.ts
  libs/common/src/platform/abstractions/environment.service.ts
  libs/common/src/platform/abstractions/state.service.ts
  libs/common/src/platform/models/domain/account.ts
  libs/common/src/platform/models/domain/global-state.ts
  libs/common/src/platform/services/environment.service.ts
  libs/common/src/platform/services/state.service.ts
Labels: needs-qa

#5574 [AC-1436] Move desktop vault filters to vault team
  apps/desktop/src/vault/app/vault/vault-filter/filters/collection-filter.component.html
  apps/desktop/src/vault/app/vault/vault-filter/filters/collection-filter.component.ts
  apps/desktop/src/vault/app/vault/vault-filter/filters/organization-filter.component.html
  apps/desktop/src/vault/app/vault/vault-filter/filters/organization-filter.component.ts
  apps/desktop/src/vault/app/vault/vault-filter/vault-filter.module.ts
Labels: needs-qa

#5580 PM-1565 Added item key property to cipher export domain
  libs/common/src/models/export/cipher.export.ts
  libs/exporter/src/vault-export/services/vault-export.service.ts
Labels: cli, web

#5684 [PM-2744] cli import is failing
  apps/cli/src/bw.ts
Labels: cli

#5670 [PM-270] fixed case in EN locale message for Self-hosted form in Extension
  apps/browser/src/_locales/en/messages.json
Labels: browser
