Repository bitwarden/clients, pull requests merged in 2023-05, with the labels that each got.

#5302 [PM-1433] Creating Item Doesn't Auto-Select Current Organization/Collection in Individual Web Vault
  apps/web/src/app/vault/individual-vault/vault.component.ts
Labels: bug

#5307 [PM-233] "No Items" graphic is overlapping on several screens
  apps/browser/src/popup/scss/base.scss
  apps/browser/src/tools/popup/send/send-groupings.component.html
  apps/browser/src/vault/popup/components/vault/vault-items.component.html
Labels: bug

#5331 Update renovate config to match template
  .github/renovate.json
Labels: needs-qa

#5335 Explicitly specify zone.js version
  package.json
Labels: needs-qa

#5311 [SM-724] improve table header a11y; fix vertical layout shift
  bitwarden_license/bit-web/src/app/secrets-manager/shared/projects-list.component.html
Labels: accessibility

#5183 exit immediately after login command run
  apps/cli/src/program.ts
Labels: needs-qa

#5245 [PM-1909] Apply search input contrast fix to all pages
  apps/browser/src/popup/scss/base.scss
Labels: community-pr

#4835 [PM-1144] Fix last active (auto logout issue)
  apps/browser/src/popup/app.component.ts
Labels: community-pr

#4210 [PS-2022] Add autofill values for german websites
  apps/browser/src/autofill/services/autofill-constants.ts
Labels: community-pr

#5300 [PM-1176] Hovering over the `Learn More about auto-fill` link in the …
  apps/browser/src/_locales/en/messages.json
  apps/browser/src/popup/settings/autofill.component.html
  apps/browser/src/popup/settings/autofill.component.ts
Labels: bug

#5280 Defect/PM-1196 - SSO with Email 2FA Flow - Email Required error fixed
  libs/angular/src/auth/components/two-factor.component.ts
  libs/common/src/auth/abstractions/auth.service.ts
  libs/common/src/auth/login-strategies/login.strategy.spec.ts
  libs/common/src/auth/login-strategies/login.strategy.ts
  libs/common/src/auth/login-strategies/sso-login.strategy.ts
  libs/common/src/auth/models/domain/auth-result.ts
  libs/common/src/auth/models/request/two-factor-email.request.ts
  libs/common/src/auth/models/response/identity-two-factor.response.ts
  libs/common/src/auth/services/auth.service.ts
Labels: needs-qa

#5353 [PM-2088] Remove extra click handling from Collection row
  apps/web/src/app/vault/components/vault-items/vault-collection-row.component.html
Labels: needs-qa

#4788 [PM-1643] Tweak search box styling
  apps/browser/src/popup/scss/base.scss
  apps/browser/src/popup/scss/variables.scss
  apps/desktop/src/scss/header.scss
Labels: community-pr

#5414 [PM-2054] Updated Password Generator History to use Component Library on Web
  apps/web/src/app/tools/generator.component.ts
  apps/web/src/app/tools/password-generator-history.component.html
  libs/angular/src/tools/generator/components/password-generator-history.component.ts
Labels: web

#5337 [PM-1796] The autofill keyboard shortcut does not prompt a user to unlock a locked extension within an incognito browsing session
  apps/browser/src/background/runtime.background.ts
  apps/browser/src/browser/browserApi.ts
Labels: bug

#5451 [PM-2197] Fix memory leaks in Safari
  apps/browser/src/browser/browserApi.ts
  libs/angular/src/services/theming/theming.service.ts
Labels: needs-qa

#5325 [PM-595] Autofill doesn't work for logins without passwords
  apps/browser/src/autofill/services/autofill.service.ts
Labels: bug

#5477 Group jest packages
  .github/renovate.json
Labels: needs-qa

#4155 [PS-1950] [PS-1211] Added autofill for textareas
  apps/browser/src/autofill/content/autofill.js
Labels: community-pr

#5531 Defect/PM-2403 - Fix non-locally reproducible Master Password Invalid issue in Safari after SSO + 2FA login
  apps/browser/src/auth/popup/two-factor.component.ts
  apps/browser/src/browser/browserApi.ts
Labels: needs-qa

#5535 Defect/PM-2403 - Attempt 2 at fixing Safari - SSO + 2FA login flow not properly closing the tab
  apps/browser/src/auth/popup/two-factor-options.component.html
  apps/browser/src/auth/popup/two-factor-options.component.ts
  apps/browser/src/auth/popup/two-factor.component.ts
Labels: needs-qa
