Repository bitwarden/clients, pull requests merged in 2023-08, with the labels that each got.

#5371 [PM-2100] Create Unit Test Suite for autofill.service.ts
  apps/browser/src/autofill/jest/autofill-mocks.ts
  apps/browser/src/autofill/jest/testing-utils.ts
  apps/browser/src/autofill/services/abstractions/autofill.service.ts
  apps/browser/src/autofill/services/autofill.service.spec.ts
  apps/browser/src/autofill/services/autofill.service.ts
Labels: enhancement, browser

#5903 [AC-1537] Update trusted devices radio button label
  apps/web/src/locales/en/messages.json
  bitwarden_license/bit-web/src/app/auth/sso/sso.component.html
Labels: bug

#5934 [AC-1574] Replace reset password verbiage for permissions required toast
  apps/web/src/app/admin-console/organizations/members/components/member-dialog/member-dialog.component.ts
  apps/web/src/locales/en/messages.json
Labels: bug, needs-qa

#5855 [AC-1529] Update settings tab visibility to include device approvals
  apps/web/src/app/admin-console/organizations/settings/organization-settings-routing.module.ts
  apps/web/src/app/admin-console/organizations/settings/settings.component.html
  bitwarden_license/bit-web/src/app/admin-console/organizations/organizations-routing.module.ts
  libs/common/src/admin-console/abstractions/organization/organization.service.abstraction.ts
  libs/common/src/admin-console/models/domain/organization.ts
Labels: bug

#5384 [PM-2147] [BEEEP] Open login form used to unlock extension in a separate window instead of a tab
  apps/browser/src/_locales/en/messages.json
  apps/browser/src/autofill/background/context-menus.background.ts
  apps/browser/src/autofill/background/notification.background.ts
  apps/browser/src/autofill/notification/bar.html
  apps/browser/src/autofill/notification/bar.ts
  apps/browser/src/background/main.background.ts
  apps/browser/src/background/models/add-unlock-vault-queue-message.ts
  apps/browser/src/background/models/lockedVaultPendingNotificationsItem.ts
  apps/browser/src/background/models/notificationQueueMessageType.ts
  apps/browser/src/background/runtime.background.ts
  apps/browser/src/platform/browser/browser-api.ts
  apps/browser/src/platform/popup/abstractions/browser-popout-window.service.ts
  apps/browser/src/platform/popup/browser-popout-window.service.ts
Labels: browser

#5711 [PM-669] Right Click Autofill List Contains Incorrect Entries
  apps/browser/src/autofill/background/tabs.background.ts
  apps/browser/src/autofill/browser/cipher-context-menu-handler.ts
  apps/browser/src/platform/background.ts
  apps/browser/src/platform/listeners/index.ts
  apps/browser/src/platform/listeners/update-badge.ts
Labels: browser

#6008 [CL-114] Remove all caps styling from dialogs
  libs/components/src/dialog/dialog/dialog.component.html
Labels: needs-qa

#5766 [PM-2899] Implement ProtonPass json importer
  apps/cli/src/locales/en/messages.json
  apps/cli/src/tools/import.command.ts
  apps/cli/src/utils.ts
  apps/web/src/app/tools/import-export/import.component.html
  apps/web/src/app/tools/import-export/import.component.ts
  libs/importer/spec/protonpass-json-importer.spec.ts
  libs/importer/spec/test-data/protonpass-json/protonpass.json.ts
  libs/importer/src/importers/index.ts
  libs/importer/src/importers/protonpass/protonpass-json-importer.ts
  libs/importer/src/importers/protonpass/types/protonpass-json-type.ts
  libs/importer/src/models/import-options.ts
  libs/importer/src/services/import.service.ts
Labels: community-pr

#6003 [PM-2907] Shopify Passkey Broken on Firefox When Extension is Installed
  apps/browser/src/background/runtime.background.ts
  apps/browser/src/vault/fido2/content/content-script.ts
  libs/common/src/vault/abstractions/fido2/fido2-client.service.abstraction.ts
  libs/common/src/vault/services/fido2/fido2-client.service.ts
Labels: browser

#5853 [CL-111] remove h3 from bit-callout
  libs/components/src/callout/callout.component.html
  libs/components/src/callout/callout.component.ts
Labels: accessibility

#6073 [CL-120] add CL i18n entries to desktop and browser
  .vscode/settings.json
  apps/browser/src/_locales/en/messages.json
  apps/desktop/src/locales/en/messages.json
Labels: needs-qa

#6070 [CL-119] rename slots in nav-item
  libs/components/src/navigation/nav-group.component.html
  libs/components/src/navigation/nav-item.component.html
  libs/components/src/navigation/nav-item.stories.ts
Labels: needs-qa

#6076 Use useClass instead of useFactory
  libs/angular/src/services/jslib-services.module.ts
Labels: needs-qa

#6093 [PM-3590] Fix route in redirectGuard for browser login
  apps/browser/src/popup/app-routing.module.ts
Labels: needs-qa

#6097 PM-3590 - Browser - redirect to current tab on logged in
  apps/browser/src/popup/app-routing.module.ts
Labels: needs-qa

#6047 [AC-1552] Fixed issue where Org members with "Manage groups" permissions can view the Vault tab
  libs/common/src/admin-console/abstractions/organization/organization.service.abstraction.ts
Labels: needs-qa

#5859 [PM-3100] Fixes imports of "reduced" psono data
  libs/importer/spec/psono-json-importer.spec.ts
  libs/importer/spec/test-data/psono-json/reduced-website-logins.ts
  libs/importer/src/importers/psono/psono-json-importer.ts
  libs/importer/src/importers/psono/psono-json-types.ts
Labels: community-pr

#5695 [PM-2747] Add Support for Feature Flag of Autofill Version
  apps/browser/package.json
  apps/browser/src/autofill/content/abstractions/autofill-init.ts
  apps/browser/src/autofill/content/autofill-init.ts
  apps/browser/src/autofill/content/autofiller.ts
  apps/browser/src/autofill/content/notification-bar.ts
  apps/browser/src/autofill/content/trigger-autofill-script-injection.spec.ts
  apps/browser/src/autofill/content/trigger-autofill-script-injection.ts
  apps/browser/src/autofill/globals.d.ts
  apps/browser/src/autofill/services/abstractions/autofill.service.ts
  apps/browser/src/autofill/services/autofill.service.spec.ts
  apps/browser/src/autofill/services/autofill.service.ts
  apps/browser/src/background/main.background.ts
  apps/browser/src/background/runtime.background.ts
  apps/browser/src/manifest.json
  apps/browser/src/platform/browser/browser-api.spec.ts
  apps/browser/src/platform/browser/browser-api.ts
  apps/browser/test.setup.ts
  apps/browser/webpack.config.js
  libs/common/src/enums/feature-flag.enum.ts
Labels: browser

#6091 [PM-3588] Close duplicate single-action windows
  apps/browser/src/platform/popup/browser-popout-window.service.ts
Labels: browser

#6114 [PM-3226] Adding session to ReferenceEventRequest
  apps/web/src/app/auth/trial-initiation/trial-initiation.component.ts
  libs/common/src/models/request/reference-event.request.ts
Labels: web
