Repository bitwarden/clients, pull requests merged in 2023-03, with the labels that each got.

#4889 [SM-552] make string sort in TableDataSource case insensitive
  libs/components/src/table/table-data-source.ts
  libs/components/src/table/table.stories.ts
Labels: needs-qa

#4890 [PM-1205] Use page header for 2FA setup comp on org settings page to match othe…
  apps/web/src/app/organizations/settings/two-factor-setup.component.ts
  apps/web/src/auth/settings/two-factor-setup.component.html
  apps/web/src/auth/settings/two-factor-setup.component.ts
Labels: needs-qa

#4848 [AC-1084] Don't copy hidden spaces when selecting password
  libs/components/src/color-password/color-password.component.ts
Labels: needs-qa

#4913 [SM-589][SM-592] Remove router reuse hack
  apps/web/src/locales/en/messages.json
  bitwarden_license/bit-web/src/app/secrets-manager/overview/onboarding.component.html
  bitwarden_license/bit-web/src/app/secrets-manager/overview/onboarding.component.ts
  bitwarden_license/bit-web/src/app/secrets-manager/overview/overview.component.html
  bitwarden_license/bit-web/src/app/secrets-manager/overview/overview.component.ts
  bitwarden_license/bit-web/src/app/secrets-manager/sm-routing.module.ts
Labels: needs-qa

#4866 [PM-1165] Handle personal API login errors [cli]
  apps/cli/src/auth/commands/login.command.ts
Labels: community-pr

#4905 [PM-244] Items in free orgs generating TOTP codes for Premium users
  apps/web/src/app/vault/individual-vault/add-edit.component.ts
Labels: bug

#4899 [AC-1078] Provider Admin part of an org with Single Org Policy enabled cannot create new Client Organizations
  apps/web/src/app/settings/organization-plans.component.ts
Labels: needs-qa

#4845 [SM-401] Adding the ability to edit service account name
  apps/web/src/locales/en/messages.json
  bitwarden_license/bit-web/src/app/secrets-manager/overview/overview.component.ts
  bitwarden_license/bit-web/src/app/secrets-manager/service-accounts/dialog/service-account-dialog.component.html
  bitwarden_license/bit-web/src/app/secrets-manager/service-accounts/dialog/service-account-dialog.component.ts
  bitwarden_license/bit-web/src/app/secrets-manager/service-accounts/service-account.service.ts
  bitwarden_license/bit-web/src/app/secrets-manager/service-accounts/service-accounts-list.component.html
  bitwarden_license/bit-web/src/app/secrets-manager/service-accounts/service-accounts-list.component.ts
  bitwarden_license/bit-web/src/app/secrets-manager/service-accounts/service-accounts.component.html
  bitwarden_license/bit-web/src/app/secrets-manager/service-accounts/service-accounts.component.ts
  bitwarden_license/bit-web/src/app/secrets-manager/shared/new-menu.component.ts
Labels: needs-qa

#4808 [EC-475] Auto-save password prompt enhancements
  apps/browser/src/autofill/background/notification.background.ts
  apps/browser/src/autofill/content/message_handler.ts
  apps/browser/src/autofill/content/notification-bar.ts
  apps/browser/src/autofill/notification/bar.html
  apps/browser/src/autofill/notification/bar.js
  apps/browser/src/autofill/notification/bar.scss
  apps/browser/src/autofill/notification/bar.ts
  apps/browser/src/autofill/notification/variables.scss
  apps/browser/src/background/main.background.ts
  apps/browser/src/background/models/addChangePasswordQueueMessage.ts
  apps/browser/src/background/models/addLoginQueueMessage.ts
  apps/browser/src/background/runtime.background.ts
  apps/browser/src/browser/browserApi.ts
  apps/browser/src/popup/generator/generator.component.ts
  apps/browser/src/popup/scss/base.scss
  apps/browser/src/popup/services/popup-utils.service.ts
  apps/browser/src/vault/popup/components/vault/add-edit.component.ts
  apps/browser/webpack.config.js
  libs/angular/src/vault/components/add-edit.component.ts
  libs/common/src/abstractions/state.service.ts
  libs/common/src/services/state.service.ts
  libs/common/src/vault/types/add-edit-cipher-info.ts
Labels: needs-qa

#4969 [SM-365] make sidenav fixed
  bitwarden_license/bit-web/src/app/secrets-manager/layout/layout.component.html
Labels: needs-qa

#4901 [AC-1075] Member modal - custom permissions and external ID
  apps/web/src/app/organizations/members/components/member-dialog/member-dialog.component.html
Labels: needs-qa

#4971 [SM-521] Update help url again
  apps/web/src/app/organizations/members/components/member-dialog/member-dialog.component.html
Labels: needs-qa

#4981 [SM-521] Help link - third times the charm
  apps/web/src/app/organizations/members/components/member-dialog/member-dialog.component.html
Labels: needs-qa

#4704 [PM-469] [PM-1325] [PS-1165] [PS-1257] Small refactorings/improvements on the desktop app main
  apps/desktop/src/app/app.component.ts
  apps/desktop/src/main.ts
  apps/desktop/src/main/biometric/biometric.darwin.main.ts
  apps/desktop/src/main/biometric/biometric.windows.main.ts
  apps/desktop/src/main/biometric/biometrics.service.abstraction.ts
  apps/desktop/src/main/biometric/biometrics.service.spec.ts
  apps/desktop/src/main/biometric/biometrics.service.ts
  apps/desktop/src/main/biometric/index.ts
  apps/desktop/src/main/desktop-credential-storage-listener.ts
  apps/desktop/src/main/menu/menu.main.ts
  apps/desktop/src/main/power-monitor.main.ts
  apps/desktop/src/main/updater.main.ts
  apps/desktop/src/main/window.main.ts
  libs/common/src/services/system.service.ts
Labels: needs-qa

#4998 Disable the KDF warning
  apps/web/src/app/vault/individual-vault/vault.component.ts
Labels: needs-qa

#4994 [PM-1397] Display a warning when a user attempts to auto-fill an iframe
  apps/browser/src/autofill/background/service_factories/autofill-service.factory.ts
  apps/browser/src/autofill/content/autofill.js
  apps/browser/src/autofill/models/autofill-page-details.ts
  apps/browser/src/autofill/models/autofill-script.ts
  apps/browser/src/autofill/services/abstractions/autofill.service.ts
  apps/browser/src/autofill/services/autofill.service.ts
  apps/browser/src/background/main.background.ts
  libs/common/src/abstractions/settings.service.ts
  libs/common/src/abstractions/state.service.ts
  libs/common/src/misc/utils.ts
  libs/common/src/services/settings.service.ts
  libs/common/src/services/state.service.ts
  libs/common/src/vault/services/cipher.service.ts
Labels: needs-qa

#5021 [PM-1440] Fix showing multiple warnings
  libs/angular/src/auth/components/change-password.component.ts
Labels: needs-qa

#5022 [SM-661] Set secretsManager flag to true for cloud
  apps/web/config/cloud.json
Labels: needs-qa

#4910 [PM-107][PM-130] Remove fingerprint from request
  apps/browser/src/auth/popup/login-with-device.component.html
  apps/desktop/src/auth/login/login-with-device.component.html
  apps/web/src/auth/login/login-with-device.component.html
  libs/angular/src/auth/components/login-with-device.component.ts
  libs/common/src/auth/models/request/passwordless-create-auth.request.ts
Labels: needs-qa

#5062 PM-1195 - Copy send link fix on browser
  libs/common/src/models/view/send.view.ts
Labels: bug, browser

#5066 [PM-1408] Vault Items with null Folder Value not Handled Correctly
  apps/desktop/src/vault/app/vault/view.component.html
  libs/angular/src/vault/components/view.component.ts
Labels: needs-qa

#5097 [PM-1644] Resolve active tab using the wrong background color
  libs/components/src/tabs/shared/tab-list-item.directive.ts
Labels: needs-qa

#4926 [PM-283] Fix Reports UI behavior for premium and free users
  apps/web/src/app/admin-console/organizations/guards/is-paid-org.guard.ts
  apps/web/src/app/admin-console/organizations/reporting/organization-reporting-routing.module.ts
  apps/web/src/app/admin-console/organizations/reporting/reports-home.component.html
  apps/web/src/app/admin-console/organizations/reporting/reports-home.component.ts
  apps/web/src/app/admin-console/organizations/tools/exposed-passwords-report.component.ts
  apps/web/src/app/app.component.ts
  apps/web/src/app/reports/pages/cipher-report.component.ts
  apps/web/src/app/reports/pages/exposed-passwords-report.component.ts
  apps/web/src/app/reports/pages/inactive-two-factor-report.component.ts
  apps/web/src/app/reports/pages/reused-passwords-report.component.ts
  apps/web/src/app/reports/pages/unsecured-websites-report.component.ts
  apps/web/src/app/reports/pages/weak-passwords-report.component.ts
  apps/web/src/app/reports/shared/report-card/report-card.component.html
  apps/web/src/locales/en/messages.json
  libs/common/src/admin-console/models/domain/organization.ts
Labels: bug

#4479 [PS-2264] Make password protected exports support account's iterations and argon2
  apps/browser/src/background/main.background.ts
  apps/cli/src/bw.ts
  libs/angular/src/services/jslib-services.module.ts
  libs/common/spec/services/export.service.spec.ts
  libs/common/src/services/export.service.ts
  libs/importer/src/importers/bitwarden/bitwarden-password-protected-importer.ts
  libs/importer/src/importers/bitwarden/bitwarden-password-protected-types.ts
Labels: community-pr

#5130 Update Github discussion template
  .github/DISCUSSION_TEMPLATE/password-manager.yml
Labels: needs-qa
