Repository bitwarden/clients, pull requests merged in 2023-10, with the labels that each got.

#6194 [PM-2855] [PM-3034] Add Setting to Enable Autofill Overlay
  apps/browser/src/_locales/en/messages.json
  apps/browser/src/autofill/background/abstractions/overlay.background.ts
  apps/browser/src/autofill/background/notification.background.spec.ts
  apps/browser/src/autofill/background/notification.background.ts
  apps/browser/src/autofill/background/overlay.background.spec.ts
  apps/browser/src/autofill/background/overlay.background.ts
  apps/browser/src/autofill/content/abstractions/autofill-init.ts
  apps/browser/src/autofill/content/autofill-init.spec.ts
  apps/browser/src/autofill/content/autofill-init.ts
  apps/browser/src/autofill/content/bootstrap-autofill-overlay.ts
  apps/browser/src/autofill/content/bootstrap-autofill.ts
  apps/browser/src/autofill/jest/autofill-mocks.ts
  apps/browser/src/autofill/jest/testing-utils.ts
  apps/browser/src/autofill/overlay/abstractions/autofill-overlay-iframe.service.ts
  apps/browser/src/autofill/overlay/iframe-content/__snapshots__/autofill-overlay-iframe.service.spec.ts.snap
  apps/browser/src/autofill/overlay/iframe-content/autofill-overlay-button-iframe.spec.ts
  apps/browser/src/autofill/overlay/iframe-content/autofill-overlay-iframe-element.spec.ts
  apps/browser/src/autofill/overlay/iframe-content/autofill-overlay-iframe.service.spec.ts
  apps/browser/src/autofill/overlay/iframe-content/autofill-overlay-iframe.service.ts
  apps/browser/src/autofill/overlay/iframe-content/autofill-overlay-list-iframe.spec.ts
  apps/browser/src/autofill/overlay/pages/button/__snapshots__/autofill-overlay-button.spec.ts.snap
  apps/browser/src/autofill/overlay/pages/button/autofill-overlay-button.spec.ts
  apps/browser/src/autofill/overlay/pages/button/autofill-overlay-button.ts
  apps/browser/src/autofill/overlay/pages/button/bootstrap-autofill-overlay-button.ts
  apps/browser/src/autofill/overlay/pages/list/__snapshots__/autofill-overlay-list.spec.ts.snap
  apps/browser/src/autofill/overlay/pages/list/autofill-overlay-list.spec.ts
  apps/browser/src/autofill/overlay/pages/list/autofill-overlay-list.ts
  apps/browser/src/autofill/overlay/pages/list/bootstrap-autofill-overlay-list.ts
  apps/browser/src/autofill/overlay/pages/list/list.scss
  apps/browser/src/autofill/overlay/pages/shared/autofill-overlay-page-element.spec.ts
  apps/browser/src/autofill/overlay/pages/shared/autofill-overlay-page-element.ts
  apps/browser/src/autofill/services/abstractions/autofill-overlay-content.service.ts
  apps/browser/src/autofill/services/abstractions/autofill.service.ts
  apps/browser/src/autofill/services/autofill-overlay-content.service.spec.ts
  apps/browser/src/autofill/services/autofill-overlay-content.service.ts
  apps/browser/src/autofill/services/autofill.service.spec.ts
  apps/browser/src/autofill/services/autofill.service.ts
  apps/browser/src/autofill/services/collect-autofill-content.service.ts
  apps/browser/src/autofill/utils/autofill-overlay.enum.ts
  apps/browser/src/autofill/utils/utils.spec.ts
  apps/browser/src/autofill/utils/utils.ts
  apps/browser/src/background/runtime.background.ts
  apps/browser/src/manifest.json
  apps/browser/src/manifest.v3.json
  apps/browser/src/platform/browser/browser-api.ts
  apps/browser/src/popup/settings/autofill.component.html
  apps/browser/src/popup/settings/autofill.component.ts
  apps/browser/src/vault/popup/components/vault/current-tab.component.ts
  apps/browser/src/vault/popup/utils/vault-popout-window.ts
  apps/browser/test.setup.ts
  apps/browser/webpack.config.js
  libs/common/src/abstractions/settings.service.ts
  libs/common/src/enums/feature-flag.enum.ts
  libs/common/src/platform/abstractions/state.service.ts
  libs/common/src/platform/models/domain/account.ts
  libs/common/src/platform/services/state.service.ts
  libs/common/src/services/settings.service.ts
Labels: hold

#5313 [PM-2044] Fix hotkeys and context menu not resetting the vault timeout timer
  apps/browser/src/autofill/browser/context-menu-clicked-handler.spec.ts
  apps/browser/src/autofill/browser/context-menu-clicked-handler.ts
  apps/browser/src/background/main.background.ts
  apps/browser/src/background/runtime.background.ts
Labels: community-pr, browser

#6561 [PM-4293] Update duo and add allow-popups and allow-popups-to-escape-sandbox
  apps/browser/src/auth/popup/two-factor.component.html
  apps/desktop/src/auth/two-factor.component.html
  apps/web/src/app/auth/two-factor.component.html
Labels: needs-qa

#6434 [PM-4127] Bugfix - Check original target tab URL before executing deferred action due to reprompt
  apps/browser/src/autofill/content/autofill.js
  apps/browser/src/autofill/services/insert-autofill-content.service.spec.ts
  apps/browser/src/autofill/services/insert-autofill-content.service.ts
  apps/browser/src/vault/popup/components/vault/view.component.ts
Labels: bug, browser

#6576 [PM-4296] Cannot login to Bitwarden with FIDO2 WebAuthn if extension is installed and logged in
  apps/browser/src/vault/fido2/content/page-script.ts
  libs/common/src/vault/services/fido2/fido2-client.service.spec.ts
  libs/common/src/vault/services/fido2/fido2-client.service.ts
Labels: needs-qa

#6509 [PM-2855] Add Settings to Enable Autofill Overlay
  apps/browser/src/_locales/en/messages.json
  apps/browser/src/autofill/utils/autofill-overlay.enum.ts
  apps/browser/src/manifest.json
  apps/browser/src/manifest.v3.json
  apps/browser/src/platform/browser/browser-api.ts
  apps/browser/src/popup/settings/autofill.component.html
  apps/browser/src/popup/settings/autofill.component.ts
  libs/common/src/abstractions/settings.service.ts
  libs/common/src/platform/abstractions/state.service.ts
  libs/common/src/platform/models/domain/account.ts
  libs/common/src/platform/services/state.service.ts
  libs/common/src/services/settings.service.ts
Labels: browser

#6600 [PM-4366] Update popout windows to open as a `popup` window type rather than a `normal` window type
  apps/browser/src/platform/popup/browser-popout-window.service.ts
Labels: browser

#6510 [PM-3034] Modify Autofill Callout to Consider Autofill Overlay Visibility
  apps/browser/src/_locales/en/messages.json
  apps/browser/src/vault/popup/components/vault/current-tab.component.ts
Labels: browser

#6496 [PM-4141] Bugfix - Non-Premium accounts can autofill TOTP codes with the autofill keyboard shortcut
  apps/browser/src/autofill/services/autofill.service.spec.ts
  apps/browser/src/autofill/services/autofill.service.ts
Labels: bug, browser

#6668 [AC-1706] Show Discounted Prices
  apps/web/src/app/billing/individual/user-subscription.component.html
  apps/web/src/app/billing/individual/user-subscription.component.ts
  apps/web/src/app/billing/organizations/organization-subscription-cloud.component.html
  apps/web/src/app/billing/organizations/organization-subscription-cloud.component.ts
  apps/web/src/app/billing/organizations/sm-subscribe-standalone.component.html
  apps/web/src/app/billing/organizations/sm-subscribe-standalone.component.ts
  apps/web/src/app/billing/shared/sm-subscribe.component.ts
  apps/web/src/locales/en/messages.json
  libs/common/src/billing/models/response/organization-subscription.response.ts
  libs/common/src/billing/models/response/subscription.response.ts
Labels: needs-qa

#6604 [PM-2052] Migrate bulk restore component
  apps/web/src/app/admin-console/organizations/members/components/bulk/bulk-restore-revoke.component.html
  apps/web/src/app/admin-console/organizations/members/components/bulk/bulk-restore-revoke.component.ts
  apps/web/src/app/admin-console/organizations/members/people.component.ts
Labels: needs-qa

#6686 [AC-1757] ConfigService dependency fix
  apps/web/src/app/vault/components/vault-items/vault-items.component.html
  apps/web/src/app/vault/components/vault-items/vault-items.component.ts
  apps/web/src/app/vault/core/views/collection-admin.view.ts
  apps/web/src/app/vault/individual-vault/vault-header/vault-header.component.html
  apps/web/src/app/vault/individual-vault/vault-header/vault-header.component.ts
  apps/web/src/app/vault/org-vault/vault-header/vault-header.component.html
  apps/web/src/app/vault/org-vault/vault-header/vault-header.component.ts
  libs/common/src/vault/models/view/collection.view.ts
Labels: bug

#6620 [PM-3572] 'Custom/Log out' vault timeout changes to 'Lock'
  apps/browser/src/popup/settings/settings.component.ts
Labels: needs-qa

#6696 [PM-4208] Fix lock guard redirect
  libs/angular/src/auth/guards/lock.guard.ts
Labels: needs-qa

#6706 [PM-4553] [Defect] Browser fallback fails on first click on bitwarden
  apps/browser/src/vault/fido2/content/page-script.ts
Labels: needs-qa

#6713 [PM-4580] Bypass user verification of passkeys on add-edit component
  apps/browser/src/vault/popup/components/vault/add-edit.component.ts
Labels: needs-qa

#6516 [PM-3032] Show Matching Logins When User Interacts with Field
  apps/browser/src/autofill/background/abstractions/overlay.background.ts
  apps/browser/src/autofill/background/overlay.background.spec.ts
  apps/browser/src/autofill/background/overlay.background.ts
  apps/browser/src/autofill/background/tabs.background.spec.ts
  apps/browser/src/autofill/background/tabs.background.ts
  apps/browser/src/autofill/constants.ts
  apps/browser/src/autofill/content/abstractions/autofill-init.ts
  apps/browser/src/autofill/content/autofill-init.spec.ts
  apps/browser/src/autofill/content/autofill-init.ts
  apps/browser/src/autofill/jest/autofill-mocks.ts
  apps/browser/src/autofill/overlay/abstractions/autofill-overlay-list.ts
  apps/browser/src/autofill/overlay/iframe-content/autofill-overlay-list-iframe.ts
  apps/browser/src/autofill/overlay/pages/list/__snapshots__/autofill-overlay-list.spec.ts.snap
  apps/browser/src/autofill/overlay/pages/list/autofill-overlay-list.spec.ts
  apps/browser/src/autofill/overlay/pages/list/autofill-overlay-list.ts
  apps/browser/src/autofill/overlay/pages/shared/autofill-overlay-page-element.spec.ts
  apps/browser/src/autofill/services/abstractions/autofill-overlay-content.service.ts
  apps/browser/src/autofill/services/autofill-overlay-content.service.spec.ts
  apps/browser/src/autofill/services/autofill-overlay-content.service.ts
  apps/browser/src/background/main.background.ts
  apps/browser/src/vault/popup/components/vault/add-edit.component.ts
  apps/browser/src/vault/popup/components/vault/view.component.ts
  apps/browser/src/vault/popup/utils/vault-popout-window.spec.ts
  apps/browser/src/vault/popup/utils/vault-popout-window.ts
  libs/common/src/vault/models/view/cipher.view.ts
Labels: browser

#6474 [PM-4163] Fix protonpass importer when totp field is not a URL
  libs/importer/spec/test-data/protonpass-json/protonpass.json.ts
  libs/importer/src/importers/protonpass/protonpass-json-importer.ts
Labels: community-pr

#6684 [PM-105] Premium Badge Send File
  apps/web/src/app/tools/send/add-edit.component.html
  libs/angular/src/tools/send/add-edit.component.ts
Labels: needs-qa

#5529 [PM-2432] Desktop: Modify switch account dropdown/dialog for accessibility
  apps/desktop/src/app/layout/account-switcher.component.html
Labels: community-pr
