Repository bitwarden/clients, pull requests merged in 2023-11, with the labels that each got.

#6803 [PM-4704] Filter non-webauthn calls to credmanager apis
  apps/browser/src/vault/fido2/content/page-script.ts
Labels: needs-qa

#6801 [PM-4531] Completely disable fido2 injection for excluded sites
  apps/browser/src/vault/fido2/content/content-script.ts
Labels: needs-qa

#6783 [PM-4678] [Defect] Passkey browser fallback broken on iCloud
  apps/browser/src/background/runtime.background.ts
  apps/browser/src/vault/fido2/content/page-script.ts
Labels: needs-qa

#6773 disable code duplication check in unit tests
  .codescene/code-health-rules.json
Labels: DevOps

#6726 [PM-4590] Cached Page Details of Formless Input Fields Breaks Autofill
  apps/browser/src/autofill/services/collect-autofill-content.service.ts
Labels: browser

#6296 [PM-3914] Refactor Browser Extension Popout Windows
  apps/browser/src/auth/popup/two-factor.component.ts
  apps/browser/src/auth/popup/utils/auth-popout-window.spec.ts
  apps/browser/src/auth/popup/utils/auth-popout-window.ts
  apps/browser/src/autofill/background/notification.background.ts
  apps/browser/src/autofill/browser/context-menu-clicked-handler.ts
  apps/browser/src/autofill/content/message_handler.ts
  apps/browser/src/autofill/notification/bar.ts
  apps/browser/src/autofill/services/autofill.service.spec.ts
  apps/browser/src/autofill/services/autofill.service.ts
  apps/browser/src/background/commands.background.ts
  apps/browser/src/background/main.background.ts
  apps/browser/src/background/runtime.background.ts
  apps/browser/src/platform/browser/browser-api.spec.ts
  apps/browser/src/platform/browser/browser-api.ts
  apps/browser/src/platform/popup/abstractions/browser-popout-window.service.ts
  apps/browser/src/platform/popup/abstractions/browser-popup-utils.abstractions.ts
  apps/browser/src/platform/popup/browser-popout-window.service.ts
  apps/browser/src/platform/popup/browser-popup-utils.spec.ts
  apps/browser/src/platform/popup/browser-popup-utils.ts
  apps/browser/src/popup/components/pop-out.component.ts
  apps/browser/src/popup/components/private-mode-warning.component.ts
  apps/browser/src/popup/services/init.service.ts
  apps/browser/src/popup/services/popup-close-warning.service.ts
  apps/browser/src/popup/services/popup-utils.service.ts
  apps/browser/src/popup/services/services.module.ts
  apps/browser/src/popup/settings/settings.component.ts
  apps/browser/src/popup/tabs.component.ts
  apps/browser/src/tools/popup/components/file-popout-callout.component.ts
  apps/browser/src/tools/popup/send/send-add-edit.component.ts
  apps/browser/src/tools/popup/send/send-groupings.component.ts
  apps/browser/src/tools/popup/send/send-type.component.ts
  apps/browser/src/tools/popup/services/file-popout-utils.service.ts
  apps/browser/src/vault/fido2/browser-fido2-user-interface.service.ts
  apps/browser/src/vault/popup/components/fido2/fido2.component.ts
  apps/browser/src/vault/popup/components/vault/add-edit.component.ts
  apps/browser/src/vault/popup/components/vault/current-tab.component.ts
  apps/browser/src/vault/popup/components/vault/vault-filter.component.ts
  apps/browser/src/vault/popup/components/vault/vault-items.component.ts
  apps/browser/src/vault/popup/components/vault/view.component.ts
  apps/browser/src/vault/popup/utils/vault-popout-window.spec.ts
  apps/browser/src/vault/popup/utils/vault-popout-window.ts
  apps/browser/test.setup.ts
Labels: browser

#6848 [PM-4744] Page Details that Update after Mutation Observer has Triggered Do Not Update within Overlay Background
  apps/browser/src/autofill/services/abstractions/autofill-overlay-content.service.ts
  apps/browser/src/autofill/services/autofill-overlay-content.service.spec.ts
  apps/browser/src/autofill/services/autofill-overlay-content.service.ts
  apps/browser/src/autofill/services/collect-autofill-content.service.ts
Labels: needs-qa

#6863 [PM-4743] Windows Chromium Browser is Not Updating Overlay Ciphers on Tab Update
  apps/browser/src/autofill/background/tabs.background.spec.ts
  apps/browser/src/autofill/background/tabs.background.ts
Labels: browser

#6864 [PM-4763] Fixing Issues with the Overlay UI Positioning and Presentation
  apps/browser/src/autofill/background/overlay.background.spec.ts
  apps/browser/src/autofill/background/overlay.background.ts
  apps/browser/src/autofill/services/autofill-overlay-content.service.spec.ts
  apps/browser/src/autofill/services/autofill-overlay-content.service.ts
  apps/browser/src/autofill/services/collect-autofill-content.service.ts
Labels: browser

#5883 [PM-3164] made KDF modals cancel button close it
  apps/web/src/app/settings/change-kdf/change-kdf-confirmation.component.html
Labels: community-pr

#5769 [PM-2903] fix : don't set pin if not provided
  libs/angular/src/auth/components/set-pin.component.ts
Labels: community-pr

#6827 [PM-4746] Fix fastmail username forwarder by changing url: to forDomain: in the...
  libs/common/src/tools/generator/username/email-forwarders/fastmail-forwarder.ts
Labels: community-pr

#6637 [PM-4414] Bugfix - On page URL change, display notifications that have not been dismissed nor expired
  apps/browser/src/autofill/background/notification.background.ts
  apps/browser/src/autofill/constants.ts
  apps/browser/src/autofill/content/notification-bar.ts
  apps/browser/src/background/models/notificationQueueMessage.ts
Labels: bug, browser

#4648 [PM-969] Fix card number not being populated for Greek provider Eurobank.
  apps/browser/src/autofill/services/autofill-constants.ts
Labels: community-pr, browser

#6889 Add Platform Entry to `CODEOWNERS`
  .github/CODEOWNERS
Labels: needs-qa

#6700 [PM-3574] Fix leak of login credentials to foreign origin due to race condition during autofill
  apps/browser/src/autofill/content/abstractions/autofill-init.ts
  apps/browser/src/autofill/content/autofill-init.spec.ts
  apps/browser/src/autofill/content/autofill-init.ts
  apps/browser/src/autofill/services/autofill.service.spec.ts
  apps/browser/src/autofill/services/autofill.service.ts
Labels: browser

#6847 [PM-4773] Google Passkey workarounds
  libs/common/src/vault/services/fido2/fido2-client.service.ts
Labels: community-pr

#6907 AC-1694 Remove Can Edit Except PW ciphers from Inactive 2FA
  apps/web/src/app/reports/pages/inactive-two-factor-report.component.ts
Labels: needs-qa

#6930 [PM-4893] Pin Autofill Overlay Dependencies
  .github/renovate.json
  package.json
Labels: needs-qa
