Repository bitwarden/clients, pull requests merged in 2023-09, with the labels that each got.

#3460 [PS-1438] Prevent new line feed when selecting and copying passwords
  apps/desktop/src/scss/misc.scss
  libs/angular/src/directives/copy-text.directive.ts
Labels: community-pr

#5974 [PM-3326] [CLI] Add minNumber, minSpecial and ambiguous password generation options
  apps/cli/src/program.ts
  apps/cli/src/tools/generate.command.ts
  apps/cli/src/utils.ts
Labels: community-pr

#6221 [PM-3577] Refactor Electron iframes
  apps/browser/src/auth/popup/login.component.html
  apps/browser/src/auth/popup/register.component.html
  apps/browser/src/auth/popup/two-factor.component.html
  apps/desktop/src/auth/login/login.component.html
  apps/desktop/src/auth/register.component.html
  apps/desktop/src/auth/two-factor.component.html
  apps/web/src/app/auth/login/login.component.html
  apps/web/src/app/auth/register-form/register-form.component.html
  apps/web/src/app/auth/two-factor.component.html
Labels: needs-qa

#6148 [PM-3704] Autofill Command Should Not Attempt to Fill If Fields Are Not Found in Page Details
  apps/browser/src/autofill/services/autofill.service.ts
Labels: browser

#6027 [PM-3442] Change AnonAddy to addy.io
  libs/angular/src/tools/generator/components/generator.component.ts
  libs/common/src/tools/generator/username/email-forwarders/anon-addy-forwarder.ts
Labels: community-pr

#5939 [PM-3285] Autofill v2 Feature Branch
  apps/browser/package.json
  apps/browser/src/autofill/constants.ts
  apps/browser/src/autofill/content/abstractions/autofill-init.ts
  apps/browser/src/autofill/content/autofill-init.spec.ts
  apps/browser/src/autofill/content/autofill-init.ts
  apps/browser/src/autofill/content/autofiller.ts
  apps/browser/src/autofill/content/autofillv2.ts
  apps/browser/src/autofill/content/notification-bar.ts
  apps/browser/src/autofill/content/trigger-autofill-script-injection.spec.ts
  apps/browser/src/autofill/content/trigger-autofill-script-injection.ts
  apps/browser/src/autofill/globals.d.ts
  apps/browser/src/autofill/jest/autofill-mocks.ts
  apps/browser/src/autofill/jest/testing-utils.ts
  apps/browser/src/autofill/models/autofill-field.ts
  apps/browser/src/autofill/models/autofill-page-details.ts
  apps/browser/src/autofill/models/autofill-script.ts
  apps/browser/src/autofill/services/abstractions/autofill.service.ts
  apps/browser/src/autofill/services/abstractions/collect-autofill-content.service.ts
  apps/browser/src/autofill/services/abstractions/dom-element-visibility.service.ts
  apps/browser/src/autofill/services/abstractions/insert-autofill-content.service.ts
  apps/browser/src/autofill/services/autofill.service.spec.ts
  apps/browser/src/autofill/services/autofill.service.ts
  apps/browser/src/autofill/services/collect-autofill-content.service.spec.ts
  apps/browser/src/autofill/services/collect-autofill-content.service.ts
  apps/browser/src/autofill/services/dom-element-visibility.service.spec.ts
  apps/browser/src/autofill/services/dom-element-visibility.service.ts
  apps/browser/src/autofill/services/insert-autofill-content.service.spec.ts
  apps/browser/src/autofill/services/insert-autofill-content.service.ts
  apps/browser/src/autofill/types/index.ts
  apps/browser/src/background/main.background.ts
  apps/browser/src/background/runtime.background.ts
  apps/browser/src/manifest.json
  apps/browser/src/platform/browser/browser-api.spec.ts
  apps/browser/src/platform/browser/browser-api.ts
  apps/browser/test.setup.ts
  apps/browser/tsconfig.spec.json
  apps/browser/webpack.config.js
  libs/common/src/enums/feature-flag.enum.ts
Labels: browser

#6096 [PM-3612] Bug - Reprompt prevents autofill keyboard shortcut from cycling fill ciphers
  apps/browser/src/autofill/services/autofill.service.ts
Labels: browser

#6252 [PM-3822] Only show popout warning on file SendAddEdit
  apps/browser/src/tools/popup/send/send-add-edit.component.html
Labels: browser

#6262 [PM-3881] Fix ENV=cloud npm run build:oss:watch
  apps/web/config/cloud.json
  apps/web/config/qa.json
Labels: community-pr

#6276 [PM-3878] Setting send password to null if it is empty
  apps/desktop/src/app/tools/send/add-edit.component.ts
  libs/angular/src/tools/send/add-edit.component.ts
Labels: bug

#6310 [PM-3928] HideEmail enable validation moved to UpdateFormValues
  libs/angular/src/tools/send/add-edit.component.ts
Labels: bug

#6317 [PM-3982] Improved validation on send hide email policy subscriber
  libs/angular/src/tools/send/add-edit.component.ts
Labels: needs-qa

#6242 [PM-3735] Bugfix - Context menu autofill with a locked vault with a sole entry that has MPR enabled fails silently
  apps/browser/src/autofill/browser/context-menu-clicked-handler.ts
Labels: browser

#6280 [PM-3613] Check for page change before delayed auto-fill action execution
  apps/browser/src/autofill/content/autofill.js
  apps/browser/src/autofill/services/insert-autofill-content.service.spec.ts
  apps/browser/src/autofill/services/insert-autofill-content.service.ts
Labels: browser

#6141 [PM-2481] [PM-3465] Integrate Shadow DOM Support Into Autofill v2 and Optimize Collection of Page Details (special thanks to @RafaelKr)
  apps/browser/src/autofill/models/autofill-form.ts
  apps/browser/src/autofill/services/abstractions/collect-autofill-content.service.ts
  apps/browser/src/autofill/services/collect-autofill-content.service.spec.ts
  apps/browser/src/autofill/services/collect-autofill-content.service.ts
  apps/browser/src/autofill/services/dom-element-visibility.service.ts
  apps/browser/src/autofill/services/insert-autofill-content.service.ts
Labels: browser

#6189 [PM-3730] Master Password Re-prompt Enabled Items Invoke Popup Window Automatically When Autofill on Page Load is Enabled
  apps/browser/src/_locales/en/messages.json
  apps/browser/src/autofill/services/autofill.service.ts
  apps/browser/src/vault/popup/components/vault/add-edit.component.html
  apps/browser/src/vault/popup/components/vault/add-edit.component.ts
  libs/angular/src/vault/components/add-edit.component.ts
Labels: browser

#6381 [BEEEP] Add Braintree sandbox API to permitted script sources in CSP
  apps/web/webpack.config.js
Labels: needs-qa

#6399 [PM-4089] fix typo in base.scss
  apps/desktop/src/scss/base.scss
Labels: community-pr

#4056 [PS-1878] Feature/selfhost anonaddy
  apps/browser/src/_locales/en/messages.json
  apps/browser/src/tools/popup/generator/generator.component.html
  apps/desktop/src/app/tools/generator.component.html
  apps/desktop/src/locales/en/messages.json
  apps/web/src/app/tools/generator.component.html
  apps/web/src/app/tools/generator.component.ts
  apps/web/src/locales/en/messages.json
  apps/web/webpack.config.js
  libs/common/src/tools/generator/username/email-forwarders/anon-addy-forwarder.ts
  libs/common/src/tools/generator/username/email-forwarders/forwarder-options.ts
  libs/common/src/tools/generator/username/username-generation-options.ts
  libs/common/src/tools/generator/username/username-generation.service.ts
Labels: community-pr

#6050 [PM-3455] Allow adding and autofilling Cards and Identities via Context Menu
  apps/browser/src/_locales/en/messages.json
  apps/browser/src/autofill/browser/cipher-context-menu-handler.spec.ts
  apps/browser/src/autofill/browser/cipher-context-menu-handler.ts
  apps/browser/src/autofill/browser/context-menu-clicked-handler.spec.ts
  apps/browser/src/autofill/browser/context-menu-clicked-handler.ts
  apps/browser/src/autofill/browser/main-context-menu-handler.spec.ts
  apps/browser/src/autofill/browser/main-context-menu-handler.ts
  apps/browser/src/autofill/constants.ts
  apps/browser/src/autofill/services/abstractions/autofill.service.ts
  apps/browser/src/autofill/services/autofill.service.ts
  apps/browser/src/autofill/types/index.ts
  apps/browser/src/background/runtime.background.ts
  apps/browser/src/platform/popup/abstractions/browser-popout-window.service.ts
  apps/browser/src/platform/popup/browser-popout-window.service.ts
  apps/browser/src/vault/popup/components/vault/add-edit.component.ts
Labels: browser

#6318 [PM-3704] Autofill Command Should Not Attempt to Fill If Fields Are Not Found in Page Details
  apps/browser/src/autofill/services/autofill.service.spec.ts
  apps/browser/src/autofill/services/autofill.service.ts
Labels: browser
