Repository bitwarden/clients, pull requests merged in 2023-01, with the labels that each got.

#3691 [SG-58] Avatar color selector
  apps/browser/src/background/main.background.ts
  apps/browser/src/background/runtime.background.ts
  apps/desktop/src/app/layout/account-switcher.component.html
  apps/desktop/src/app/layout/account-switcher.component.ts
  apps/web/src/app/components/dynamic-avatar.component.ts
  apps/web/src/app/components/selectable-avatar.component.ts
  apps/web/src/app/layouts/navbar.component.html
  apps/web/src/app/settings/change-avatar.component.html
  apps/web/src/app/settings/change-avatar.component.ts
  apps/web/src/app/settings/profile.component.html
  apps/web/src/app/settings/profile.component.ts
  apps/web/src/app/shared/loose-components.module.ts
  apps/web/src/app/vault/organization-badge/organization-name-badge.component.ts
  apps/web/src/locales/en/messages.json
  libs/angular/src/services/jslib-services.module.ts
  libs/common/src/abstractions/account/avatar-update.service.ts
  libs/common/src/abstractions/api.service.ts
  libs/common/src/abstractions/state.service.ts
  libs/common/src/misc/utils.ts
  libs/common/src/models/domain/account.ts
  libs/common/src/models/request/update-avatar.request.ts
  libs/common/src/models/response/profile.response.ts
  libs/common/src/services/account/avatar-update.service.ts
  libs/common/src/services/api.service.ts
  libs/common/src/services/state.service.ts
  libs/common/src/services/sync/sync.service.ts
  libs/components/src/avatar/avatar.component.ts
Labels: enhancement, web, needs-qa

#4318 [PS-2118] Update 2fa.directory API URI
  apps/web/src/app/reports/pages/inactive-two-factor-report.component.ts
  apps/web/webpack.config.js
Labels: community-pr

#4316 [PS-2112] browser - Fix scrolling glitch in virtual list
  apps/browser/src/popup/components/cipher-row.component.html
  apps/browser/src/popup/scss/box.scss
  apps/browser/src/popup/vault/vault-filter.component.html
  apps/browser/src/popup/vault/vault-items.component.html
Labels: community-pr

#4380 [PS-2120] Forcing vault to refresh when the vault is purged or new items are imported
  apps/web/src/app/organizations/tools/import-export/org-import.component.ts
  apps/web/src/app/settings/purge-vault.component.ts
  apps/web/src/app/tools/import-export/import.component.ts
Labels: bug, web

#4046 [PS-1872] remember me label triggers toggle
  apps/web/src/app/accounts/login/login.component.html
  apps/web/src/app/accounts/login/login.module.ts
Labels: community-pr

#4478 [PS-2263] Keeper CSV import: import TOTP to correct field
  libs/common/spec/importers/keeper-csv-importer.spec.ts
  libs/common/spec/importers/test-data/keeper-csv/testdata.csv.ts
  libs/common/src/importers/keeper/keeper-csv-importer.ts
Labels: community-pr

#4468 [PS-2251] Implement argon2 kdf
  apps/browser/src/manifest.v3.json
  apps/browser/webpack.config.js
  apps/desktop/webpack.main.js
  apps/desktop/webpack.renderer.js
  apps/web/src/app/settings/change-kdf.component.ts
  apps/web/src/locales/en/messages.json
  apps/web/webpack.config.js
  libs/angular/src/components/register.component.ts
  libs/angular/src/components/set-password.component.ts
  libs/common/spec/services/export.service.spec.ts
  libs/common/src/abstractions/cryptoFunction.service.ts
  libs/common/src/enums/kdfType.ts
  libs/common/src/services/crypto.service.ts
  libs/common/src/services/export.service.ts
  libs/common/src/services/webCryptoFunction.service.ts
  libs/node/src/services/node-crypto-function.service.ts
  package-lock.json
  package.json
Labels: community-pr

#4578 [PS-2365] Kdf Configuration Options for Argon2
  apps/cli/src/commands/login.command.ts
  apps/cli/src/commands/unlock.command.ts
  apps/web/src/app/organizations/members/components/reset-password.component.ts
  apps/web/src/app/settings/change-email.component.ts
  apps/web/src/app/settings/change-kdf.component.html
  apps/web/src/app/settings/change-kdf.component.ts
  apps/web/src/app/settings/emergency-access-takeover.component.ts
  apps/web/src/app/vault/vault.component.ts
  apps/web/src/locales/en/messages.json
  libs/angular/src/components/change-password.component.ts
  libs/angular/src/components/lock.component.ts
  libs/angular/src/components/register.component.ts
  libs/angular/src/components/set-password.component.ts
  libs/angular/src/components/set-pin.component.ts
  libs/angular/src/components/update-password.component.ts
  libs/angular/src/components/update-temp-password.component.ts
  libs/common/src/abstractions/crypto.service.ts
  libs/common/src/abstractions/organization-user/responses/organization-user.response.ts
  libs/common/src/abstractions/state.service.ts
  libs/common/src/enums/kdfType.ts
  libs/common/src/importers/bitwarden-password-protected-importer.ts
  libs/common/src/misc/logInStrategies/logIn.strategy.ts
  libs/common/src/models/domain/account.ts
  libs/common/src/models/domain/kdf-config.ts
  libs/common/src/models/request/kdf.request.ts
  libs/common/src/models/request/register.request.ts
  libs/common/src/models/request/set-password.request.ts
  libs/common/src/models/response/emergency-access.response.ts
  libs/common/src/models/response/identity-token.response.ts
  libs/common/src/models/response/prelogin.response.ts
  libs/common/src/services/auth.service.ts
  libs/common/src/services/crypto.service.ts
  libs/common/src/services/export.service.ts
  libs/common/src/services/keyConnector.service.ts
  libs/common/src/services/state.service.ts
Labels: community-pr

#4254 Add individual packages hash files to release
  .github/workflows/release-desktop.yml
Labels: hold
