Repository bitwarden/clients, pull requests merged in 2023-12, with the labels that each got.

#7051 [AC-1873] Only assign user in the front-end if using Flexible Collections
  apps/web/src/app/vault/components/collection-dialog/collection-dialog.component.ts
Labels: bug

#6799 [PM-4709] Browser extension: prevent crash when registering new credential
  apps/browser/src/vault/fido2/content/page-script.ts
Labels: community-pr

#6986 Remove tech-leads as default codeowner
  .github/CODEOWNERS
Labels: needs-qa

#7045 [PM-4926] Only Keep Active User Alive When A View is Open
  libs/common/src/services/vault-timeout/vault-timeout.service.spec.ts
  libs/common/src/services/vault-timeout/vault-timeout.service.ts
Labels: needs-qa

#7118 Update ownership in renovate config
  .github/renovate.json
Labels: needs-qa

#7110 [PM-5148] Removing Browser Autofill Override Setting and Add Message
  apps/browser/src/_locales/en/messages.json
  apps/browser/src/autofill/popup/settings/autofill.component.html
  apps/browser/src/autofill/popup/settings/autofill.component.ts
  apps/browser/src/manifest.json
  apps/browser/src/manifest.v3.json
  apps/browser/src/platform/browser/browser-api.ts
Labels: browser

#6408 [PM-4035] Import LastPass Export Page Data
  apps/browser/src/_locales/en/messages.json
  apps/browser/src/autofill/notification/bar.ts
  apps/browser/src/background/main.background.ts
  apps/browser/src/tools/background/abstractions/fileless-importer.background.ts
  apps/browser/src/tools/background/fileless-importer.background.spec.ts
  apps/browser/src/tools/background/fileless-importer.background.ts
  apps/browser/src/tools/content/abstractions/lp-fileless-importer.ts
  apps/browser/src/tools/content/lp-fileless-importer.spec.ts
  apps/browser/src/tools/content/lp-fileless-importer.ts
  apps/browser/src/tools/enums/fileless-import.enums.ts
Labels: browser, needs-qa

#6407 [PM-4033] Display import prompt to user
  apps/browser/src/_locales/en/messages.json
  apps/browser/src/autofill/background/notification.background.ts
  apps/browser/src/autofill/content/notification-bar.ts
  apps/browser/src/autofill/jest/testing-utils.ts
  apps/browser/src/autofill/notification/bar.html
  apps/browser/src/autofill/notification/bar.scss
  apps/browser/src/autofill/notification/bar.ts
  apps/browser/src/autofill/notification/models/add-request-fileless-import-queue-message.ts
  apps/browser/src/autofill/notification/models/notification-queue-message-type.ts
  apps/browser/src/autofill/shared/styles/variables.scss
  apps/browser/src/background/main.background.ts
  apps/browser/src/tools/background/abstractions/fileless-importer.background.ts
  apps/browser/src/tools/background/fileless-importer.background.spec.ts
  apps/browser/src/tools/background/fileless-importer.background.ts
  apps/browser/src/tools/content/abstractions/lp-fileless-importer.ts
  apps/browser/src/tools/content/lp-fileless-importer.spec.ts
  apps/browser/src/tools/content/lp-fileless-importer.ts
  apps/browser/src/tools/enums/fileless-import.enums.ts
Labels: browser, needs-qa

#6953 [PM-4923] Form elements that fade into view contain incorrectly cached page details
  apps/browser/src/autofill/services/collect-autofill-content.service.spec.ts
  apps/browser/src/autofill/services/collect-autofill-content.service.ts
Labels: browser

#7114 [PM-5144] Use sync fs in desktop i18n loading
  apps/desktop/src/platform/services/i18n.main.service.ts
Labels: needs-qa

#7001 [PM-5035] Fix autofill overlay clickjacking vulnerability that can be triggered by a malicious extension
  apps/browser/src/autofill/background/abstractions/overlay.background.ts
  apps/browser/src/autofill/background/overlay.background.spec.ts
  apps/browser/src/autofill/background/overlay.background.ts
  apps/browser/src/autofill/content/abstractions/autofill-init.ts
  apps/browser/src/autofill/content/autofill-init.spec.ts
  apps/browser/src/autofill/content/autofill-init.ts
  apps/browser/src/autofill/overlay/iframe-content/autofill-overlay-iframe.service.spec.ts
  apps/browser/src/autofill/overlay/iframe-content/autofill-overlay-iframe.service.ts
  apps/browser/src/autofill/overlay/pages/list/autofill-overlay-list.ts
Labels: browser

#6826 [PM-934] Autofill not working until page has been refreshed
  apps/browser/src/autofill/background/overlay.background.ts
  apps/browser/src/autofill/background/service_factories/autofill-service.factory.ts
  apps/browser/src/autofill/background/tabs.background.spec.ts
  apps/browser/src/autofill/background/tabs.background.ts
  apps/browser/src/autofill/content/abstractions/autofill-init.ts
  apps/browser/src/autofill/content/autofill-init.spec.ts
  apps/browser/src/autofill/content/autofill-init.ts
  apps/browser/src/autofill/content/autofiller.ts
  apps/browser/src/autofill/content/bootstrap-autofill-overlay.ts
  apps/browser/src/autofill/content/bootstrap-autofill.ts
  apps/browser/src/autofill/content/message_handler.ts
  apps/browser/src/autofill/content/notification-bar.ts
  apps/browser/src/autofill/enums/autofill-port.enums.ts
  apps/browser/src/autofill/overlay/iframe-content/autofill-overlay-iframe.service.ts
  apps/browser/src/autofill/overlay/pages/button/autofill-overlay-button.ts
  apps/browser/src/autofill/overlay/pages/list/autofill-overlay-list.ts
  apps/browser/src/autofill/popup/settings/autofill.component.ts
  apps/browser/src/autofill/services/abstractions/autofill-overlay-content.service.ts
  apps/browser/src/autofill/services/abstractions/autofill.service.ts
  apps/browser/src/autofill/services/abstractions/collect-autofill-content.service.ts
  apps/browser/src/autofill/services/autofill-overlay-content.service.spec.ts
  apps/browser/src/autofill/services/autofill-overlay-content.service.ts
  apps/browser/src/autofill/services/autofill.service.spec.ts
  apps/browser/src/autofill/services/autofill.service.ts
  apps/browser/src/autofill/services/collect-autofill-content.service.ts
  apps/browser/src/autofill/utils/index.spec.ts
  apps/browser/src/autofill/utils/index.ts
  apps/browser/src/background/main.background.ts
  apps/browser/src/background/runtime.background.ts
  apps/browser/src/manifest.json
  apps/browser/test.setup.ts
Labels: browser

#6400 [PM-4090] Fix: Automatic biometric authentication no longer worked (Resolves: #6134)
  apps/desktop/src/auth/lock.component.spec.ts
  apps/desktop/src/auth/lock.component.ts
Labels: community-pr

#7209 [PM-5245] Autofill not triggering for fields that are not visible on load
  apps/browser/src/autofill/services/autofill-constants.ts
  apps/browser/src/autofill/services/collect-autofill-content.service.spec.ts
  apps/browser/src/autofill/services/collect-autofill-content.service.ts
Labels: browser

#6394 [PM-4077] safeincloud multiple url fix
  libs/common/src/vault/models/view/login.view.ts
  libs/importer/src/importers/safeincloud-xml-importer.ts
Labels: community-pr

#7213 [CL-133] add skip links to bit-layout
  .storybook/main.ts
  apps/browser/src/_locales/en/messages.json
  apps/desktop/src/locales/en/messages.json
  apps/web/src/locales/en/messages.json
  libs/components/src/layout/layout.component.html
  libs/components/src/layout/layout.component.ts
  libs/components/src/layout/layout.stories.ts
  libs/components/src/link/link.directive.ts
  package-lock.json
  package.json
Labels: accessibility

#7133 [PM-5177] fix CLI list items lock error
  apps/cli/src/commands/list.command.ts
Labels: community-pr

#7244 [CL-160] Rename BadgeType to BadgeVariant
  apps/web/src/app/admin-console/organizations/manage/groups.component.html
  apps/web/src/app/admin-console/organizations/members/components/member-dialog/member-dialog.component.html
  apps/web/src/app/admin-console/organizations/members/people.component.html
  apps/web/src/app/admin-console/organizations/policies/policies.component.html
  apps/web/src/app/admin-console/organizations/shared/components/access-selector/access-selector.component.html
  apps/web/src/app/auth/settings/emergency-access/emergency-access.component.html
  apps/web/src/app/auth/settings/webauthn-login-settings/webauthn-login-settings.component.html
  apps/web/src/app/billing/individual/user-subscription.component.html
  apps/web/src/app/billing/organizations/organization-subscription-cloud.component.html
  apps/web/src/app/reports/pages/exposed-passwords-report.component.html
  apps/web/src/app/reports/pages/reused-passwords-report.component.html
  apps/web/src/app/reports/pages/weak-passwords-report.component.html
  apps/web/src/app/reports/pages/weak-passwords-report.component.ts
  apps/web/src/app/reports/shared/report-card/report-card.component.html
  apps/web/src/app/vault/components/premium-badge.component.ts
  apps/web/src/app/vault/individual-vault/add-edit.component.html
  apps/web/src/app/vault/org-vault/collection-badge/collection-name-badge.component.html
  apps/web/src/app/vault/org-vault/group-badge/group-name-badge.component.html
  bitwarden_license/bit-web/src/app/admin-console/organizations/manage/domain-verification/domain-add-edit-dialog/domain-add-edit-dialog.component.html
  bitwarden_license/bit-web/src/app/admin-console/organizations/manage/domain-verification/domain-verification.component.html
  bitwarden_license/bit-web/src/app/admin-console/providers/manage/people.component.html
  bitwarden_license/bit-web/src/app/secrets-manager/shared/secrets-list.component.html
  libs/components/src/badge-list/badge-list.component.html
  libs/components/src/badge-list/badge-list.component.ts
  libs/components/src/badge-list/badge-list.stories.ts
  libs/components/src/badge/badge.directive.ts
  libs/components/src/badge/badge.stories.ts
  libs/components/src/badge/index.ts
  libs/components/src/multi-select/multi-select.component.html
  libs/components/src/toggle-group/toggle-group.stories.ts
Labels: needs-qa

#7216 [PM-4536] Import user redirected to wrong page
  apps/web/src/app/tools/import/import-web.component.ts
Labels: web

#6398 [PM-4032] Detect LastPass export page and suppress download prompt
  apps/browser/src/_locales/en/messages.json
  apps/browser/src/autofill/background/abstractions/notification.background.ts
  apps/browser/src/autofill/background/notification.background.ts
  apps/browser/src/autofill/content/notification-bar.ts
  apps/browser/src/autofill/jest/autofill-mocks.ts
  apps/browser/src/autofill/jest/testing-utils.ts
  apps/browser/src/autofill/notification/bar.html
  apps/browser/src/autofill/notification/bar.scss
  apps/browser/src/autofill/notification/bar.ts
  apps/browser/src/autofill/notification/models/add-request-fileless-import-queue-message.ts
  apps/browser/src/autofill/notification/models/notification-queue-message-type.ts
  apps/browser/src/autofill/shared/styles/variables.scss
  apps/browser/src/background/main.background.ts
  apps/browser/src/manifest.json
  apps/browser/src/tools/background/abstractions/fileless-importer.background.ts
  apps/browser/src/tools/background/fileless-importer.background.spec.ts
  apps/browser/src/tools/background/fileless-importer.background.ts
  apps/browser/src/tools/content/abstractions/lp-fileless-importer.ts
  apps/browser/src/tools/content/lp-fileless-importer.spec.ts
  apps/browser/src/tools/content/lp-fileless-importer.ts
  apps/browser/src/tools/enums/fileless-import.enums.ts
  apps/browser/webpack.config.js
Labels: browser

#7396 [PM-5479] Update year in copyright with 2023 to 2024
  apps/browser/src/safari/desktop/Info.plist
  apps/browser/src/safari/safari/Info.plist
  apps/cli/stores/chocolatey/bitwarden-cli.nuspec
  apps/desktop/electron-builder.json
  apps/desktop/stores/chocolatey/bitwarden.nuspec
  apps/web/src/404.html
Labels: needs-qa
