Repository bitwarden/clients, pull requests merged in 2023-02, with the labels that each got.

#4638 [PS-2414] Fix missing kdf parameters in key connector code
  libs/common/src/models/request/account/set-key-connector-key.request.ts
  libs/common/src/services/keyConnector.service.ts
Labels: community-pr

#4646 [SG-1034] [Defect] - Vault is empty upon login confirmation
  apps/browser/src/popup/accounts/login-with-device.component.ts
Labels: bug

#4656 [PS-2426] adding link to open positions
  README.md
Labels: community-pr

#4676 [SM-411] update icon sheet and table sort icons
  apps/browser/src/vault/popup/components/vault/vault-select.component.html
  apps/desktop/src/app/layout/account-switcher.component.html
  libs/angular/src/scss/bwicons/fonts/bwi-font.svg
  libs/angular/src/scss/bwicons/fonts/bwi-font.ttf
  libs/angular/src/scss/bwicons/fonts/bwi-font.woff
  libs/angular/src/scss/bwicons/fonts/bwi-font.woff2
  libs/angular/src/scss/bwicons/styles/style.scss
  libs/components/src/navigation/nav-group.component.html
  libs/components/src/stories/icons.stories.mdx
  libs/components/src/table/sortable.component.ts
Labels: needs-qa

#4655 [PS-2423] added important to strings for localization
  apps/web/src/auth/register-form/register-form.component.html
  apps/web/src/locales/en/messages.json
Labels: community-pr

#4480 [PS-2266][SG-1067] Desktop: restyle generator panel to be panel-like and avoid overflowing
  apps/desktop/src/scss/misc.scss
  apps/desktop/src/scss/variables.scss
Labels: community-pr

#4119 [PS-1918] Make autofill doc-scanner traverse into ShadowRoot
  apps/browser/src/autofill/content/autofill.js
Labels: community-pr

#4884 [SM-565] removing Write only option in service accounts
  apps/web/src/locales/en/messages.json
  bitwarden_license/bit-web/src/app/secrets-manager/shared/access-policies/access-selector.component.html
  bitwarden_license/bit-web/src/app/secrets-manager/shared/access-policies/access-selector.component.ts
Labels: needs-qa
