Repository bitwarden/clients, pull requests merged in 2023-07, with the labels that each got.

#5072 [PM-1605] Fix excessive background memory consumption by unloading argon2 module after use
  libs/common/src/platform/services/web-crypto-function.service.ts
  patches/argon2-browser+1.18.0.patch
Labels: community-pr

#5665 [PM-2538] Settings won't open after leaving screen
  apps/desktop/src/auth/login/login.component.html
  apps/desktop/src/auth/login/login.component.ts
Labels: needs-qa

#5698 [PM-2792] Fix for #5110 (The "Settings" > "Options" page's section headers cannot be translated)
  apps/browser/src/_locales/en/messages.json
  apps/browser/src/popup/settings/options.component.html
Labels: community-pr

#5635 [PM-482] Desktop Application is Minimized When There is a Master Password Re-prompt and Copying Vault Item Password
  apps/desktop/src/vault/app/vault/view.component.ts
  libs/angular/src/vault/components/view.component.ts
Labels: desktop

#5801 Adding missing await to properly set region on web client
  apps/web/src/app/core/init.service.ts
Labels: needs-qa

#5819 [PM-2846] Added missing await on environment URL reset
  libs/common/src/platform/services/environment.service.ts
Labels: needs-qa

#5821 Remove unused method
  libs/common/src/platform/abstractions/environment.service.ts
  libs/common/src/platform/services/environment.service.ts
Labels: needs-qa

#5700 [PM-2787] Fix Autofill Regex Check to Correctly Handle Both two-digit and four-digit years
  apps/browser/src/autofill/services/autofill.service.ts
Labels: browser

#5825 [AC-1518] Remove extra v2 from generated SCIM url
  libs/common/src/platform/services/environment.service.ts
Labels: bug

#5530 [PM-2433] Fix typo `overlayPostition` > `overlayPosition`
  apps/browser/src/vault/popup/components/vault/vault-select.component.ts
  apps/desktop/src/app/layout/account-switcher.component.html
  apps/desktop/src/app/layout/account-switcher.component.ts
  libs/angular/src/auth/components/environment-selector.component.html
  libs/angular/src/auth/components/environment-selector.component.ts
Labels: community-pr

#4560 [PS-2355] Fix safari freezing when clicking premium option
  apps/browser/src/popup/settings/premium.component.ts
Labels: community-pr

#5892 [PM-3168] Fix trial initiation "Invite Users" link
  apps/web/src/app/auth/trial-initiation/trial-initiation.component.spec.ts
  apps/web/src/app/auth/trial-initiation/trial-initiation.component.ts
Labels: needs-qa

#5851 [AC-1542] Update manage password reset label
  apps/web/src/app/admin-console/organizations/members/components/member-dialog/member-dialog.component.html
  apps/web/src/locales/en/messages.json
Labels: bug

#5791 647 - rearrange drop downs
  bitwarden_license/bit-web/src/app/secrets-manager/shared/projects-list.component.html
Labels: needs-qa

#5796 [PM-2804] Migrate Send List to Component Library
  apps/web/src/app/app.module.ts
  apps/web/src/app/shared/loose-components.module.ts
  apps/web/src/app/tools/send/icons/no-send.icon.ts
  apps/web/src/app/tools/send/send.component.html
  apps/web/src/app/tools/send/send.component.ts
  apps/web/src/locales/en/messages.json
  libs/angular/src/tools/send/send.component.ts
Labels: web
