Repository bitwarden/clients, pull requests merged in 2024-04, with the labels that each got.

#8542 [PM-5740] LocalBackedSessionStorage Updates
  apps/browser/src/background/main.background.ts
  apps/browser/src/platform/background/service-factories/storage-service.factory.ts
  apps/browser/src/platform/services/local-backed-session-storage.service.spec.ts
  apps/browser/src/platform/services/local-backed-session-storage.service.ts
Labels: needs-qa

#8375 [SM-889] FIX - bulk activate SM members
  apps/web/src/app/admin-console/organizations/core/views/organization-user.view.ts
  apps/web/src/app/admin-console/organizations/members/people.component.ts
Labels: bug

#5645 [PM-2714] Use `nullValidator` to accept 'No folder' while moving item
  apps/web/src/app/vault/individual-vault/bulk-action-dialogs/bulk-move-dialog/bulk-move-dialog.component.ts
Labels: community-pr

#8622 [AC-2404] Fix subscription page for free org with new statuses enabled
  apps/web/src/app/billing/organizations/subscription-status.component.html
  apps/web/src/app/billing/organizations/subscription-status.component.ts
Labels: needs-qa

#8627 [PM-7292] Fix viewing/editing unassigned ciphers for admins
  apps/web/src/app/vault/org-vault/vault.component.ts
  libs/angular/src/vault/components/add-edit.component.ts
  libs/common/src/admin-console/models/domain/organization.ts
Labels: needs-qa

#8564 Tell `POLICIES` to clear its own state on logout
  apps/browser/src/background/main.background.ts
  apps/cli/src/bw.ts
  apps/desktop/src/app/app.component.ts
  apps/web/src/app/app.component.ts
  libs/common/src/admin-console/abstractions/policy/policy.service.abstraction.ts
  libs/common/src/admin-console/services/policy/policy.service.spec.ts
  libs/common/src/admin-console/services/policy/policy.service.ts
Labels: needs-qa

#8563 Tell `PROVIDERS` to clear its own state on logout
  apps/browser/src/background/main.background.ts
  apps/cli/src/bw.ts
  apps/desktop/src/app/app.component.ts
  libs/common/src/admin-console/services/provider.service.ts
Labels: needs-qa

#8618 [PM-7216] Bugfix - Fix notification bar content script using old server config state storage
  apps/browser/src/autofill/background/abstractions/notification.background.ts
  apps/browser/src/autofill/background/notification.background.spec.ts
  apps/browser/src/autofill/background/notification.background.ts
  apps/browser/src/autofill/content/notification-bar.ts
  apps/browser/src/background/main.background.ts
Labels: bug

#8628 Increase max-old-space for bit:dev:watch
  apps/web/package.json
Labels: needs-qa

#8540 [AC-2350] - FIX - Separate domain verification steps
  bitwarden_license/bit-web/src/app/admin-console/organizations/manage/domain-verification/domain-add-edit-dialog/domain-add-edit-dialog.component.html
  bitwarden_license/bit-web/src/app/admin-console/organizations/manage/domain-verification/domain-add-edit-dialog/domain-add-edit-dialog.component.ts
  libs/common/src/admin-console/services/organization-domain/requests/organization-domain.request.ts
Labels: bug

#8667 Use `UserKeyDefinition` for user-scoped data
  libs/common/src/platform/services/key-state/user-key.state.ts
Labels: needs-qa

#8672 [PM-7349] add snap description
  apps/desktop/electron-builder.json
Labels: needs-qa

#8602 Prefer Passed In UserId
  apps/browser/src/background/main.background.ts
Labels: needs-qa

#8691 [PM-6696] Collections not loading when adding item
  apps/desktop/src/vault/app/vault/add-edit.component.ts
  libs/angular/src/vault/components/add-edit.component.ts
Labels: needs-qa

#8674 [AC-2319] remove the owned by business checkbox business name
  apps/web/src/app/admin-console/organizations/create/organization-information.component.html
  apps/web/src/app/admin-console/organizations/create/organization-information.component.ts
  apps/web/src/app/admin-console/organizations/settings/account.component.html
  apps/web/src/app/admin-console/organizations/settings/account.component.ts
  apps/web/src/app/billing/organizations/organization-plans.component.ts
Labels: needs-qa

#8712 Update Organization and Policy Services to allow the passing of a user id and to prevent hangs waiting on an active user
  libs/common/src/admin-console/abstractions/organization/organization.service.abstraction.ts
  libs/common/src/admin-console/services/organization/organization.service.ts
  libs/common/src/admin-console/services/policy/policy.service.spec.ts
  libs/common/src/admin-console/services/policy/policy.service.ts
Labels: needs-qa

#8648 [AC-2431] New collection dialog bug
  apps/web/src/app/admin-console/organizations/shared/components/access-selector/access-selector.models.ts
  apps/web/src/app/vault/components/collection-dialog/collection-dialog.component.ts
Labels: needs-qa

#8757 Auth/PM-7467- Fix Refresh token issues
  libs/auth/src/common/login-strategies/login.strategy.ts
  libs/common/src/auth/services/token.service.spec.ts
  libs/common/src/auth/services/token.service.ts
  libs/common/src/auth/services/token.state.spec.ts
  libs/common/src/auth/services/token.state.ts
  libs/common/src/state-migrations/migrate.ts
  libs/common/src/state-migrations/migrations/58-remove-refresh-token-migrated-state-provider-flag.spec.ts
  libs/common/src/state-migrations/migrations/58-remove-refresh-token-migrated-state-provider-flag.ts
Labels: needs-qa

#8773 [PM-7138] [PM-7526]Guard Background Only and MV2 Only Actions
  apps/browser/src/background/main.background.ts
  apps/browser/src/popup/services/services.module.ts
Labels: needs-qa

#8784 Handle null values coming from state
  libs/common/src/vault/services/cipher.service.ts
Labels: needs-qa

#8780 [PM-7533] Add missing value assignment
  libs/common/src/vault/services/cipher.service.ts
Labels: needs-qa

#8778 [AC-2470] Delete unused SettingsComponents
  apps/web/src/app/admin-console/organizations/settings/settings.component.html
  apps/web/src/app/admin-console/organizations/settings/settings.component.ts
  bitwarden_license/bit-web/src/app/admin-console/providers/settings/settings.component.ts
Labels: needs-qa

#8815 Fix migrated state service data
  libs/common/src/state-migrations/migrations/57-move-cipher-service-to-state-provider.spec.ts
  libs/common/src/state-migrations/migrations/57-move-cipher-service-to-state-provider.ts
Labels: needs-qa

#8590 Auth/PM-7235 - Refactor AuthService.getAuthStatus, deprecate everBeenUnlocked, and handle initialization of auto user key on client init
  apps/browser/src/background/main.background.ts
  apps/browser/src/popup/services/init.service.ts
  apps/desktop/src/app/services/init.service.ts
  apps/web/src/app/core/init.service.ts
  libs/angular/src/auth/components/lock.component.ts
  libs/angular/src/services/jslib-services.module.ts
  libs/common/src/auth/services/auth.service.ts
  libs/common/src/platform/abstractions/state.service.ts
  libs/common/src/platform/models/domain/account.ts
  libs/common/src/platform/services/crypto.service.spec.ts
  libs/common/src/platform/services/crypto.service.ts
  libs/common/src/platform/services/state.service.ts
  libs/common/src/platform/services/user-key-init.service.spec.ts
  libs/common/src/platform/services/user-key-init.service.ts
  libs/common/src/services/vault-timeout/vault-timeout-settings.service.ts
  libs/common/src/services/vault-timeout/vault-timeout.service.spec.ts
  libs/common/src/services/vault-timeout/vault-timeout.service.ts
Labels: needs-qa

#8709 [PM-7489] Introduce `MessageSender` & `MessageListener`
  .eslintrc.json
  apps/browser/src/background/main.background.ts
  apps/browser/src/background/nativeMessaging.background.ts
  apps/browser/src/background/runtime.background.ts
  apps/browser/src/platform/background/service-factories/message-sender.factory.ts
  apps/browser/src/platform/background/service-factories/messaging-service.factory.ts
  apps/browser/src/platform/messaging/chrome-message.sender.ts
  apps/browser/src/platform/services/browser-messaging-private-mode-background.service.ts
  apps/browser/src/platform/services/browser-messaging-private-mode-popup.service.ts
  apps/browser/src/platform/services/browser-messaging.service.ts
  apps/browser/src/platform/utils/from-chrome-runtime-messaging.ts
  apps/browser/src/popup/app.component.ts
  apps/browser/src/popup/services/services.module.ts
  apps/cli/src/bw.ts
  apps/desktop/src/app/services/services.module.ts
  apps/desktop/src/main.ts
  apps/desktop/src/main/power-monitor.main.ts
  apps/desktop/src/platform/preload.ts
  apps/desktop/src/platform/services/electron-renderer-message.sender.ts
  apps/desktop/src/platform/services/electron-renderer-messaging.service.ts
  apps/desktop/src/platform/utils/from-ipc-messaging.ts
  apps/desktop/src/services/electron-main-messaging.service.ts
  apps/web/src/app/billing/accounts/trial-initiation/trial-billing-step.component.ts
  apps/web/src/app/billing/organizations/organization-plans.component.ts
  apps/web/src/app/core/broadcaster-messaging.service.ts
  apps/web/src/app/core/core.module.ts
  apps/web/src/app/vault/components/premium-badge.stories.ts
  libs/angular/src/platform/services/broadcaster.service.ts
  libs/angular/src/services/injection-tokens.ts
  libs/angular/src/services/jslib-services.module.ts
  libs/common/src/platform/abstractions/messaging.service.ts
  libs/common/src/platform/messaging/helpers.spec.ts
  libs/common/src/platform/messaging/helpers.ts
  libs/common/src/platform/messaging/index.ts
  libs/common/src/platform/messaging/internal.ts
  libs/common/src/platform/messaging/message.listener.spec.ts
  libs/common/src/platform/messaging/message.listener.ts
  libs/common/src/platform/messaging/message.sender.ts
  libs/common/src/platform/messaging/subject-message.sender.spec.ts
  libs/common/src/platform/messaging/subject-message.sender.ts
  libs/common/src/platform/messaging/types.ts
  libs/common/src/platform/services/broadcaster.service.ts
  libs/common/src/platform/services/default-broadcaster.service.ts
  libs/common/src/platform/services/noop-messaging.service.ts
Labels: needs-qa

#8833 [PM-7610] [MV3] Guard overlay visibility and autofill on page load settings from awaiting indefinitely when there is no active account
  apps/browser/src/autofill/background/service_factories/autofill-service.factory.ts
  apps/browser/src/autofill/services/autofill.service.spec.ts
  apps/browser/src/autofill/services/autofill.service.ts
  apps/browser/src/background/main.background.ts
  apps/browser/src/popup/services/services.module.ts
Labels: needs-qa

#8829 [PM-7603] Fix individual vault export not appearing on Event Logs
  libs/common/src/services/event/event-collection.service.ts
Labels: bug

#8860 Revert "Auth/PM-6689 - Migrate Security Stamp to Token Service and State Provider"
  apps/browser/src/background/main.background.ts
  apps/cli/src/bw.ts
  libs/angular/src/services/jslib-services.module.ts
  libs/auth/src/common/login-strategies/login.strategy.spec.ts
  libs/auth/src/common/login-strategies/login.strategy.ts
  libs/common/src/auth/abstractions/token.service.ts
  libs/common/src/auth/services/token.service.spec.ts
  libs/common/src/auth/services/token.service.ts
  libs/common/src/auth/services/token.state.spec.ts
  libs/common/src/auth/services/token.state.ts
  libs/common/src/platform/abstractions/state.service.ts
  libs/common/src/platform/models/domain/account-tokens.spec.ts
  libs/common/src/platform/models/domain/account.spec.ts
  libs/common/src/platform/models/domain/account.ts
  libs/common/src/platform/services/state.service.ts
  libs/common/src/vault/services/sync/sync.service.ts
Labels: needs-qa

#8843 [PM-7617] Stop CryptoService from using `getBgService`
  apps/browser/src/popup/services/services.module.ts
Labels: needs-qa

#8867 Revert "[PM-7617] Stop CryptoService from using `getBgService`"
  apps/browser/src/popup/services/services.module.ts
Labels: needs-qa

#8866 Remove `alarms` Permission
  apps/browser/src/manifest.v3.json
Labels: needs-qa

#8782 [AC-2406] migrating activate autofill component
  bitwarden_license/bit-web/src/app/admin-console/policies/activate-autofill.component.html
Labels: needs-qa

#8760 [AC-2396] migrate two factor authentication component
  apps/web/src/app/admin-console/organizations/policies/two-factor-authentication.component.html
Labels: needs-qa

#8898 [PM-7566] Set keypair for admin auth requests before waiting for notification
  libs/angular/src/auth/components/login-via-auth-request.component.ts
Labels: needs-qa

#8889 Revert "Revert "Auth/PM-6689 - Migrate Security Stamp to Token Service and State Provider""
  apps/browser/src/background/main.background.ts
  apps/cli/src/bw.ts
  libs/angular/src/services/jslib-services.module.ts
  libs/auth/src/common/login-strategies/login.strategy.spec.ts
  libs/auth/src/common/login-strategies/login.strategy.ts
  libs/common/src/auth/abstractions/token.service.ts
  libs/common/src/auth/services/token.service.spec.ts
  libs/common/src/auth/services/token.service.ts
  libs/common/src/auth/services/token.state.spec.ts
  libs/common/src/auth/services/token.state.ts
  libs/common/src/platform/abstractions/state.service.ts
  libs/common/src/platform/models/domain/account-tokens.spec.ts
  libs/common/src/platform/models/domain/account.spec.ts
  libs/common/src/platform/models/domain/account.ts
  libs/common/src/platform/services/state.service.ts
  libs/common/src/vault/services/sync/sync.service.ts
Labels: needs-qa

#8819 Auth/PM-6787 - Rename DeviceTrustCryptoService to DeviceTrustService
  apps/browser/src/auth/background/service-factories/device-trust-service.factory.ts
  apps/browser/src/auth/background/service-factories/login-strategy-service.factory.ts
  apps/browser/src/auth/popup/lock.component.ts
  apps/browser/src/auth/popup/login-via-auth-request.component.ts
  apps/browser/src/background/main.background.ts
  apps/browser/src/popup/services/services.module.ts
  apps/cli/src/bw.ts
  apps/desktop/src/auth/lock.component.spec.ts
  apps/desktop/src/auth/lock.component.ts
  apps/desktop/src/auth/login/login-via-auth-request.component.ts
  apps/web/src/app/auth/key-rotation/user-key-rotation.service.spec.ts
  apps/web/src/app/auth/key-rotation/user-key-rotation.service.ts
  libs/angular/src/auth/components/base-login-decryption-options.component.ts
  libs/angular/src/auth/components/lock.component.ts
  libs/angular/src/auth/components/login-via-auth-request.component.ts
  libs/angular/src/auth/guards/lock.guard.ts
  libs/angular/src/auth/guards/redirect.guard.ts
  libs/angular/src/auth/guards/tde-decryption-required.guard.ts
  libs/angular/src/services/jslib-services.module.ts
  libs/auth/src/common/login-strategies/auth-request-login.strategy.spec.ts
  libs/auth/src/common/login-strategies/auth-request-login.strategy.ts
  libs/auth/src/common/login-strategies/sso-login.strategy.spec.ts
  libs/auth/src/common/login-strategies/sso-login.strategy.ts
  libs/auth/src/common/services/login-strategies/login-strategy.service.spec.ts
  libs/auth/src/common/services/login-strategies/login-strategy.service.ts
  libs/common/src/auth/abstractions/device-trust.service.abstraction.ts
  libs/common/src/auth/services/device-trust.service.implementation.ts
  libs/common/src/auth/services/device-trust.service.spec.ts
  libs/common/src/state-migrations/migrate.ts
  libs/common/src/state-migrations/migrations/53-migrate-device-trust-svc-to-state-providers.spec.ts
  libs/common/src/state-migrations/migrations/53-migrate-device-trust-svc-to-state-providers.ts
  libs/common/src/state-migrations/migrations/58-remove-refresh-token-migrated-state-provider-flag.ts
Labels: needs-qa

#8905 [PM-7703] Set auto key on command in cli
  apps/cli/src/bw.ts
Labels: needs-qa

#8902 [PM-7687] Fix `reloadPopup` Recursion
  apps/browser/src/background/runtime.background.ts
  apps/browser/src/platform/services/local-backed-session-storage.service.ts
Labels: needs-qa

#8839 [AC-2485] Add redirects to clients components based on FF and provider status
  bitwarden_license/bit-web/src/app/admin-console/providers/clients/base-clients.component.ts
  bitwarden_license/bit-web/src/app/admin-console/providers/clients/clients.component.ts
  bitwarden_license/bit-web/src/app/admin-console/providers/providers-layout.component.html
  bitwarden_license/bit-web/src/app/admin-console/providers/providers-layout.component.ts
  bitwarden_license/bit-web/src/app/billing/providers/clients/manage-client-organization-subscription.component.html
  bitwarden_license/bit-web/src/app/billing/providers/clients/manage-client-organizations.component.ts
  libs/common/src/admin-console/enums/index.ts
  libs/common/src/admin-console/enums/provider-status-type.enum.ts
  libs/common/src/admin-console/models/data/provider.data.ts
  libs/common/src/admin-console/models/domain/provider.ts
  libs/common/src/admin-console/models/response/profile-provider.response.ts
  libs/common/src/admin-console/services/provider.service.spec.ts
Labels: needs-qa

#8820 [PM-7564] Move 2fa and login strategy service to popup and add state providers to 2fa service
  apps/browser/src/auth/background/service-factories/two-factor-service.factory.ts
  apps/browser/src/auth/popup/two-factor-options.component.ts
  apps/browser/src/background/main.background.ts
  apps/browser/src/popup/services/init.service.ts
  apps/browser/src/popup/services/services.module.ts
  apps/cli/src/auth/commands/login.command.ts
  apps/cli/src/bw.ts
  libs/angular/src/auth/components/sso.component.spec.ts
  libs/angular/src/auth/components/two-factor-options.component.ts
  libs/angular/src/auth/components/two-factor.component.ts
  libs/angular/src/services/jslib-services.module.ts
  libs/auth/src/common/login-strategies/auth-request-login.strategy.spec.ts
  libs/auth/src/common/login-strategies/login.strategy.spec.ts
  libs/auth/src/common/login-strategies/login.strategy.ts
  libs/auth/src/common/login-strategies/password-login.strategy.spec.ts
  libs/auth/src/common/login-strategies/sso-login.strategy.spec.ts
  libs/auth/src/common/login-strategies/user-api-login.strategy.spec.ts
  libs/auth/src/common/login-strategies/webauthn-login.strategy.spec.ts
  libs/common/src/auth/abstractions/two-factor.service.ts
  libs/common/src/auth/models/domain/auth-result.ts
  libs/common/src/auth/models/response/identity-two-factor.response.ts
  libs/common/src/auth/services/two-factor.service.ts
  libs/common/src/platform/state/deserialization-helpers.spec.ts
  libs/common/src/platform/state/deserialization-helpers.ts
  libs/common/src/platform/state/key-definition.ts
  libs/common/src/platform/state/state-definitions.ts
  libs/common/src/platform/state/user-key-definition.ts
Labels: needs-qa

#8910 [AC-2359] Ownership does not default to an organization when Remove Individual Vault policy is active
  libs/angular/src/vault/components/add-edit.component.ts
Labels: needs-qa

#8922 [PM-7702] Remove extra content script being injected
  apps/browser/src/autofill/services/autofill.service.ts
Labels: needs-qa

#8580 PM-4945 Update Two Factor verify dialog
  apps/web/src/app/admin-console/organizations/settings/two-factor-setup.component.ts
  apps/web/src/app/auth/settings/two-factor-authenticator.component.html
  apps/web/src/app/auth/settings/two-factor-duo.component.html
  apps/web/src/app/auth/settings/two-factor-email.component.html
  apps/web/src/app/auth/settings/two-factor-recovery.component.html
  apps/web/src/app/auth/settings/two-factor-setup.component.ts
  apps/web/src/app/auth/settings/two-factor-verify.component.html
  apps/web/src/app/auth/settings/two-factor-verify.component.ts
  apps/web/src/app/auth/settings/two-factor-webauthn.component.html
  apps/web/src/app/auth/settings/two-factor-yubikey.component.html
  apps/web/src/app/shared/loose-components.module.ts
Labels: needs-qa

#8932 Fix ConfigService Merge Conflict
  bitwarden_license/bit-web/src/app/billing/providers/clients/manage-client-organizations.component.ts
Labels: needs-qa

#8927 PM-7745 - SSO Login Strategy - Attempt to fix TDE decryption "no private key" error
  libs/auth/src/common/login-strategies/sso-login.strategy.ts
Labels: needs-qa

#8931 Display `version_name` in AboutComponent
  apps/browser/src/platform/browser/browser-api.ts
  apps/browser/src/platform/services/platform-utils/browser-platform-utils.service.ts
  apps/browser/src/popup/settings/about.component.html
  apps/browser/src/popup/settings/about.component.ts
Labels: needs-qa

#8934 Bandaid Folders Not Emitting
  apps/browser/src/platform/state/foreground-derived-state.ts
Labels: needs-qa

#8940 [PM-7758] Check that `self` is undefined instead of `window`
  libs/common/src/platform/misc/utils.ts
Labels: needs-qa

#8903 [PM-7663] Update Build Pipeline for Beta Labelling
  .github/workflows/build-browser.yml
  apps/browser/gulpfile.js
  apps/browser/package.json
Labels: needs-qa

#8946 [PM-7750] pass userId when logging out and add error handling if one isn't found in background
  apps/browser/src/background/main.background.ts
  apps/browser/src/popup/settings/settings.component.ts
Labels: needs-qa

#8949 [PM-7750] add error handling to runtime.background messaging
  apps/browser/src/background/runtime.background.ts
Labels: needs-qa

#8636 [PM-7314] chore: remove repetitive words
  apps/browser/src/auth/popup/account-switching/services/account-switcher.service.ts
  apps/browser/src/platform/popup/browser-popup-utils.spec.ts
  apps/desktop/src/platform/services/desktop-settings.service.ts
  libs/common/spec/observable-tracker.ts
  libs/common/src/auth/services/token.service.ts
  libs/common/src/platform/abstractions/crypto.service.ts
  libs/common/src/state-migrations/migration-helper.ts
  libs/components/src/dialog/dialogs.mdx
  libs/components/src/form/forms.mdx
Labels: community-pr

#8950 Run `npm run prettier` & Fix `main` Linter
  libs/components/src/form/forms.mdx
Labels: needs-qa

#8945 [PM-7766] Add `clientType` to MigrationHelper
  apps/browser/src/background/main.background.ts
  apps/browser/src/platform/background/service-factories/migration-runner.factory.ts
  apps/browser/src/popup/services/services.module.ts
  apps/cli/src/bw.ts
  apps/desktop/src/app/services/services.module.ts
  apps/desktop/src/main.ts
  apps/web/src/app/core/core.module.ts
  apps/web/src/app/platform/web-migration-runner.ts
  libs/angular/src/services/injection-tokens.ts
  libs/angular/src/services/jslib-services.module.ts
  libs/common/src/platform/services/migration-builder.service.spec.ts
  libs/common/src/platform/services/migration-runner.spec.ts
  libs/common/src/platform/services/migration-runner.ts
  libs/common/src/state-migrations/migration-builder.spec.ts
  libs/common/src/state-migrations/migration-helper.spec.ts
  libs/common/src/state-migrations/migration-helper.ts
  libs/common/src/state-migrations/migrator.spec.ts
Labels: needs-qa

#8968 [AC-2523] Fix broken members dialog for Manage Users custom permission
  apps/web/src/app/admin-console/organizations/members/components/member-dialog/member-dialog.component.ts
  apps/web/src/app/vault/core/views/collection-admin.view.ts
Labels: needs-qa

#8944 Fix Beta Version
  apps/browser/gulpfile.js
Labels: needs-qa

#8979 Auth/PM-7811 - Refactor User Auto Unlock Key Hydration Process To Remove Race Conditions
  apps/browser/src/background/main.background.ts
  apps/cli/src/bw.ts
  apps/desktop/src/app/services/init.service.ts
  apps/web/src/app/core/init.service.ts
  libs/angular/src/services/jslib-services.module.ts
  libs/common/src/platform/services/user-auto-unlock-key.service.spec.ts
  libs/common/src/platform/services/user-auto-unlock-key.service.ts
  libs/common/src/platform/services/user-key-init.service.spec.ts
  libs/common/src/platform/services/user-key-init.service.ts
Labels: needs-qa

#8768 [AC-2403] Hide grace period note when in self-serve trial
  apps/web/src/app/billing/organizations/organization-subscription-selfhost.component.html
  libs/common/src/billing/models/view/self-hosted-organization-subscription.view.ts
Labels: needs-qa
