Repository bitwarden/clients, pull requests merged in 2024-05, with the labels that each got.

#8980 [PM-6533] Sort organizations by name within product switcher
  apps/web/src/app/layouts/product-switcher/product-switcher-content.component.ts
Labels: needs-qa

#8996 Add beta extension to allowed native messaging hosts
  apps/desktop/src/main/native-messaging.main.ts
Labels: needs-qa

#9000 [AC-2547] Defect - Deleting Provider from Provider Portal should take user to Password Manager Vault page
  bitwarden_license/bit-web/src/app/admin-console/providers/settings/account.component.ts
Labels: needs-qa

#8973 [AC-2140] Swap Admin Console icon
  apps/web/src/app/layouts/product-switcher/product-switcher-content.component.html
  apps/web/src/app/layouts/product-switcher/product-switcher-content.component.ts
Labels: needs-qa

#8863 [PM-7627] [MV3] Do not run fido2 content scripts on browser settings or extension pages
  apps/browser/src/autofill/services/autofill.service.spec.ts
  apps/browser/src/autofill/services/autofill.service.ts
  apps/browser/src/background/main.background.ts
  apps/browser/src/manifest.v3.json
  apps/browser/src/platform/background/service-factories/browser-script-injector-service.factory.ts
  apps/browser/src/platform/services/browser-script-injector.service.spec.ts
  apps/browser/src/platform/services/browser-script-injector.service.ts
  apps/browser/src/popup/services/services.module.ts
  apps/browser/src/tools/background/fileless-importer.background.spec.ts
  apps/browser/src/vault/fido2/background/fido2.background.ts
  apps/browser/src/vault/fido2/content/content-script.spec.ts
  apps/browser/src/vault/fido2/content/content-script.ts
  apps/browser/src/vault/fido2/content/page-script.ts
  apps/browser/src/vault/fido2/content/page-script.webauthn-supported.spec.ts
  apps/browser/src/vault/fido2/content/page-script.webauthn-unsupported.spec.ts
Labels: needs-qa

#8700 [PM-7413] fix(8560): refreshing reports pages displays empty pages
  apps/web/src/app/admin-console/organizations/tools/exposed-passwords-report.component.ts
  apps/web/src/app/admin-console/organizations/tools/inactive-two-factor-report.component.ts
  apps/web/src/app/admin-console/organizations/tools/reused-passwords-report.component.ts
  apps/web/src/app/admin-console/organizations/tools/unsecured-websites-report.component.ts
  apps/web/src/app/admin-console/organizations/tools/weak-passwords-report.component.ts
  apps/web/src/app/tools/reports/pages/cipher-report.component.ts
  apps/web/src/app/tools/reports/pages/exposed-passwords-report.component.spec.ts
  apps/web/src/app/tools/reports/pages/exposed-passwords-report.component.ts
  apps/web/src/app/tools/reports/pages/inactive-two-factor-report.component.spec.ts
  apps/web/src/app/tools/reports/pages/inactive-two-factor-report.component.ts
  apps/web/src/app/tools/reports/pages/reused-passwords-report.component.spec.ts
  apps/web/src/app/tools/reports/pages/reused-passwords-report.component.ts
  apps/web/src/app/tools/reports/pages/unsecured-websites-report.component.spec.ts
  apps/web/src/app/tools/reports/pages/unsecured-websites-report.component.ts
  apps/web/src/app/tools/reports/pages/weak-passwords-report.component.spec.ts
  apps/web/src/app/tools/reports/pages/weak-passwords-report.component.ts
Labels: community-pr

#9034 Fix init account validation
  libs/common/src/platform/services/crypto.service.ts
Labels: needs-qa

#8941 [AC-1970] Add billing navigation group to provider layout
  bitwarden_license/bit-web/src/app/admin-console/providers/clients/clients.component.ts
  bitwarden_license/bit-web/src/app/admin-console/providers/providers-layout.component.html
  bitwarden_license/bit-web/src/app/admin-console/providers/providers-layout.component.ts
  bitwarden_license/bit-web/src/app/admin-console/providers/providers-routing.module.ts
  bitwarden_license/bit-web/src/app/admin-console/providers/providers.module.ts
  bitwarden_license/bit-web/src/app/billing/providers/clients/manage-client-organizations.component.ts
  bitwarden_license/bit-web/src/app/billing/providers/guards/has-consolidated-billing.guard.ts
  bitwarden_license/bit-web/src/app/billing/providers/index.ts
  bitwarden_license/bit-web/src/app/billing/providers/provider-subscription.component.html
  bitwarden_license/bit-web/src/app/billing/providers/provider-subscription.component.ts
  libs/common/src/admin-console/abstractions/provider.service.ts
  libs/common/src/admin-console/services/provider.service.spec.ts
  libs/common/src/admin-console/services/provider.service.ts
  libs/common/src/billing/abstractions/provider-billing.service.abstraction.ts
Labels: needs-qa

#9023 Use account service for account enumeration.
  apps/browser/src/platform/services/default-browser-state.service.ts
  apps/desktop/src/app/app.component.ts
  apps/desktop/src/app/services/services.module.ts
  apps/desktop/src/services/encrypted-message-handler.service.ts
  apps/desktop/src/services/native-messaging.service.ts
  libs/common/src/platform/abstractions/state.service.ts
  libs/common/src/platform/services/state.service.ts
Labels: needs-qa

#9018 [PM-7838] [PM-7864] Ensure AuthStatus Changes Before Exiting
  apps/browser/src/background/main.background.ts
  apps/desktop/src/app/app.component.ts
  apps/desktop/src/app/layout/account-switcher.component.ts
  apps/web/src/app/app.component.ts
  libs/common/src/services/vault-timeout/vault-timeout.service.spec.ts
  libs/common/src/services/vault-timeout/vault-timeout.service.ts
Labels: needs-qa

#9047 [AC-2557] Defect - Modal text updates
  apps/web/src/locales/en/messages.json
  bitwarden_license/bit-web/src/app/admin-console/providers/settings/account.component.ts
Labels: needs-qa

#9061 [AC-2558] Provider Admin still sees manage billing options - not the provided image
  apps/web/src/app/billing/organizations/organization-subscription-cloud.component.html
Labels: needs-qa

#8713 [PM-7425] fix(8702): refreshing organization report page does not display the r…
  apps/web/src/app/admin-console/organizations/reporting/reports-home.component.ts
Labels: community-pr

#8265 [AC-1707] Restrict provider access to items
  apps/web/src/app/vault/individual-vault/bulk-action-dialogs/bulk-delete-dialog/bulk-delete-dialog.component.ts
  apps/web/src/app/vault/individual-vault/collections.component.html
  apps/web/src/app/vault/individual-vault/collections.component.ts
  apps/web/src/app/vault/org-vault/add-edit.component.ts
  apps/web/src/app/vault/org-vault/attachments.component.ts
  apps/web/src/app/vault/org-vault/bulk-collection-assignment-dialog/bulk-collection-assignment-dialog.component.ts
  apps/web/src/app/vault/org-vault/collection-access-restricted.component.ts
  apps/web/src/app/vault/org-vault/collections.component.ts
  apps/web/src/app/vault/org-vault/vault-header/vault-header.component.html
  apps/web/src/app/vault/org-vault/vault-header/vault-header.component.ts
  apps/web/src/app/vault/org-vault/vault.component.html
  apps/web/src/app/vault/org-vault/vault.component.ts
  apps/web/src/app/vault/org-vault/vault.module.ts
  libs/angular/src/admin-console/components/collections.component.ts
  libs/angular/src/vault/components/add-edit.component.ts
  libs/common/src/admin-console/models/domain/organization.ts
  libs/common/src/enums/feature-flag.enum.ts
  libs/common/src/vault/models/view/collection.view.ts
Labels: needs-qa

#8293 [PM-6749] Check MasterPassword in web app during change
  apps/web/src/app/auth/settings/change-password.component.ts
Labels: community-pr

#9082 [PM-7747] add timeout to safari sendMessageWithResponse
  apps/browser/src/platform/services/platform-utils/browser-platform-utils.service.ts
Labels: needs-qa

#9086 Pm 7843 two factor verification is empty on organization duo 2 fa
  apps/web/src/app/admin-console/organizations/settings/two-factor-setup.component.ts
Labels: needs-qa

#8387 [PM 5007] migrate premium component
  apps/web/src/app/billing/individual/premium.component.html
  apps/web/src/app/billing/individual/premium.component.ts
Labels: needs-qa

#8239 [PM 5012] migrate adjust subscription component
  apps/web/src/app/billing/organizations/adjust-subscription.component.html
  apps/web/src/app/billing/organizations/adjust-subscription.component.ts
Labels: needs-qa

#8448 PM-5017 Migrate Organization Plans component
  apps/web/src/app/billing/organizations/organization-plans.component.html
  apps/web/src/app/billing/organizations/organization-plans.component.ts
Labels: needs-qa

#9099 Use encrypt service in node env secure storage
  apps/cli/src/bw.ts
  apps/cli/src/platform/services/node-env-secure-storage.service.ts
  libs/common/src/platform/abstractions/encrypt.service.ts
Labels: needs-qa

#9131 [PM-7985] Add & Use InlineDerivedStateProvider
  apps/browser/src/background/main.background.ts
  apps/browser/src/platform/background/service-factories/derived-state-provider.factory.ts
  apps/browser/src/platform/state/background-derived-state.provider.ts
  apps/browser/src/platform/state/background-derived-state.ts
  apps/browser/src/platform/state/derived-state-interactions.spec.ts
  apps/browser/src/platform/state/foreground-derived-state.provider.ts
  apps/browser/src/platform/state/foreground-derived-state.spec.ts
  apps/browser/src/platform/state/foreground-derived-state.ts
  apps/browser/src/popup/services/services.module.ts
  libs/common/src/platform/state/implementations/inline-derived-state.spec.ts
  libs/common/src/platform/state/implementations/inline-derived-state.ts
Labels: needs-qa

#8604 Auth/PM-5501 - VaultTimeoutSettingsService State Provider Migration
  apps/browser/src/auth/background/service-factories/login-strategy-service.factory.ts
  apps/browser/src/auth/popup/settings/account-security.component.ts
  apps/browser/src/autofill/types/index.ts
  apps/browser/src/background/idle.background.ts
  apps/browser/src/background/main.background.ts
  apps/browser/src/background/service-factories/vault-timeout-settings-service.factory.ts
  apps/browser/src/models/account.ts
  apps/browser/src/platform/background/service-factories/api-service.factory.ts
  apps/browser/src/popup/services/services.module.ts
  apps/cli/src/bw.ts
  apps/cli/src/platform/services/node-api.service.ts
  apps/desktop/src/app/accounts/settings.component.ts
  apps/desktop/src/app/app.component.ts
  apps/desktop/src/app/services/services.module.ts
  apps/desktop/src/models/account.ts
  apps/web/src/app/core/core.module.ts
  apps/web/src/app/core/state/account.ts
  apps/web/src/app/settings/preferences.component.ts
  libs/angular/src/components/settings/vault-timeout-input.component.ts
  libs/angular/src/services/injection-tokens.ts
  libs/angular/src/services/jslib-services.module.ts
  libs/auth/src/common/login-strategies/auth-request-login.strategy.spec.ts
  libs/auth/src/common/login-strategies/auth-request-login.strategy.ts
  libs/auth/src/common/login-strategies/login.strategy.spec.ts
  libs/auth/src/common/login-strategies/login.strategy.ts
  libs/auth/src/common/login-strategies/password-login.strategy.spec.ts
  libs/auth/src/common/login-strategies/password-login.strategy.ts
  libs/auth/src/common/login-strategies/sso-login.strategy.spec.ts
  libs/auth/src/common/login-strategies/sso-login.strategy.ts
  libs/auth/src/common/login-strategies/user-api-login.strategy.spec.ts
  libs/auth/src/common/login-strategies/user-api-login.strategy.ts
  libs/auth/src/common/login-strategies/webauthn-login.strategy.spec.ts
  libs/auth/src/common/login-strategies/webauthn-login.strategy.ts
  libs/auth/src/common/services/login-strategies/login-strategy.service.spec.ts
  libs/auth/src/common/services/login-strategies/login-strategy.service.ts
  libs/common/src/abstractions/vault-timeout/vault-timeout-settings.service.ts
  libs/common/src/auth/abstractions/token.service.ts
  libs/common/src/auth/services/token.service.spec.ts
  libs/common/src/auth/services/token.service.ts
  libs/common/src/platform/abstractions/state.service.ts
  libs/common/src/platform/models/domain/account.ts
  libs/common/src/platform/models/domain/global-state.ts
  libs/common/src/platform/services/crypto.service.spec.ts
  libs/common/src/platform/services/crypto.service.ts
  libs/common/src/platform/services/state.service.ts
  libs/common/src/platform/services/system.service.ts
  libs/common/src/platform/state/state-definitions.ts
  libs/common/src/services/api.service.ts
  libs/common/src/services/vault-timeout/vault-timeout-settings.service.spec.ts
  libs/common/src/services/vault-timeout/vault-timeout-settings.service.ts
  libs/common/src/services/vault-timeout/vault-timeout-settings.state.spec.ts
  libs/common/src/services/vault-timeout/vault-timeout-settings.state.ts
  libs/common/src/services/vault-timeout/vault-timeout.service.spec.ts
  libs/common/src/services/vault-timeout/vault-timeout.service.ts
  libs/common/src/state-migrations/migrate.ts
  libs/common/src/state-migrations/migration-helper.spec.ts
  libs/common/src/state-migrations/migrations/62-migrate-vault-timeout-settings-svc-to-state-provider.spec.ts
  libs/common/src/state-migrations/migrations/62-migrate-vault-timeout-settings-svc-to-state-provider.ts
  libs/common/src/types/vault-timeout.type.ts
Labels: needs-qa

#9108 [AC-2570] Existing providers see new CB experience on Admin Console org Billing Subscription page
  apps/web/src/app/billing/organizations/organization-subscription-cloud.component.ts
Labels: needs-qa

#9164 PM-5501 - VaultTimeoutSettingsSvc State Provider Migration - Small bugfixes
  apps/browser/src/auth/popup/settings/account-security.component.ts
  apps/desktop/src/app/accounts/settings.component.ts
  libs/common/src/services/vault-timeout/vault-timeout-settings.service.spec.ts
  libs/common/src/services/vault-timeout/vault-timeout-settings.service.ts
Labels: needs-qa

#9182 [AC-2602] Fix groups modal not loading for providers
  apps/web/src/app/admin-console/organizations/manage/group-add-edit.component.ts
Labels: needs-qa

#9141 [PM-8059] Clarify warning message
  apps/web/src/app/auth/settings/security/change-kdf/change-kdf-confirmation.component.html
  apps/web/src/app/auth/settings/security/change-kdf/change-kdf.component.html
  apps/web/src/locales/en/messages.json
Labels: community-pr

#8750 [AC-1603] Hide vault selector at Admin Console's import
  libs/importer/src/components/import.component.html
  libs/importer/src/components/import.component.ts
Labels: web

#9197 [PM-6823] Vault Header Refresh
  apps/browser/src/_locales/en/messages.json
  apps/browser/src/platform/popup/components/pop-out.component.html
  apps/browser/src/platform/popup/components/pop-out.component.ts
  apps/browser/src/vault/popup/components/vault/vault-v2.component.html
Labels: needs-qa

#9179 [AC-2601] Hide Vault filters for providers when flag enabled
  apps/web/src/app/vault/org-vault/vault.component.html
  apps/web/src/app/vault/org-vault/vault.component.ts
Labels: needs-qa

#9216 [PM-8197] Do not allow browser biometric for locked account
  apps/browser/src/_locales/en/messages.json
  apps/browser/src/background/nativeMessaging.background.ts
  apps/desktop/src/services/native-messaging.service.ts
Labels: needs-qa

#9012 [AC-2514] Added copy for SM trial organizations subscription page
  apps/web/src/app/billing/organizations/organization-subscription-cloud.component.html
  apps/web/src/locales/en/messages.json
Labels: needs-qa

#9011 [AC-2513] Only showing PM subscription adjustment form if the user is a PM user
  apps/web/src/app/billing/organizations/organization-subscription-cloud.component.html
Labels: needs-qa

#9229 Wait for account to switch before proceeding
  apps/browser/src/background/main.background.ts
Labels: needs-qa

#9223 [PM-8156] Bugfix - Defer badge and menu state updates
  apps/browser/src/background/runtime.background.ts
Labels: needs-qa

#9185 PM-8045 All Subscription plans can be selected same time
  apps/web/src/app/billing/organizations/organization-plans.component.html
Labels: needs-qa

#8321 [PM-5018] Migrate Add Credit component
  apps/web/src/app/billing/shared/add-credit-dialog.component.html
  apps/web/src/app/billing/shared/add-credit-dialog.component.ts
  apps/web/src/app/billing/shared/add-credit.component.html
  apps/web/src/app/billing/shared/billing-shared.module.ts
  apps/web/src/app/billing/shared/payment-method.component.html
  apps/web/src/app/billing/shared/payment-method.component.ts
Labels: needs-qa

#8658 PM-2166 Update Purge vault dialog
  apps/web/src/app/admin-console/organizations/settings/account.component.html
  apps/web/src/app/admin-console/organizations/settings/account.component.ts
  apps/web/src/app/auth/settings/account/account.component.html
  apps/web/src/app/auth/settings/account/account.component.ts
  apps/web/src/app/vault/settings/purge-vault.component.html
  apps/web/src/app/vault/settings/purge-vault.component.ts
Labels: needs-qa

#8723 PM -2050 Update Bulk Confirm Dialog
  apps/web/src/app/admin-console/organizations/members/components/bulk/bulk-confirm.component.html
  apps/web/src/app/admin-console/organizations/members/components/bulk/bulk-confirm.component.ts
  apps/web/src/app/admin-console/organizations/members/people.component.ts
Labels: needs-qa

#8747 PM-2172 Update User Add Edit Dialog
  apps/web/src/app/admin-console/organizations/members/components/member-dialog/member-dialog.component.html
Labels: needs-qa

#8749 AC-2389 Migrate Disable Send Component
  apps/web/src/app/admin-console/organizations/policies/disable-send.component.html
Labels: needs-qa

#8794 AC-2387 Migrate Nested Checkbox Component
  apps/web/src/app/admin-console/organizations/members/components/member-dialog/nested-checkbox.component.html
Labels: needs-qa

#8799 AC-2390 Migrate Password Generator component
  apps/web/src/app/admin-console/organizations/policies/password-generator.component.html
  apps/web/src/app/admin-console/organizations/policies/password-generator.component.ts
Labels: needs-qa

#8802 AC-2394 Migrate Send Options component
  apps/web/src/app/admin-console/organizations/policies/send-options.component.html
Labels: needs-qa

#8894 AC-2402 Migrate sponsoring org row component
  apps/web/src/app/admin-console/settings/sponsoring-org-row.component.html
  apps/web/src/app/admin-console/settings/sponsoring-org-row.component.ts
Labels: needs-qa

#9277 Auth/PM-5501 - VaultTimeoutSettingsSvc State Provider Migration - Cleanup desktop orphaned data
  libs/common/src/state-migrations/migrations/62-migrate-vault-timeout-settings-svc-to-state-provider.spec.ts
  libs/common/src/state-migrations/migrations/62-migrate-vault-timeout-settings-svc-to-state-provider.ts
Labels: needs-qa

#8652 [PM 5025] migrate update license component
  apps/web/src/app/billing/shared/update-license.component.html
  apps/web/src/app/billing/shared/update-license.component.ts
Labels: needs-qa

#8496 [PM 4980] security keys component migration
  apps/web/src/app/auth/settings/security/security-keys.component.html
Labels: needs-qa

#8661 [PM 4983] migrate vault timeout input component
  apps/web/src/app/settings/vault-timeout-input.component.html
Labels: needs-qa

#8801 [AC-2408] migrate maximum vault timeout component
  bitwarden_license/bit-web/src/app/admin-console/policies/maximum-vault-timeout.component.html
Labels: needs-qa

#9299 fix clear when account unavailable error
  apps/browser/src/background/main.background.ts
  apps/cli/src/service-container.ts
  apps/desktop/src/app/app.component.ts
  apps/web/src/app/app.component.ts
  libs/common/src/tools/generator/legacy-password-generation.service.ts
Labels: needs-qa

#8745 [PM-4976] migrate domain rules component
  apps/web/src/app/settings/domain-rules.component.html
  apps/web/src/app/settings/domain-rules.component.ts
Labels: needs-qa

#8489 [PM 4972] change kdf confirmation component migration
  apps/web/src/app/auth/settings/security/change-kdf/change-kdf-confirmation.component.html
  apps/web/src/app/auth/settings/security/change-kdf/change-kdf-confirmation.component.ts
Labels: needs-qa

#8895 [AC-2400] migrating accept families for enterprise setup component
  apps/web/src/app/admin-console/organizations/sponsorships/families-for-enterprise-setup.component.html
  apps/web/src/app/admin-console/organizations/sponsorships/families-for-enterprise-setup.component.ts
Labels: needs-qa

#9301 [PM-8004] [AC-2603] [AC-2616] [AC-2621] [AC-2622] Unmanaged collection fixes
  apps/web/src/app/vault/components/vault-items/vault-collection-row.component.html
  apps/web/src/app/vault/components/vault-items/vault-collection-row.component.ts
  apps/web/src/app/vault/components/vault-items/vault-items.component.ts
  apps/web/src/app/vault/core/collection-admin.service.ts
  apps/web/src/app/vault/core/views/collection-admin.view.ts
  apps/web/src/app/vault/org-vault/vault.component.ts
  apps/web/src/app/vault/utils/collection-utils.ts
  libs/common/src/admin-console/models/domain/organization.ts
  libs/common/src/vault/models/domain/collection.spec.ts
  libs/common/src/vault/models/response/collection.response.ts
  libs/common/src/vault/models/view/collection.view.ts
Labels: needs-qa

#8970 AC-2410 Migrate Events Component
  apps/web/src/app/admin-console/common/base.events.component.ts
  apps/web/src/app/admin-console/organizations/manage/events.component.html
  apps/web/src/app/admin-console/organizations/manage/events.component.ts
  bitwarden_license/bit-web/src/app/admin-console/providers/manage/events.component.html
  bitwarden_license/bit-web/src/app/admin-console/providers/manage/events.component.ts
  bitwarden_license/bit-web/src/app/secrets-manager/service-accounts/event-logs/service-accounts-events.component.html
  bitwarden_license/bit-web/src/app/secrets-manager/service-accounts/event-logs/service-accounts-events.component.ts
Labels: needs-qa

#8928 PM-2053 Update Bulk Status dialog
  apps/web/src/app/admin-console/organizations/members/components/bulk/bulk-status.component.html
  apps/web/src/app/admin-console/organizations/members/components/bulk/bulk-status.component.ts
  apps/web/src/app/admin-console/organizations/members/people.component.ts
  bitwarden_license/bit-web/src/app/admin-console/providers/manage/people.component.ts
Labels: needs-qa

#9230 [AC-2559] - BUG - Refactor members search observable chains
  apps/web/src/app/admin-console/common/base.people.component.ts
  apps/web/src/app/admin-console/organizations/members/people.component.html
  apps/web/src/app/admin-console/organizations/members/people.component.ts
  bitwarden_license/bit-web/src/app/admin-console/providers/manage/people.component.html
  bitwarden_license/bit-web/src/app/admin-console/providers/manage/people.component.ts
Labels: bug

#8985 PM-2058 Update Two Factor Recovery Dialog
  apps/web/src/app/auth/settings/two-factor-recovery.component.html
  apps/web/src/app/auth/settings/two-factor-recovery.component.ts
  apps/web/src/app/auth/settings/two-factor-setup.component.html
  apps/web/src/app/auth/settings/two-factor-setup.component.ts
Labels: needs-qa

#8503 PM-2165 Migrate delete account dialog
  apps/web/src/app/auth/settings/account/account.component.html
  apps/web/src/app/auth/settings/account/account.component.ts
  apps/web/src/app/auth/settings/account/delete-account-dialog.component.html
  apps/web/src/app/auth/settings/account/delete-account-dialog.component.ts
  apps/web/src/app/auth/settings/account/delete-account.component.html
  apps/web/src/app/shared/loose-components.module.ts
Labels: needs-qa

#9332 [PM-8174] two subscription header issue fix
  apps/web/src/app/billing/individual/user-subscription.component.html
Labels: needs-qa

#8874 AC-2401 Migrate sponsored families component
  apps/web/src/app/admin-console/settings/sponsored-families.component.html
  apps/web/src/app/admin-console/settings/sponsored-families.component.ts
Labels: needs-qa

#9178 [PM-6606] remove onboarding feature flag
  apps/web/src/app/vault/individual-vault/vault-onboarding/vault-onboarding.component.html
  apps/web/src/app/vault/individual-vault/vault-onboarding/vault-onboarding.component.spec.ts
  apps/web/src/app/vault/individual-vault/vault-onboarding/vault-onboarding.component.ts
  libs/common/src/enums/feature-flag.enum.ts
Labels: needs-qa

#8565 PM 2048 Update Two Factor Options dialog
  apps/web/src/app/auth/two-factor-options.component.html
  apps/web/src/app/auth/two-factor-options.component.ts
  apps/web/src/app/auth/two-factor.component.html
  apps/web/src/app/auth/two-factor.component.ts
Labels: needs-qa

#8659 [PM-5011][PM-7284] migrate user subscription along with update license dialog
  apps/web/src/app/billing/individual/user-subscription.component.html
  apps/web/src/app/billing/individual/user-subscription.component.ts
  apps/web/src/app/billing/shared/billing-shared.module.ts
  apps/web/src/app/billing/shared/update-license-dialog.component.html
  apps/web/src/app/billing/shared/update-license-dialog.component.ts
Labels: needs-qa

#9392 Change Addons to Add-ons
  apps/web/src/locales/en/messages.json
Labels: needs-qa

#9138 Vault - Trial initiation content updates
  apps/web/src/app/auth/trial-initiation/content/enterprise-content.component.html
  apps/web/src/app/auth/trial-initiation/content/logo-badges.component.html
  apps/web/src/app/auth/trial-initiation/content/logo-badges.component.ts
  apps/web/src/app/auth/trial-initiation/content/teams1-content.component.html
  apps/web/src/app/auth/trial-initiation/trial-initiation.module.ts
  apps/web/src/images/register-layout/vault-signup-badges.png
Labels: needs-qa

#9400 [PM-8447] Autofill On Load Causes Decryption to Hang After Browser Startup
  apps/browser/src/autofill/services/autofill.service.spec.ts
  apps/browser/src/autofill/services/autofill.service.ts
  apps/browser/src/background/main.background.ts
  apps/browser/src/popup/services/services.module.ts
Labels: needs-qa

#9355 [PM-7024] - BUG - View events for cipher available for users without permission
  apps/web/src/app/vault/org-vault/vault.component.html
Labels: bug

#9325 PM-8337 Add Invalid Secret Handling to Two Factor Verify Dialog
  apps/web/src/app/auth/settings/two-factor-verify.component.html
  apps/web/src/app/auth/settings/two-factor-verify.component.ts
Labels: needs-qa

#9292 [PM-8292] Fixup `ForegroundSyncService`
  apps/browser/src/background/main.background.ts
  apps/browser/src/platform/messaging/chrome-message.sender.ts
  apps/browser/src/platform/sync/foreground-sync.service.spec.ts
  apps/browser/src/platform/sync/foreground-sync.service.ts
  apps/browser/src/platform/sync/sync-service.listener.spec.ts
  apps/browser/src/platform/sync/sync-service.listener.ts
  apps/browser/src/platform/utils/from-chrome-runtime-messaging.ts
  apps/browser/src/popup/services/services.module.ts
  apps/desktop/src/app/services/services.module.ts
  apps/desktop/src/main.ts
  apps/desktop/src/platform/services/electron-renderer-message.sender.ts
  apps/desktop/src/platform/utils/from-ipc-messaging.ts
  apps/desktop/src/services/electron-main-messaging.service.ts
  libs/angular/src/services/injection-tokens.ts
  libs/angular/src/services/jslib-services.module.ts
  libs/common/src/platform/abstractions/broadcaster.service.ts
  libs/common/src/platform/messaging/helpers.spec.ts
  libs/common/src/platform/messaging/helpers.ts
  libs/common/src/platform/messaging/message.listener.ts
  libs/common/src/platform/messaging/message.sender.ts
  libs/common/src/platform/messaging/subject-message.sender.ts
  libs/common/src/platform/messaging/types.ts
  libs/common/src/platform/services/default-broadcaster.service.ts
Labels: needs-qa

#9408 [AC-2703] Fix copy in members and groups modals for custom users
  apps/web/src/app/admin-console/organizations/manage/group-add-edit.component.html
  apps/web/src/app/admin-console/organizations/manage/group-add-edit.component.ts
  apps/web/src/app/admin-console/organizations/members/components/member-dialog/member-dialog.component.html
  apps/web/src/app/admin-console/organizations/members/components/member-dialog/member-dialog.component.ts
Labels: needs-qa

#9417 [PM-8480] Rename ambiguous Jest testing method
  apps/browser/src/autofill/background/notification.background.spec.ts
  apps/browser/src/autofill/background/overlay.background.spec.ts
  apps/browser/src/autofill/content/autofill-init.spec.ts
  apps/browser/src/autofill/content/content-message-handler.spec.ts
  apps/browser/src/autofill/spec/testing-utils.ts
  apps/browser/src/platform/offscreen-document/offscreen-document.spec.ts
  apps/browser/src/vault/fido2/background/fido2.background.spec.ts
Labels: needs-qa

#9127 [PM-8039] Fastmail: Change website default value to empty string.
  libs/common/src/tools/generator/username/email-forwarders/fastmail-forwarder.ts
  libs/common/src/tools/generator/username/forwarders/fastmail.ts
Labels: community-pr

#9440 fix lint failure
  libs/common/src/tools/generator/username/email-forwarders/fastmail-forwarder.ts
Labels: needs-qa

#9441 [PM-8436] [PM-8483] Support Asymmetric Mac Encryption Types in EncString
  libs/common/src/platform/models/domain/enc-string.spec.ts
  libs/common/src/platform/models/domain/enc-string.ts
Labels: needs-qa

#9364 [PM-8210] Discourage Active User in `CryptoService`
  libs/common/src/auth/services/device-trust.service.implementation.ts
  libs/common/src/auth/services/device-trust.service.spec.ts
  libs/common/src/platform/abstractions/crypto.service.ts
  libs/common/src/platform/misc/convert-values.spec.ts
  libs/common/src/platform/misc/convert-values.ts
  libs/common/src/platform/services/crypto.service.spec.ts
  libs/common/src/platform/services/crypto.service.ts
  libs/common/src/platform/services/key-state/org-keys.state.spec.ts
  libs/common/src/platform/services/key-state/org-keys.state.ts
  libs/common/src/platform/services/key-state/provider-keys.state.spec.ts
  libs/common/src/platform/services/key-state/provider-keys.state.ts
  libs/common/src/platform/services/key-state/user-key.state.spec.ts
  libs/common/src/platform/services/key-state/user-key.state.ts
  libs/common/src/vault/services/cipher.service.ts
Labels: needs-qa

#9412 Browser - Add `jest-preset-angular`
  apps/browser/src/autofill/content/autofill-init.spec.ts
  apps/browser/src/autofill/utils/index.spec.ts
  apps/browser/src/vault/fido2/content/page-script.webauthn-supported.spec.ts
  apps/browser/test.setup.ts
Labels: needs-qa

#9465 [PM-6788] enable bugfixes in babel/preset-env
  babel.config.json
Labels: needs-qa
