Repository bitwarden/clients, pull requests merged in 2024-03, with the labels that each got.

#8203 Include Storage Location In Fake Cache Key
  libs/common/spec/fake-state-provider.ts
Labels: needs-qa

#8156 [AC-2248][PM-5352] Bugfix - Fix non-working policy state in autofill settings service
  apps/browser/src/autofill/background/notification.background.ts
  apps/browser/src/autofill/background/overlay.background.spec.ts
  apps/browser/src/autofill/background/overlay.background.ts
  apps/browser/src/autofill/browser/context-menu-clicked-handler.spec.ts
  apps/browser/src/autofill/browser/context-menu-clicked-handler.ts
  apps/browser/src/autofill/browser/main-context-menu-handler.spec.ts
  apps/browser/src/autofill/browser/main-context-menu-handler.ts
  apps/browser/src/autofill/content/autofill-init.spec.ts
  apps/browser/src/autofill/overlay/iframe-content/autofill-overlay-iframe.service.spec.ts
  apps/browser/src/autofill/overlay/iframe-content/autofill-overlay-iframe.service.ts
  apps/browser/src/autofill/overlay/pages/button/autofill-overlay-button.ts
  apps/browser/src/autofill/overlay/pages/list/autofill-overlay-list.ts
  apps/browser/src/autofill/overlay/pages/shared/autofill-overlay-page-element.ts
  apps/browser/src/autofill/popup/settings/autofill.component.ts
  apps/browser/src/autofill/services/autofill-overlay-content.service.spec.ts
  apps/browser/src/autofill/services/autofill-overlay-content.service.ts
  apps/browser/src/autofill/services/autofill.service.spec.ts
  apps/browser/src/autofill/services/autofill.service.ts
  apps/browser/src/autofill/services/insert-autofill-content.service.spec.ts
  apps/browser/src/autofill/services/insert-autofill-content.service.ts
  apps/browser/src/autofill/utils/autofill-overlay.enum.ts
  apps/browser/src/background/runtime.background.ts
  apps/browser/src/popup/settings/options.component.ts
  apps/browser/src/vault/popup/components/vault/current-tab.component.ts
  apps/browser/tsconfig.json
  libs/common/src/autofill/constants/index.ts
  libs/common/src/autofill/services/autofill-settings.service.ts
  libs/common/src/autofill/types/index.ts
  libs/common/src/state-migrations/migrations/18-move-autofill-settings-to-state-providers.ts
  libs/common/src/state-migrations/migrations/25-move-clear-clipboard-to-autofill-settings-state-provider.ts
Labels: bug

#8234 Use new FileUploadService in Angular context
  apps/browser/src/popup/services/services.module.ts
Labels: needs-qa

#8217 [PM-6647] Create new log service for angular environment
  apps/browser/src/popup/services/services.module.ts
Labels: needs-qa

#8255 Consider Higher `stateVersion` "ready"
  libs/common/src/state-migrations/migrate.ts
Labels: needs-qa

#8231 Use existing angular storage service for browser's secure storage
  apps/browser/src/background/main.background.ts
  apps/browser/src/popup/services/services.module.ts
Labels: needs-qa

#8306 DEVOPS-1840 - Update version bump workflow for automatic version calculation
  .github/workflows/version-auto-bump.yml
  .github/workflows/version-bump.yml
Labels: devops

#8312 Bugfix - Fix cipher service factory not using domain settings service correctly
  libs/angular/src/services/jslib-services.module.ts
Labels: bug

#8313 Reorder import
  libs/common/spec/fake-state-provider.ts
Labels: needs-qa

#8326 Log key when no active user found
  libs/common/src/platform/state/implementations/default-active-user-state.ts
Labels: needs-qa

#8287 [PM-6740] Fix default value for autoCopyTotp
  libs/common/src/autofill/services/autofill-settings.service.ts
Labels: bug

#8351 Revert "Use global state for biometric prompt cancel storage"
  libs/common/spec/fake-account-service.ts
  libs/common/src/platform/biometrics/biometric-state.service.spec.ts
  libs/common/src/platform/biometrics/biometric-state.service.ts
  libs/common/src/platform/biometrics/biometric.state.spec.ts
  libs/common/src/platform/biometrics/biometric.state.ts
  libs/common/src/state-migrations/migrate.ts
  libs/common/src/state-migrations/migrations/38-delete-orphaned-biometric-prompt-data.spec.ts
  libs/common/src/state-migrations/migrations/38-delete-orphaned-biometric-prompt-data.ts
Labels: needs-qa

#8347 [AC-2304] added User Status check to revoke-restore and remove components
  apps/web/src/app/admin-console/organizations/members/components/bulk/bulk-remove.component.ts
  apps/web/src/app/admin-console/organizations/members/components/bulk/bulk-restore-revoke.component.ts
Labels: needs-qa

#8371 [PM-6897] Update locales used on browser, desktop and web
  apps/browser/src/platform/popup/locales.ts
  apps/desktop/src/platform/app/locales.ts
  apps/web/src/app/shared/locales.ts
Labels: needs-qa

#8291 [PM-6334] Passing CollectionView or FolderView from Import component to ImportService
  libs/importer/src/components/import.component.html
  libs/importer/src/services/import.service.abstraction.ts
  libs/importer/src/services/import.service.spec.ts
  libs/importer/src/services/import.service.ts
Labels: bug

#8403 Create New Method for Setting Avatar Color from Sync
  libs/common/src/auth/abstractions/avatar.service.ts
  libs/common/src/auth/services/avatar.service.ts
  libs/common/src/vault/services/sync/sync.service.ts
Labels: needs-qa

#5968 [PM-3316] Feature addition - Toggle Hardware Acceleration [Desktop]
  apps/desktop/src/app/accounts/settings.component.html
  apps/desktop/src/app/accounts/settings.component.ts
  apps/desktop/src/app/services/services.module.ts
  apps/desktop/src/locales/en/messages.json
  apps/desktop/src/main.ts
  apps/desktop/src/platform/services/desktop-settings.service.ts
  libs/common/src/platform/state/state-definitions.ts
Labels: community-pr

#8434 DEVOPS-1898 - Remove ghpages-deploy job
  .github/workflows/release-web.yml
Labels: devops

#8427 [PM-6983] Disable hardware acceleration for bad GPUs
  apps/desktop/src/main.ts
Labels: needs-qa

#8441 [CL-232] exclude bit-dialog from global extension header styles
  apps/browser/src/popup/scss/base.scss
Labels: needs-qa

#8442 [PM-4406] fix select overlay visibility when popup is zoomed
  apps/browser/src/popup/scss/base.scss
Labels: needs-qa

#8468 Version Bump Workflow - Fix set-final-version-output step
  .github/workflows/version-bump.yml
Labels: devops

#8495 add back call to verify by PIN
  libs/common/src/auth/services/user-verification/user-verification.service.ts
Labels: needs-qa

#8498 [AC-2351] Fix unable to move items to organization in Browser
  libs/angular/src/components/share.component.ts
Labels: needs-qa

#8527 [STRICT TS] Migrate platform abstract services functions
  apps/desktop/src/platform/main/biometric/biometrics.service.abstraction.ts
  libs/angular/src/platform/abstractions/form-validation-errors.service.ts
  libs/angular/src/platform/services/theming/theming.service.abstraction.ts
  libs/common/src/platform/abstractions/app-id.service.ts
  libs/common/src/platform/abstractions/broadcaster.service.ts
  libs/common/src/platform/abstractions/config/config-api.service.abstraction.ts
  libs/common/src/platform/abstractions/crypto-function.service.ts
  libs/common/src/platform/abstractions/crypto.service.ts
  libs/common/src/platform/abstractions/encrypt.service.ts
  libs/common/src/platform/abstractions/file-download/file-download.service.ts
  libs/common/src/platform/abstractions/file-upload/file-upload.service.ts
  libs/common/src/platform/abstractions/i18n.service.ts
  libs/common/src/platform/abstractions/key-generation.service.ts
  libs/common/src/platform/abstractions/log.service.ts
  libs/common/src/platform/abstractions/messaging.service.ts
  libs/common/src/platform/abstractions/platform-utils.service.ts
  libs/common/src/platform/abstractions/system.service.ts
  libs/common/src/platform/abstractions/translation.service.ts
  libs/common/src/platform/abstractions/validation.service.ts
  libs/common/src/platform/biometrics/biometric-state.service.ts
  libs/common/src/platform/state/derived-state.provider.ts
  libs/common/src/platform/state/global-state.provider.ts
  libs/common/src/platform/state/state.provider.ts
  libs/common/src/platform/state/user-state.provider.ts
  libs/common/src/platform/theming/theme-state.service.ts
Labels: needs-qa

#8451 [PM-5499] Move auth request notification to service
  apps/browser/src/auth/popup/login-via-auth-request.component.ts
  apps/desktop/src/auth/login/login-via-auth-request.component.ts
  apps/web/src/app/auth/login/login-via-auth-request.component.ts
  libs/angular/src/auth/components/login-via-auth-request.component.ts
  libs/angular/src/services/jslib-services.module.ts
  libs/auth/src/common/abstractions/auth-request.service.abstraction.ts
  libs/auth/src/common/abstractions/login-strategy.service.ts
  libs/auth/src/common/services/auth-request/auth-request.service.ts
  libs/auth/src/common/services/login-strategies/login-strategy.service.ts
  libs/common/src/auth/abstractions/anonymous-hub.service.ts
  libs/common/src/auth/services/anonymous-hub.service.ts
Labels: needs-qa

#8532 Await `this.getScimEndpointUrl()`
  bitwarden_license/bit-web/src/app/admin-console/organizations/manage/scim.component.ts
Labels: needs-qa
