Repository bitwarden/clients, pull requests merged in 2024-01, with the labels that each got.

#7291 [PM-5367] Update the content of the enterprise vault page
  apps/web/src/app/auth/trial-initiation/content/enterprise-content.component.html
  apps/web/src/app/auth/trial-initiation/content/enterprise1-content.component.html
  apps/web/src/app/auth/trial-initiation/content/enterprise2-content.component.html
  apps/web/src/app/auth/trial-initiation/content/logo-cnet-5-stars.component.html
  apps/web/src/app/auth/trial-initiation/content/logo-cnet-5-stars.component.ts
  apps/web/src/app/auth/trial-initiation/content/review-logo.component.html
  apps/web/src/app/auth/trial-initiation/content/review-logo.component.ts
  apps/web/src/app/auth/trial-initiation/trial-initiation.module.ts
  apps/web/src/images/register-layout/capterra-logo.svg
  apps/web/src/images/register-layout/cnet-logo.svg
  apps/web/src/images/register-layout/g2-logo.svg
  apps/web/src/images/register-layout/get-app-logo.svg
Labels: community-pr

#7422 [PM-5453] Route on `switchAccountFinish` Message
  apps/browser/src/auth/popup/update-temp-password.component.ts
  libs/angular/src/auth/components/update-temp-password.component.ts
Labels: needs-qa

#5985 [PM-3343] Capture TOTP QR codes from websites in the browser extension
  apps/browser/src/_locales/en/messages.json
  apps/browser/src/manifest.json
  apps/browser/src/manifest.v3.json
  apps/browser/src/platform/browser/browser-api.ts
  apps/browser/src/vault/popup/components/vault/add-edit.component.html
  apps/browser/src/vault/popup/components/vault/add-edit.component.ts
  apps/desktop/src/vault/app/vault/add-edit.component.ts
  apps/web/src/app/auth/settings/emergency-access/view/emergency-add-edit-cipher.component.ts
  apps/web/src/app/vault/individual-vault/add-edit.component.ts
  apps/web/src/app/vault/org-vault/add-edit.component.ts
  libs/angular/src/vault/components/add-edit.component.ts
  package-lock.json
  package.json
Labels: community-pr

#7450 PM-5589 add-edit defect update
  apps/desktop/src/vault/app/vault/add-edit.component.ts
  apps/web/src/app/auth/settings/emergency-access/view/emergency-add-edit-cipher.component.ts
  apps/web/src/app/vault/individual-vault/add-edit.component.ts
  apps/web/src/app/vault/org-vault/add-edit.component.ts
Labels: needs-qa

#7451 Remove unnecessary complex types
  apps/browser/src/platform/state/background-derived-state.provider.ts
  apps/browser/src/platform/state/background-derived-state.ts
  apps/browser/src/platform/state/derived-state-service-interactions.spec.ts
  apps/browser/src/platform/state/foreground-derived-state.provider.ts
  apps/browser/src/platform/state/foreground-derived-state.ts
  libs/common/spec/fake-state-provider.ts
  libs/common/src/platform/state/derive-definition.ts
  libs/common/src/platform/state/derived-state.provider.ts
  libs/common/src/platform/state/implementations/default-derived-state.provider.ts
  libs/common/src/platform/state/implementations/default-derived-state.spec.ts
  libs/common/src/platform/state/implementations/default-derived-state.ts
  libs/common/src/platform/state/implementations/default-state.provider.ts
  libs/common/src/platform/state/state.provider.ts
  libs/common/src/types/state.d.ts
Labels: needs-qa

#6941 [PM-4906] Allow bitmenu to overflow and scroll when needed
  libs/components/src/menu/menu.component.html
Labels: community-pr

#7470 [PM-5632] Update Bitwarden extension review URLs
  apps/browser/README.md
  apps/browser/src/popup/settings/settings.component.ts
  apps/desktop/src/main/menu/menu.help.ts
Labels: community-pr

#7415 [PM-5432] Overlay button iframe presents with a white background on websites that use dark mode
  apps/browser/src/autofill/overlay/abstractions/autofill-overlay-button.ts
  apps/browser/src/autofill/overlay/abstractions/autofill-overlay-iframe.service.ts
  apps/browser/src/autofill/overlay/iframe-content/autofill-overlay-iframe.service.spec.ts
  apps/browser/src/autofill/overlay/iframe-content/autofill-overlay-iframe.service.ts
  apps/browser/src/autofill/overlay/pages/button/autofill-overlay-button.spec.ts
  apps/browser/src/autofill/overlay/pages/button/autofill-overlay-button.ts
Labels: browser

#7464 [PM-5616] Remove document element mutation observer from Autofill Overlay to fix strange DOM manipulation behavior
  apps/browser/src/autofill/services/autofill-overlay-content.service.spec.ts
  apps/browser/src/autofill/services/autofill-overlay-content.service.ts
Labels: browser

#7432 [PM-5056] Improved UI on format selector for Importer
  apps/browser/src/_locales/en/messages.json
  apps/desktop/src/locales/en/messages.json
  apps/web/src/locales/en/messages.json
  libs/importer/src/components/import.component.html
  libs/importer/src/components/import.component.ts
Labels: browser, desktop, web

#7365 [AC-1893] Removed logic to downgrade Manager roles and remove Edit/Delete any collection permissions for Flexible Collections
  apps/browser/src/background/main.background.ts
  apps/cli/src/bw.ts
  apps/web/src/app/billing/organizations/sm-subscribe-standalone.component.ts
  libs/angular/src/services/jslib-services.module.ts
  libs/common/src/admin-console/abstractions/organization/organization.service.abstraction.ts
  libs/common/src/admin-console/services/organization/organization.service.spec.ts
  libs/common/src/admin-console/services/organization/organization.service.ts
  libs/common/src/vault/services/sync/sync.service.ts
Labels: needs-qa

#6649 [PM-4260] [BEEEP] Mask TOTP seeds in cipher edit view - similar to how the password is hidden
  apps/browser/src/vault/popup/components/vault/add-edit.component.html
  libs/angular/src/vault/components/add-edit.component.ts
  libs/common/src/enums/event-type.enum.ts
Labels: browser

#7596 [PM-5763] Fix branch links
  README.md
Labels: community-pr

#7449 [PM-4437] Bug - Exclude non-standard search inputs from autofill
  apps/browser/src/autofill/services/autofill-constants.ts
  apps/browser/src/autofill/services/autofill.service.spec.ts
  apps/browser/src/autofill/services/autofill.service.ts
Labels: bug

#7590 [PM-5488] Master password re-prompt not triggering correctly from autofill action
  apps/browser/src/autofill/services/autofill.service.spec.ts
  apps/browser/src/autofill/services/autofill.service.ts
Labels: browser

#7255 [PM-5321] chore: replace duplicated jest.disabledWorkspaceFolders "desktop" entry with "root"
  clients.code-workspace
Labels: community-pr

#7592 [PM-5617] Re-add setting to turn off browser autofill
  apps/browser/gulpfile.js
  apps/browser/src/_locales/en/messages.json
  apps/browser/src/autofill/background/service_factories/autofill-service.factory.ts
  apps/browser/src/autofill/popup/settings/autofill.component.html
  apps/browser/src/autofill/popup/settings/autofill.component.ts
  apps/browser/src/autofill/services/autofill.service.spec.ts
  apps/browser/src/autofill/services/autofill.service.ts
  apps/browser/src/background/main.background.ts
  apps/browser/src/manifest.json
  apps/browser/src/manifest.v3.json
  apps/browser/src/platform/browser/browser-api.spec.ts
  apps/browser/src/platform/browser/browser-api.ts
  apps/browser/test.setup.ts
Labels: browser

#7542 [PM-5682] Chrome's extension API for retrieving closed ShadowRoots from elements causes performance issues when passed a Node with nested children
  apps/browser/src/autofill/services/collect-autofill-content.service.spec.ts
  apps/browser/src/autofill/services/collect-autofill-content.service.ts
Labels: browser

#7655 [PM-5806] Remove the Inline Auto-fill Menu From `textarea` Fields
  apps/browser/src/autofill/services/autofill-constants.ts
  apps/browser/src/autofill/services/autofill-overlay-content.service.spec.ts
  apps/browser/src/autofill/services/autofill-overlay-content.service.ts
Labels: browser

#7664 Update Renovate config
  .github/renovate.json
Labels: needs-qa

#7666 Bugfix - Handle access on undefined cipher properties
  libs/angular/src/vault/components/add-edit.component.ts
Labels: needs-qa

#7582 [PM-5749] Make cipher decryption faster by replacing promise.all in encrypt.service.implementation
  libs/common/src/platform/services/cryptography/encrypt.service.implementation.ts
Labels: community-pr

#7656 [PM-4275] Showing hide text on send
  apps/desktop/src/app/tools/send/add-edit.component.html
Labels: bug

#7735 Use `OBSERVABLE_MEMORY_STORAGE`
  apps/web/src/app/core/core.module.ts
Labels: needs-qa

#7740 [PM-5958] Fix typo
  .github/ISSUE_TEMPLATE/desktop.yml
Labels: community-pr

#7713 [PM-5943] Fix badge links
  README.md
Labels: community-pr
