Repository bitwarden/clients, pull requests merged in 2024-06, with the labels that each got.

#9193 Fix PM-8134: Change b64 to b64url
  apps/web/src/app/auth/core/services/webauthn-login/request/webauthn-login-attestation-response.request.ts
Labels: needs-qa

#9365 [PM-6826] Vault filter refresh
  apps/browser/src/_locales/en/messages.json
  apps/browser/src/vault/popup/components/vault-v2/vault-list-filters/vault-list-filters.component.html
  apps/browser/src/vault/popup/components/vault-v2/vault-list-filters/vault-list-filters.component.ts
  apps/browser/src/vault/popup/components/vault/vault-v2.component.html
  apps/browser/src/vault/popup/components/vault/vault-v2.component.ts
  apps/browser/src/vault/popup/services/vault-popup-items.service.spec.ts
  apps/browser/src/vault/popup/services/vault-popup-items.service.ts
  apps/browser/src/vault/popup/services/vault-popup-list-filters.service.spec.ts
  apps/browser/src/vault/popup/services/vault-popup-list-filters.service.ts
  libs/components/src/chip-select/chip-select.component.ts
  libs/components/src/icon/icons/deactivated-org.ts
  libs/components/src/icon/icons/index.ts
Labels: needs-qa

#9421 Revert "Vault - Trial initiation content updates"
  apps/web/src/app/auth/trial-initiation/content/enterprise-content.component.html
  apps/web/src/app/auth/trial-initiation/content/enterprise1-content.component.html
  apps/web/src/app/auth/trial-initiation/content/enterprise2-content.component.html
  apps/web/src/app/auth/trial-initiation/content/teams1-content.component.html
  apps/web/src/app/auth/trial-initiation/content/teams2-content.component.html
  apps/web/src/images/register-layout/vault-signup-badges.png
Labels: needs-qa

#8913 Auth - PM-7392 & PM-7436 - Token Service - Desktop - Add disk fallback for secure storage failures
  apps/browser/src/_locales/en/messages.json
  apps/browser/src/background/main.background.ts
  apps/browser/src/popup/app.component.ts
  apps/cli/src/platform/services/node-api.service.ts
  apps/cli/src/service-container.ts
  apps/desktop/src/app/app.component.ts
  apps/desktop/src/locales/en/messages.json
  apps/desktop/src/main.ts
  apps/desktop/src/main/window.main.ts
  apps/web/src/app/app.component.ts
  apps/web/src/locales/en/messages.json
  libs/angular/src/services/injection-tokens.ts
  libs/angular/src/services/jslib-services.module.ts
  libs/auth/src/common/index.ts
  libs/auth/src/common/types/index.ts
  libs/auth/src/common/types/logout-reason.type.ts
  libs/common/src/auth/abstractions/token.service.ts
  libs/common/src/auth/services/key-connector.service.ts
  libs/common/src/auth/services/token.service.spec.ts
  libs/common/src/auth/services/token.service.ts
  libs/common/src/platform/models/domain/enc-string.spec.ts
  libs/common/src/platform/models/domain/enc-string.ts
  libs/common/src/services/api.service.ts
  libs/common/src/services/notifications.service.ts
  libs/common/src/services/vault-timeout/vault-timeout.service.spec.ts
  libs/common/src/services/vault-timeout/vault-timeout.service.ts
  libs/common/src/vault/services/sync/sync.service.ts
  libs/components/src/toast/toast.service.ts
Labels: needs-qa

#9474 [AC-2635] [AC-2636] Add device-approval deny and deny-all commands
  bitwarden_license/bit-cli/src/admin-console/device-approval/deny-all.command.ts
  bitwarden_license/bit-cli/src/admin-console/device-approval/deny.command.ts
  bitwarden_license/bit-cli/src/admin-console/device-approval/device-approval.program.ts
Labels: needs-qa

#8917 [SM-1192] displaying full project name in tooltip and allowing more of project name in bit badge/project column
  bitwarden_license/bit-web/src/app/secrets-manager/shared/secrets-list.component.html
  libs/components/src/badge/badge.directive.ts
Labels: needs-qa

#9477 Ac 2680 defect custom permission manage account recovery no longer auto triggers the manage users permission
  apps/web/src/app/admin-console/organizations/members/components/member-dialog/member-dialog.component.html
Labels: needs-qa

#9508 [PM-8587] Update icons for folder & collection filters
  apps/browser/src/vault/popup/services/vault-popup-list-filters.service.spec.ts
  apps/browser/src/vault/popup/services/vault-popup-list-filters.service.ts
Labels: needs-qa

#8443 [PM-5014] Download license component migration
  apps/web/src/app/billing/organizations/download-license.component.html
  apps/web/src/app/billing/organizations/download-license.component.ts
  apps/web/src/app/billing/organizations/organization-billing.module.ts
  apps/web/src/app/billing/organizations/organization-subscription-cloud.component.html
  apps/web/src/app/billing/organizations/organization-subscription-cloud.component.ts
Labels: needs-qa

#8974 [PM-2057] update two factor email dialog
  apps/web/src/app/auth/settings/two-factor-email.component.html
  apps/web/src/app/auth/settings/two-factor-email.component.ts
  apps/web/src/app/auth/settings/two-factor-setup.component.ts
Labels: needs-qa

#8562 [PM 2164] api-key component migration
  apps/web/src/app/admin-console/organizations/settings/account.component.ts
  apps/web/src/app/auth/settings/security/api-key.component.html
  apps/web/src/app/auth/settings/security/api-key.component.ts
  apps/web/src/app/auth/settings/security/security-keys.component.ts
Labels: needs-qa

#9307 SM-1213 Add Bitwarden Secrets Manager tip to CLI help
  apps/cli/src/program.ts
Labels: cli

#9481 PM-8478 Defect Visually more padding needed around bit avatar
  apps/web/src/app/auth/settings/account/profile.component.html
Labels: needs-qa

#9177 PM-1938 Migrate Accept Emergency Component
  apps/web/src/app/auth/emergency-access/accept/accept-emergency.component.html
  apps/web/src/app/oss-routing.module.ts
Labels: needs-qa

#9479 AC-2702 Defect Full Header name is not visible for require sso component
  apps/web/src/app/admin-console/organizations/policies/policy-edit.component.html
Labels: needs-qa

#8522 PM-2047 Migrated Change Avatar component
  apps/web/src/app/auth/settings/account/change-avatar-dialog.component.html
  apps/web/src/app/auth/settings/account/change-avatar-dialog.component.ts
  apps/web/src/app/auth/settings/account/change-avatar.component.html
  apps/web/src/app/auth/settings/account/profile.component.html
  apps/web/src/app/auth/settings/account/profile.component.ts
  apps/web/src/app/shared/loose-components.module.ts
Labels: needs-qa

#8345 [PM 5023] migrate payment component
  apps/web/src/app/billing/shared/payment.component.html
  apps/web/src/app/billing/shared/payment.component.ts
Labels: needs-qa

#9478 AC-2723 Defect Range Too large error toast on reporting events is not being displayed
  apps/web/src/app/admin-console/common/base.events.component.ts
Labels: needs-qa

#9484 [AC-2721][Defect] Apply Subscription Status Updates in Provider Subscription details
  bitwarden_license/bit-web/src/app/admin-console/providers/providers.module.ts
  bitwarden_license/bit-web/src/app/billing/providers/subscription/provider-subscription.component.html
  bitwarden_license/bit-web/src/app/billing/providers/subscription/subscription-status.component.html
  bitwarden_license/bit-web/src/app/billing/providers/subscription/subscription-status.component.ts
  libs/common/src/billing/models/response/provider-subscription-response.ts
Labels: needs-qa

#8663 PM-4977 Migrate Preferences component
  apps/web/src/app/settings/preferences.component.html
  apps/web/src/app/settings/preferences.component.ts
Labels: needs-qa

#9532 [PM-8623] Show family icon for free orgs in filter chips
  apps/browser/src/vault/popup/services/vault-popup-list-filters.service.spec.ts
  apps/browser/src/vault/popup/services/vault-popup-list-filters.service.ts
Labels: needs-qa

#9537 [PM-8665] Show toast when favorite is toggled
  apps/browser/src/_locales/en/messages.json
  apps/browser/src/vault/popup/components/vault-v2/item-more-options/item-more-options.component.ts
Labels: needs-qa

#9570 [PM-8624] PersonalOwnershipPolicy check in Vault Filters
  apps/browser/src/vault/popup/services/vault-popup-list-filters.service.spec.ts
  apps/browser/src/vault/popup/services/vault-popup-list-filters.service.ts
Labels: needs-qa

#9503 [PM-8593] CLI - Logout needs to reset active account
  apps/cli/src/service-container.ts
Labels: needs-qa

#9547 [PM-2057] update two factor email dialog
  apps/web/src/app/auth/settings/two-factor-email.component.html
  apps/web/src/app/auth/settings/two-factor-email.component.ts
Labels: needs-qa

#9204 [PM-4956] two factor component migration
  apps/web/src/app/auth/two-factor.component.html
  apps/web/src/app/auth/two-factor.component.ts
  apps/web/src/app/oss-routing.module.ts
  apps/web/src/locales/en/messages.json
Labels: needs-qa

#9588 Upload license dialog not closing bug fix
  apps/web/src/app/billing/shared/update-license-dialog.component.ts
  apps/web/src/app/billing/shared/update-license.component.ts
Labels: needs-qa

#8199 [PM-5024] tax info component migration
  apps/web/src/app/billing/accounts/trial-initiation/trial-billing-step.component.ts
  apps/web/src/app/billing/individual/premium.component.ts
  apps/web/src/app/billing/organizations/organization-plans.component.ts
  apps/web/src/app/billing/shared/adjust-payment-dialog.component.ts
  apps/web/src/app/billing/shared/tax-info.component.html
  apps/web/src/app/billing/shared/tax-info.component.ts
Labels: needs-qa

#9443 [AC-2567] Updated certain billing callsites to get billing history instead
  apps/web/src/app/billing/organizations/organization-billing-history-view.component.ts
  libs/common/src/admin-console/abstractions/organization/organization-api.service.abstraction.ts
  libs/common/src/admin-console/services/organization/organization-api.service.ts
  libs/common/src/billing/models/response/billing.response.ts
Labels: needs-qa

#9169 PM-1943 Migrate Recover Delete Component
  apps/web/src/app/auth/recover-delete.component.html
  apps/web/src/app/auth/recover-delete.component.ts
  apps/web/src/app/oss-routing.module.ts
Labels: needs-qa

#9390 AC-2409 Migrate Accept Provider Component
  bitwarden_license/bit-web/src/app/admin-console/providers/manage/accept-provider.component.html
  bitwarden_license/bit-web/src/app/admin-console/providers/providers-routing.module.ts
Labels: needs-qa

#9126 PM-4954 Migrate SSO Component
  apps/web/src/app/auth/sso.component.html
  apps/web/src/app/auth/sso.component.ts
  apps/web/src/app/oss-routing.module.ts
Labels: needs-qa

#9602 Revert "Upload license dialog not closing bug fix (#9588)"
  apps/web/src/app/billing/shared/update-license-dialog.component.ts
  apps/web/src/app/billing/shared/update-license.component.ts
Labels: needs-qa

#9603 Revert "[PM-5024] tax info component migration (#8199)"
  apps/web/src/app/billing/accounts/trial-initiation/trial-billing-step.component.ts
  apps/web/src/app/billing/individual/premium.component.ts
  apps/web/src/app/billing/organizations/organization-plans.component.ts
  apps/web/src/app/billing/shared/adjust-payment-dialog.component.ts
  apps/web/src/app/billing/shared/tax-info.component.html
  apps/web/src/app/billing/shared/tax-info.component.ts
Labels: needs-qa

#9575 [PM-7683] Fix dynamic item defects
  apps/browser/src/_locales/en/messages.json
  apps/browser/src/vault/popup/components/vault-v2/item-copy-action/item-copy-actions.component.html
  apps/browser/src/vault/popup/components/vault-v2/item-copy-action/item-copy-actions.component.ts
  apps/browser/src/vault/popup/components/vault-v2/item-more-options/item-more-options.component.html
  apps/browser/src/vault/popup/components/vault-v2/item-more-options/item-more-options.component.ts
  apps/browser/src/vault/popup/components/vault-v2/vault-list-items-container/vault-list-items-container.component.html
  apps/browser/src/vault/popup/services/vault-popup-items.service.ts
  libs/components/src/badge/badge.directive.ts
  libs/components/src/menu/menu-item.directive.ts
  libs/vault/src/components/copy-cipher-field.directive.ts
Labels: needs-qa

#9495 [PM-4139] Remove approve device logins setting and enable it by default
  apps/browser/src/background/main.background.ts
  apps/desktop/src/app/accounts/settings.component.html
  apps/desktop/src/app/accounts/settings.component.ts
  apps/desktop/src/locales/en/messages.json
  apps/desktop/src/vault/app/vault/vault.component.ts
  libs/angular/src/services/jslib-services.module.ts
  libs/auth/src/common/abstractions/auth-request.service.abstraction.ts
  libs/auth/src/common/services/auth-request/auth-request.service.spec.ts
  libs/auth/src/common/services/auth-request/auth-request.service.ts
  libs/common/src/services/notifications.service.ts
Labels: needs-qa

#9633 [PM-8831] Hide trashed items from new vault popup lists
  apps/browser/src/vault/popup/services/vault-popup-list-filters.service.ts
Labels: needs-qa

#9652 [PM-8885] Hardcode Fallback to TreeWalker Strategy for PageCollection details
  apps/browser/src/autofill/services/collect-autofill-content.service.ts
Labels: needs-qa

#9658 Auth/PM-8866 - Fix Recover delete component submit missing form validation
  apps/web/src/app/auth/recover-delete.component.ts
Labels: needs-qa

#9664 [Fix] Storybook: product navigation errors
  apps/web/src/app/layouts/product-switcher/navigation-switcher/navigation-switcher.stories.ts
  apps/web/src/app/layouts/product-switcher/product-switcher.stories.ts
Labels: needs-qa

#9612 [PM-8830] Billing Enums Rename
  apps/browser/src/vault/popup/components/vault/vault-select.component.html
  apps/browser/src/vault/popup/services/vault-popup-items.service.spec.ts
  apps/browser/src/vault/popup/services/vault-popup-list-filters.service.spec.ts
  apps/browser/src/vault/popup/services/vault-popup-list-filters.service.ts
  apps/browser/src/vault/popup/views/popup-cipher.view.ts
  apps/web/src/app/admin-console/organizations/members/components/member-dialog/member-dialog.component.html
  apps/web/src/app/admin-console/organizations/members/components/member-dialog/member-dialog.component.ts
  apps/web/src/app/admin-console/organizations/members/components/member-dialog/validators/org-seat-limit-reached.validator.spec.ts
  apps/web/src/app/admin-console/organizations/members/components/member-dialog/validators/org-seat-limit-reached.validator.ts
  apps/web/src/app/admin-console/organizations/members/people.component.ts
  apps/web/src/app/admin-console/organizations/sponsorships/families-for-enterprise-setup.component.ts
  apps/web/src/app/admin-console/settings/create-organization.component.ts
  apps/web/src/app/auth/settings/two-factor-setup.component.ts
  apps/web/src/app/auth/trial-initiation/secrets-manager/secrets-manager-trial-paid-stepper.component.ts
  apps/web/src/app/auth/trial-initiation/trial-initiation.component.ts
  apps/web/src/app/billing/accounts/trial-initiation/trial-billing-step.component.ts
  apps/web/src/app/billing/organizations/organization-plans.component.html
  apps/web/src/app/billing/organizations/organization-plans.component.ts
  apps/web/src/app/billing/organizations/organization-subscription-cloud.component.ts
  apps/web/src/app/billing/shared/sm-subscribe.component.ts
  apps/web/src/app/vault/individual-vault/add-edit.component.ts
  apps/web/src/app/vault/org-vault/vault-header/vault-header.component.ts
  libs/common/src/admin-console/models/data/organization.data.spec.ts
  libs/common/src/admin-console/models/data/organization.data.ts
  libs/common/src/admin-console/models/domain/organization.ts
  libs/common/src/admin-console/models/response/profile-organization.response.ts
  libs/common/src/billing/enums/index.ts
  libs/common/src/billing/enums/product-tier-type.enum.ts
  libs/common/src/billing/enums/product-type.enum.ts
  libs/common/src/billing/models/response/plan.response.ts
  libs/common/src/enums/index.ts
Labels: needs-qa

#9523 [PM-7879, PM-7635] Add server verification for master password to user verification
  apps/browser/src/background/main.background.ts
  apps/cli/src/auth/commands/unlock.command.ts
  apps/cli/src/base-program.ts
  apps/cli/src/oss-serve-configurator.ts
  apps/cli/src/program.ts
  apps/cli/src/service-container.ts
  libs/angular/src/auth/components/lock.component.ts
  libs/angular/src/services/jslib-services.module.ts
  libs/common/src/abstractions/api.service.ts
  libs/common/src/auth/abstractions/user-verification/user-verification-api.service.abstraction.ts
  libs/common/src/auth/abstractions/user-verification/user-verification.service.abstraction.ts
  libs/common/src/auth/services/user-verification/user-verification-api.service.ts
  libs/common/src/auth/services/user-verification/user-verification.service.spec.ts
  libs/common/src/auth/services/user-verification/user-verification.service.ts
  libs/common/src/auth/types/verification.ts
  libs/common/src/services/api.service.ts
Labels: needs-qa

#9665 Auth/PM-8886 - SsoComponent - fix missing form validation
  apps/web/src/app/auth/sso.component.ts
Labels: needs-qa

#9611 [SM-1305] Add Kubernetes and Rust to the integrations page
  apps/web/src/images/secrets-manager/integrations/kubernetes.svg
  apps/web/src/images/secrets-manager/sdks/rust-white.svg
  apps/web/src/images/secrets-manager/sdks/rust.svg
  apps/web/src/locales/en/messages.json
  bitwarden_license/bit-web/src/app/secrets-manager/integrations/integrations.component.spec.ts
  bitwarden_license/bit-web/src/app/secrets-manager/integrations/integrations.component.ts
Labels: needs-qa

#9671 Auth/ Fix web route data configuration issues for SSO comp and AcceptEmergency comp
  apps/web/src/app/oss-routing.module.ts
Labels: needs-qa

#9037 [PM-7930] Add ability to pop out extension to user decryption options component
  apps/browser/src/auth/popup/login-decryption-options/login-decryption-options.component.html
Labels: needs-qa

#9485 PM-8482 Change KDF Confirmation no longer has browser validation
  apps/web/src/app/auth/settings/security/change-kdf/change-kdf-confirmation.component.ts
Labels: needs-qa

#9624 Bug fix - Yubikey code obscured
  apps/web/src/app/auth/two-factor.component.html
Labels: needs-qa

#9555 [PM-7387] Hide Master Password tab for users without MP
  apps/web/src/app/auth/settings/security/security.component.html
Labels: needs-qa

#9347 [PM-728] CLI - Error when on server config change when logged in
  apps/cli/src/platform/commands/config.command.ts
  apps/cli/src/program.ts
Labels: needs-qa

#9639 [PM-8865] Reset "should trust device" state to null
  libs/common/src/auth/services/device-trust.service.implementation.ts
  libs/common/src/auth/services/device-trust.service.spec.ts
Labels: needs-qa

#8923 [PM-2664] Hide Owners column below desktop viewports
  apps/web/src/app/vault/components/vault-items/vault-cipher-row.component.html
  apps/web/src/app/vault/components/vault-items/vault-collection-row.component.html
  apps/web/src/app/vault/components/vault-items/vault-items.component.html
Labels: needs-qa

#9713 [Storybook] Product Switcher errors
  apps/web/src/app/layouts/product-switcher/navigation-switcher/navigation-switcher.stories.ts
Labels: needs-qa

#9607 [PM-7215] User with Can View permission can remove passkey or delete URIs from UI, though it isn't saved
  apps/browser/src/vault/popup/components/vault/add-edit.component.html
  apps/desktop/src/vault/app/vault/add-edit.component.html
  apps/web/src/app/vault/individual-vault/add-edit.component.ts
Labels: needs-qa

#9538 [PM-8615] Filters Accessibility tweaks
  apps/browser/src/_locales/en/messages.json
  apps/browser/src/vault/popup/components/vault-v2/vault-list-filters/vault-list-filters.component.html
  apps/browser/src/vault/popup/components/vault/vault-v2.component.html
Labels: needs-qa

#9746 [PM-9042] Fixed name for product tier to match property sent from the server
  libs/common/src/admin-console/models/data/organization.data.ts
  libs/common/src/admin-console/models/response/profile-organization.response.ts
Labels: needs-qa

#9649 [AC-2776][PM-773] Update email on sponsored families signup to update on change
  apps/web/src/app/admin-console/settings/sponsored-families.component.ts
Labels: needs-qa

#9732 [PM-830] Add attribute aria-expanded to Send add-edit options button
  apps/web/src/app/tools/send/add-edit.component.html
Labels: accessibility, web

#9786 [PM-8994] Load vault data when coming from another user that was viewing an org
  apps/web/src/app/vault/individual-vault/vault-filter/services/abstractions/vault-filter.service.ts
  apps/web/src/app/vault/individual-vault/vault-filter/services/vault-filter.service.ts
  apps/web/src/app/vault/individual-vault/vault.component.ts
Labels: needs-qa

#9774 [AC-2166] Resolve billing email error on organization name update
  apps/web/src/app/admin-console/organizations/settings/account.component.ts
Labels: needs-qa

#9581 Translation settings should be persisted on web
  libs/common/src/platform/state/state-definitions.ts
Labels: needs-qa

#9821 [PM-9182] Introduce optional alternative componentRouteSwap route options
  libs/angular/src/utils/component-route-swap.ts
Labels: needs-qa

#8397 PM-5022 Migrate Payment Method component
  apps/web/src/app/billing/shared/payment-method.component.html
  apps/web/src/app/billing/shared/payment-method.component.ts
Labels: needs-qa

#8854 [AC-2411] migrate account component
  apps/web/src/app/admin-console/organizations/settings/account.component.html
  bitwarden_license/bit-web/src/app/admin-console/providers/settings/account.component.html
  bitwarden_license/bit-web/src/app/admin-console/providers/settings/account.component.ts
Labels: needs-qa

#8976 [PM-2056] update two factor duo dialog
  apps/web/src/app/admin-console/organizations/settings/two-factor-setup.component.ts
  apps/web/src/app/auth/settings/two-factor-duo.component.html
  apps/web/src/app/auth/settings/two-factor-duo.component.ts
  apps/web/src/app/auth/settings/two-factor-setup.component.ts
Labels: needs-qa

#9592 [PM-8800] Adding the setting of the account to null on logout for web
  apps/web/src/app/app.component.ts
Labels: needs-qa

#9827 Update CLI storefronts to use bitwarden licensed artifacts
  .github/workflows/build-cli.yml
  apps/cli/package.json
  apps/cli/stores/snap/snapcraft.yaml
Labels: needs-qa

#9715 [PM-7897] Attachments - Part 1
  apps/browser/src/_locales/en/messages.json
  apps/browser/src/popup/app-routing.module.ts
  apps/browser/src/vault/popup/components/vault-v2/add-edit/add-edit-v2.component.html
  apps/browser/src/vault/popup/components/vault-v2/add-edit/add-edit-v2.component.ts
  apps/browser/src/vault/popup/components/vault-v2/attachments/attachments-v2.component.html
  apps/browser/src/vault/popup/components/vault-v2/attachments/attachments-v2.component.spec.ts
  apps/browser/src/vault/popup/components/vault-v2/attachments/attachments-v2.component.ts
  apps/browser/src/vault/popup/components/vault-v2/attachments/cipher-attachments/cipher-attachments.component.html
  apps/browser/src/vault/popup/components/vault-v2/attachments/cipher-attachments/cipher-attachments.component.spec.ts
  apps/browser/src/vault/popup/components/vault-v2/attachments/cipher-attachments/cipher-attachments.component.ts
  apps/browser/src/vault/popup/components/vault-v2/attachments/cipher-attachments/delete-attachment/delete-attachment.component.html
  apps/browser/src/vault/popup/components/vault-v2/attachments/cipher-attachments/delete-attachment/delete-attachment.component.spec.ts
  apps/browser/src/vault/popup/components/vault-v2/attachments/cipher-attachments/delete-attachment/delete-attachment.component.ts
  apps/browser/src/vault/popup/components/vault-v2/attachments/cipher-attachments/download-attachment/download-attachment.component.html
  apps/browser/src/vault/popup/components/vault-v2/attachments/cipher-attachments/download-attachment/download-attachment.component.spec.ts
  apps/browser/src/vault/popup/components/vault-v2/attachments/cipher-attachments/download-attachment/download-attachment.component.ts
  apps/browser/src/vault/popup/components/vault-v2/attachments/open-attachments/open-attachments.component.html
  apps/browser/src/vault/popup/components/vault-v2/attachments/open-attachments/open-attachments.component.spec.ts
  apps/browser/src/vault/popup/components/vault-v2/attachments/open-attachments/open-attachments.component.ts
Labels: needs-qa

#9803 [PM-8718] Streamlined SSO autosubmit flow
  apps/web/src/app/auth/sso.component.ts
Labels: needs-qa

#9877 Auth/PM-4950 - Fix hint and verify delete components that had the route data in the wrong place
  apps/web/src/app/oss-routing.module.ts
Labels: needs-qa

#9727 [AC-2791] Members page - finish component library refactors
  apps/web/src/app/admin-console/common/new-base.people.component.ts
  apps/web/src/app/admin-console/common/people-table-data-source.ts
  apps/web/src/app/admin-console/organizations/members/members-routing.module.ts
  apps/web/src/app/admin-console/organizations/members/members.component.html
  apps/web/src/app/admin-console/organizations/members/members.component.ts
  apps/web/src/app/admin-console/organizations/members/members.module.ts
Labels: web
