Repository bitwarden/clients, pull requests merged in 2024-08, with the labels that each got.

#9851 [PM-6296] Fix biometrics error prompt when biometrics are temporarily unavailable in browser extension
  apps/browser/src/_locales/en/messages.json
  apps/browser/src/auth/popup/lock.component.ts
  apps/browser/src/auth/popup/settings/account-security.component.ts
  apps/browser/src/background/main.background.ts
  apps/browser/src/background/nativeMessaging.background.ts
  apps/browser/src/background/runtime.background.ts
  apps/browser/src/platform/services/background-browser-biometrics..ts
  apps/browser/src/platform/services/browser-biometrics.service.ts
  apps/browser/src/platform/services/browser-crypto.service.ts
  apps/browser/src/platform/services/foreground-browser-biometrics.ts
  apps/browser/src/platform/services/platform-utils/background-platform-utils.service.ts
  apps/browser/src/platform/services/platform-utils/browser-platform-utils.service.spec.ts
  apps/browser/src/platform/services/platform-utils/browser-platform-utils.service.ts
  apps/browser/src/platform/services/platform-utils/foreground-platform-utils.service.ts
  apps/browser/src/popup/services/services.module.ts
  apps/cli/src/platform/services/cli-platform-utils.service.ts
  apps/desktop/src/app/accounts/settings.component.ts
  apps/desktop/src/app/services/services.module.ts
  apps/desktop/src/auth/lock.component.spec.ts
  apps/desktop/src/auth/lock.component.ts
  apps/desktop/src/main.ts
  apps/desktop/src/platform/main/biometric/biometric.darwin.main.ts
  apps/desktop/src/platform/main/biometric/biometric.noop.main.ts
  apps/desktop/src/platform/main/biometric/biometric.windows.main.ts
  apps/desktop/src/platform/main/biometric/biometrics.service.spec.ts
  apps/desktop/src/platform/main/biometric/biometrics.service.ts
  apps/desktop/src/platform/main/biometric/desktop.biometrics.service.ts
  apps/desktop/src/platform/main/biometric/index.ts
  apps/desktop/src/platform/main/desktop-credential-storage-listener.ts
  apps/desktop/src/platform/services/electron-biometrics.service.ts
  apps/desktop/src/platform/services/electron-platform-utils.service.ts
  apps/desktop/src/services/native-messaging.service.ts
  apps/web/src/app/core/web-platform-utils.service.ts
  libs/angular/src/auth/components/lock.component.ts
  libs/common/src/platform/abstractions/platform-utils.service.ts
  libs/common/src/platform/biometrics/biometric.service.ts
Labels: needs-qa

#4586 [PM-990] Unix biometrics unlock via Polkit
  apps/browser/src/platform/services/platform-utils/browser-platform-utils.service.ts
  apps/desktop/desktop_native/Cargo.lock
  apps/desktop/desktop_native/core/Cargo.toml
  apps/desktop/desktop_native/core/src/biometric/macos.rs
  apps/desktop/desktop_native/core/src/biometric/mod.rs
  apps/desktop/desktop_native/core/src/biometric/unix.rs
  apps/desktop/desktop_native/core/src/biometric/windows.rs
  apps/desktop/desktop_native/core/src/password/macos.rs
  apps/desktop/desktop_native/core/src/password/unix.rs
  apps/desktop/desktop_native/core/src/password/windows.rs
  apps/desktop/desktop_native/napi/index.d.ts
  apps/desktop/desktop_native/napi/src/lib.rs
  apps/desktop/src/app/accounts/settings.component.html
  apps/desktop/src/app/accounts/settings.component.ts
  apps/desktop/src/auth/lock.component.ts
  apps/desktop/src/locales/en/messages.json
  apps/desktop/src/platform/main/biometric/biometric.darwin.main.ts
  apps/desktop/src/platform/main/biometric/biometric.noop.main.ts
  apps/desktop/src/platform/main/biometric/biometric.unix.main.ts
  apps/desktop/src/platform/main/biometric/biometric.windows.main.ts
  apps/desktop/src/platform/main/biometric/biometrics.service.abstraction.ts
  apps/desktop/src/platform/main/biometric/biometrics.service.ts
  apps/desktop/src/platform/main/desktop-credential-storage-listener.ts
  apps/desktop/src/platform/preload.ts
  apps/desktop/src/platform/services/electron-platform-utils.service.ts
  apps/desktop/src/types/biometric-message.ts
  apps/desktop/src/utils.ts
  apps/web/src/app/core/web-platform-utils.service.ts
  libs/common/src/platform/abstractions/platform-utils.service.ts
Labels: needs-qa

#10446 [PM-10026] [Defect] Zip code is not being enforced when subscribing in Password Manager
  apps/web/src/app/billing/individual/premium.component.ts
  apps/web/src/app/billing/organizations/organization-plans.component.ts
Labels: needs-qa

#10473 [PM-10764] Fix ProtonPass creditCard expirationDate import
  libs/importer/spec/test-data/protonpass-json/protonpass.json.ts
  libs/importer/src/importers/protonpass/protonpass-json-importer.ts
Labels: community-pr

#10487 [PM-10295] Remove Flexible Collections V1 feature flag
  libs/common/src/enums/feature-flag.enum.ts
Labels: feature-flag

#10005 [PM-9552] add a toggle for the routing animation
  apps/browser/src/_locales/en/messages.json
  apps/browser/src/popup/app.component.ts
  apps/browser/src/popup/services/services.module.ts
  apps/browser/src/vault/popup/settings/appearance.component.html
  apps/browser/src/vault/popup/settings/appearance.component.ts
  libs/common/src/platform/abstractions/animation-control.service.ts
  libs/common/src/platform/state/state-definitions.ts
Labels: community-pr

#10708 [PM-11314] Fix system auth typo 'autometic' -> 'automatic'
  apps/desktop/src/locales/en/messages.json
Labels: community-pr

#10699 [PM-4473] use anon layout for send access component
  apps/web/src/app/oss-routing.module.ts
  apps/web/src/app/tools/send/access.component.html
  apps/web/src/app/tools/send/access.component.ts
  apps/web/src/app/tools/send/send-access-explainer.component.html
  apps/web/src/app/tools/send/send-access-explainer.component.ts
  apps/web/src/locales/en/messages.json
Labels: needs-qa

#10717 [PM-11329] [chore] Add "otp" TotpFieldNames array in autofill-constants.ts
  apps/browser/src/autofill/services/autofill-constants.ts
Labels: community-pr
