Repository bitwarden/clients, pull requests merged in 2024-02, with the labels that each got.

#7797 [PM-5991] Updated ordering on account switch to route before clearing state
  apps/desktop/src/app/layout/account-switcher.component.ts
Labels: needs-qa

#7830 [AC-2147] Show grant collection access helper text
  apps/web/src/app/vault/components/collection-dialog/collection-dialog.component.html
Labels: bug, needs-qa

#7835 [PM-6124] Default Passkey Setting not correct
  libs/common/src/vault/services/vault-settings/vault-settings.service.ts
Labels: needs-qa

#7841 Properly set up StateProvider dependency for OrganizationService
  apps/browser/src/popup/services/services.module.ts
  libs/angular/src/services/jslib-services.module.ts
Labels: needs-qa

#7848 [AC-2115] Update admin view to also collection check manage flag
  apps/web/src/app/vault/core/views/collection-admin.view.ts
Labels: needs-qa

#7879 Refactored folders component template to use a single subscription
  apps/browser/src/popup/settings/folders.component.html
Labels: needs-qa

#7884 [AC-2113] Confirmation dialog for enabling collection enhancements
  apps/web/src/app/admin-console/organizations/settings/account.component.html
  apps/web/src/app/admin-console/organizations/settings/account.component.ts
  apps/web/src/locales/en/messages.json
Labels: needs-qa

#5473 [PM-2311] Allow empty passphrase separator
  apps/cli/src/program.ts
  apps/cli/src/tools/generate.command.ts
  libs/common/src/tools/generator/passphrase/index.ts
  libs/common/src/tools/generator/passphrase/passphrase-generation-options.ts
  libs/common/src/tools/generator/passphrase/passphrase-generator-options-evaluator.spec.ts
  libs/common/src/tools/generator/passphrase/passphrase-generator-options-evaluator.ts
  libs/common/src/tools/generator/password/password-generation.service.ts
Labels: community-pr

#7508 [PM-5663] Fix copy to clipboard not working on Wayland
  apps/desktop/desktop_native/Cargo.lock
  apps/desktop/desktop_native/Cargo.toml
Labels: community-pr

#7911 clear ever had user key for logged out user instead of active
  libs/common/src/platform/services/crypto.service.ts
Labels: needs-qa

#7928 Improve checkmarx config
  .checkmarx/config.yml
Labels: needs-qa

#6911 [PM-4871] Remove clickable row in favor of clickable cell content
  apps/web/src/app/vault/components/vault-items/vault-cipher-row.component.ts
  apps/web/src/app/vault/components/vault-items/vault-collection-row.component.ts
Labels: community-pr

#7965 only show hand off message on desktop
  apps/web/src/connectors/duo-redirect.ts
Labels: needs-qa

#7967 Update Mac Developer Certificate
  .github/secrets/macdev-cert.p12.gpg
Labels: needs-qa

#7976 Add Autofill Team as Codeowners of Autofill Libs Path
  .github/CODEOWNERS
Labels: needs-qa

#7765 [PM-6006] Restrict desktop devtools to dev mode only
  apps/desktop/src/main/menu/menu.view.ts
  apps/desktop/src/main/window.main.ts
Labels: needs-qa

#8004 Add rel=noreferrer to send register
  apps/web/src/app/tools/send/access.component.html
Labels: needs-qa

#8006 Add rel noreferrer to download link
  apps/web/src/app/core/web-file-download.service.ts
Labels: needs-qa

#7855 [PM-6163] Speed up list items command - Only call GetGlobals() when we actually need them
  libs/common/src/platform/services/state.service.ts
Labels: community-pr

#7729 [PM-673] Safari browser extension does not list folders when offering to save new or last-used credentials
  apps/browser/src/_locales/en/messages.json
  apps/browser/src/autofill/background/abstractions/notification.background.ts
  apps/browser/src/autofill/background/notification.background.spec.ts
  apps/browser/src/autofill/background/notification.background.ts
  apps/browser/src/autofill/content/notification-bar.ts
  apps/browser/src/autofill/notification/bar.ts
  apps/browser/src/autofill/overlay/pages/shared/autofill-overlay-page-element.ts
  apps/browser/src/background/main.background.ts
Labels: browser

#8051 Remove constructor from link-sso
  apps/web/src/app/vault/individual-vault/vault-filter/components/link-sso.directive.ts
Labels: needs-qa

#7952 [PM-6213] Fix Inline Autofill Menu Erasing Filled Form on Hilton.com
  apps/browser/src/autofill/content/autofill-init.spec.ts
  apps/browser/src/autofill/content/autofill-init.ts
Labels: browser

#7730 [PM-2753] Prompt to Save New Login Credentials Silently Drops Data on Network Error
  apps/browser/src/_locales/en/messages.json
  apps/browser/src/autofill/background/abstractions/notification.background.ts
  apps/browser/src/autofill/background/notification.background.spec.ts
  apps/browser/src/autofill/background/notification.background.ts
  apps/browser/src/autofill/content/notification-bar.ts
  apps/browser/src/autofill/notification/abstractions/notification-bar.ts
  apps/browser/src/autofill/notification/bar.html
  apps/browser/src/autofill/notification/bar.scss
  apps/browser/src/autofill/notification/bar.ts
Labels: browser

#8070 Add key generation service to deps
  apps/browser/src/background/main.background.ts
  apps/browser/src/popup/services/services.module.ts
Labels: needs-qa

#7951 [PM-6078] Remove Username Masking From Inline Autofill Menu
  apps/browser/src/autofill/background/overlay.background.spec.ts
  apps/browser/src/autofill/background/overlay.background.ts
Labels: browser

#8056 [PM-5499] Create Auth Request Service
  apps/browser/src/auth/background/service-factories/auth-request-crypto-service.factory.ts
  apps/browser/src/auth/background/service-factories/auth-request-service.factory.ts
  apps/browser/src/auth/background/service-factories/login-strategy-service.factory.ts
  apps/browser/src/auth/popup/login-via-auth-request.component.ts
  apps/browser/src/background/main.background.ts
  apps/browser/src/popup/services/services.module.ts
  apps/cli/src/bw.ts
  apps/desktop/src/auth/login/login-approval.component.ts
  apps/desktop/src/auth/login/login-via-auth-request.component.ts
  apps/web/src/app/auth/login/login-via-auth-request.component.ts
  libs/angular/src/auth/components/login-via-auth-request.component.ts
  libs/angular/src/services/jslib-services.module.ts
  libs/auth/src/common/abstractions/auth-request.service.abstraction.ts
  libs/auth/src/common/abstractions/index.ts
  libs/auth/src/common/abstractions/login-strategy.service.ts
  libs/auth/src/common/login-strategies/sso-login.strategy.spec.ts
  libs/auth/src/common/login-strategies/sso-login.strategy.ts
  libs/auth/src/common/services/auth-request/auth-request.service.spec.ts
  libs/auth/src/common/services/auth-request/auth-request.service.ts
  libs/auth/src/common/services/index.ts
  libs/auth/src/common/services/login-strategies/login-strategy.service.ts
  libs/common/src/auth/abstractions/auth-request-crypto.service.abstraction.ts
  libs/common/src/auth/services/auth-request-crypto.service.implementation.ts
Labels: needs-qa

#8019 [PM-6391] Add "fixed-width" class to view icons
  apps/browser/src/vault/popup/components/vault/add-edit.component.html
Labels: bug

#8105 temporarily disable web-header stories
  apps/web/src/app/layouts/header/web-header.skip-stories.ts
  apps/web/src/app/layouts/header/web-header.stories.ts
Labels: needs-qa

#8103 [AC-2245] Fix - Collection dialog access selector column headers
  apps/web/src/app/vault/components/collection-dialog/collection-dialog.component.html
  apps/web/src/app/vault/org-vault/bulk-collections-dialog/bulk-collections-dialog.component.html
  apps/web/src/locales/en/messages.json
Labels: bug

#7966 DEVOPS-1743 Web Vault Migration workflow improvements
  .github/workflows/deploy-web.yml
Labels: devops

#8124 Bug - Fix migration rollbacks
  libs/common/src/state-migrations/migrations/11-move-org-keys-to-state-providers.spec.ts
  libs/common/src/state-migrations/migrations/13-move-provider-keys-to-state-providers.spec.ts
  libs/common/src/state-migrations/migrations/18-move-autofill-settings-to-state-providers.spec.ts
  libs/common/src/state-migrations/migrations/24-move-sm-onboarding-key-to-state-providers.spec.ts
  libs/common/src/state-migrations/migrations/25-move-clear-clipboard-to-autofill-settings-state-provider.spec.ts
  libs/common/src/state-migrations/migrations/26-move-badge-settings-to-state-providers.spec.ts
Labels: bug

#8140 [PM-6495] Remove extra parameters in biometrics constructors
  apps/desktop/src/main.ts
  apps/desktop/src/platform/main/biometric/biometrics.service.spec.ts
  apps/desktop/src/platform/main/biometric/biometrics.service.ts
Labels: needs-qa

#8139 DEVOPS-1800 - Migrate Secrets
  .github/secrets/appstore-app-cert.p12.gpg
  .github/secrets/appstore-installer-cert.p12.gpg
  .github/secrets/bitwarden-desktop-key.p12.gpg
  .github/secrets/bitwarden_desktop_appstore.provisionprofile.gpg
  .github/secrets/devid-app-cert.p12.gpg
  .github/secrets/devid-installer-cert.p12.gpg
  .github/secrets/macdev-cert.p12.gpg
  .github/workflows/build-browser.yml
  .github/workflows/build-desktop.yml
  .github/workflows/release-desktop-beta.yml
Labels: devops

#8141 DEVOPS-1841 - Change versions to proper values
  apps/browser/package.json
  apps/browser/src/manifest.json
  apps/browser/src/manifest.v3.json
  apps/cli/package.json
  apps/desktop/package.json
  apps/desktop/src/package-lock.json
  apps/desktop/src/package.json
  package-lock.json
Labels: devops
