Repository bitwarden/clients, pull requests merged in 2025-02, with the labels that each got.

#13185 [PM-17487] Load cipher data into new notification experience
  apps/browser/src/autofill/background/notification.background.ts
  apps/browser/src/autofill/content/components/cipher/cipher-info.ts
  apps/browser/src/autofill/content/components/cipher/cipher-item.ts
  apps/browser/src/autofill/content/components/cipher/types.ts
  apps/browser/src/autofill/content/components/lit-stories/notification/body.lit-stories.ts
  apps/browser/src/autofill/content/components/notification/body.ts
  apps/browser/src/autofill/content/components/notification/container.ts
  apps/browser/src/autofill/notification/bar.ts
Labels: enhancement

#12693 [PM-16717] [Desktop] Remove incorrect `aria-hidden` from account switcher options
  apps/desktop/src/app/layout/account-switcher.component.html
Labels: community-pr

#13364 PM-18215 Create UI for confirmation notification message
  apps/browser/src/autofill/content/components/icons/index.ts
  apps/browser/src/autofill/content/components/icons/party-horn.ts
  apps/browser/src/autofill/content/components/icons/warning.ts
  apps/browser/src/autofill/content/components/lit-stories/notification/confirmation.lit-stories.ts
  apps/browser/src/autofill/content/components/notification/confirmation-message.ts
  apps/browser/src/autofill/content/components/notification/confirmation.ts
Labels: enhancement

#13339 pm-18084 Connect new notification bar experience buttons
  apps/browser/src/autofill/content/components/lit-stories/notification/body.lit-stories.ts
  apps/browser/src/autofill/content/components/lit-stories/notification/footer.lit-stories.ts
  apps/browser/src/autofill/content/components/lit-stories/rows/button-row.lit-stories.ts
  apps/browser/src/autofill/content/components/notification/body.ts
  apps/browser/src/autofill/content/components/notification/container.ts
  apps/browser/src/autofill/content/components/notification/footer.ts
  apps/browser/src/autofill/content/components/rows/button-row.ts
  apps/browser/src/autofill/notification/bar.ts
Labels: enhancement

#13210 [PM-17913] fix: zh-TW registerLocaleData missing extra error
  apps/browser/src/platform/popup/locales.ts
  apps/desktop/src/platform/app/locales.ts
  apps/web/src/app/shared/locales.ts
Labels: community-pr

#13494 pm-18441 add loading icon to member details
  bitwarden_license/bit-web/src/app/tools/reports/member-access-report/member-access-report.component.html
  bitwarden_license/bit-web/src/app/tools/reports/member-access-report/member-access-report.component.ts
Labels: needs-qa

#13455 [PM-17223] Update comma to period after "Invalid input provided" text
  apps/web/src/app/billing/shared/payment/payment.component.ts
Labels: needs-qa

#10273 [PM-10105] Release arm64 binaries for macOS
  .github/workflows/build-cli.yml
  apps/cli/package.json
Labels: community-pr

#13498 PM-18276-Connect confirmation UI
  apps/browser/src/autofill/content/components/notification/confirmation-container.ts
  apps/browser/src/autofill/content/components/notification/header.ts
  apps/browser/src/autofill/notification/bar.ts
Labels: enhancement

#13570 Pm 18493 pass relevant cipher name into confirmation UI
  apps/browser/src/_locales/en/messages.json
  apps/browser/src/autofill/background/abstractions/notification.background.ts
  apps/browser/src/autofill/background/notification.background.spec.ts
  apps/browser/src/autofill/background/notification.background.ts
  apps/browser/src/autofill/content/components/lit-stories/notification/confirmation.lit-stories.ts
  apps/browser/src/autofill/content/components/notification/confirmation-container.ts
  apps/browser/src/autofill/content/components/notification/confirmation.ts
  apps/browser/src/autofill/content/notification-bar.ts
  apps/browser/src/autofill/notification/abstractions/notification-bar.ts
  apps/browser/src/autofill/notification/bar.ts
Labels: enhancement

#13639 PM-18522 Adjust Confirmation UI text to accommodate truncating
  apps/browser/src/autofill/content/components/lit-stories/notification/footer.lit-stories.ts
  apps/browser/src/autofill/content/components/lit-stories/rows/button-row.lit-stories.ts
  apps/browser/src/autofill/content/components/notification/confirmation-message.ts
  apps/browser/src/autofill/content/components/notification/confirmation.ts
  apps/browser/src/autofill/content/components/notification/container.ts
  apps/browser/src/autofill/content/components/notification/footer.ts
  apps/browser/src/autofill/content/components/rows/button-row.ts
Labels: enhancement
