Repository bitwarden/clients, pull requests merged in 2025-04, with the labels that each got.

#13973 PM-19378 remove v1 notification bar path
  apps/browser/src/autofill/background/overlay-notifications.background.spec.ts
  apps/browser/src/autofill/background/overlay-notifications.background.ts
  apps/browser/src/autofill/content/notification-bar.ts
  apps/browser/src/autofill/notification/abstractions/notification-bar.ts
  apps/browser/src/autofill/notification/bar.html
  apps/browser/src/autofill/notification/bar.scss
  apps/browser/src/autofill/notification/bar.ts
  apps/browser/src/autofill/overlay/notifications/content/overlay-notifications-content.service.ts
  apps/browser/src/autofill/services/autofill.service.spec.ts
  apps/browser/src/autofill/services/autofill.service.ts
  apps/browser/src/background/main.background.ts
  apps/browser/webpack.config.js
  libs/common/src/enums/feature-flag.enum.ts
Labels: enhancement

#14062 [PM-19713][BEEEP] Improve performance of whether user can view subsc…
  libs/common/src/billing/services/account/billing-account-profile-state.service.ts
Labels: needs-qa

#13755 [PM-19041] Fix: Safari pinned tabs causing autofill to be wrong
  apps/browser/src/platform/browser/browser-api.spec.ts
  apps/browser/src/platform/browser/browser-api.ts
Labels: community-pr

#13822 PM-19102 Autofill new identity information in the popout
  apps/browser/src/autofill/services/autofill-overlay-content.service.ts
  apps/browser/src/vault/popup/components/vault-v2/add-edit/add-edit-v2.component.ts
  libs/vault/src/cipher-form/abstractions/cipher-form-config.service.ts
  libs/vault/src/cipher-form/components/identity/identity.component.ts
Labels: needs-qa

#14004 Autofill/pm 17444 use reprompt
  apps/desktop/src/app/app.component.ts
  apps/desktop/src/autofill/services/desktop-fido2-user-interface.service.ts
  apps/desktop/src/modal/passkeys/create/fido2-create.component.html
  apps/desktop/src/modal/passkeys/create/fido2-create.component.ts
  apps/desktop/src/modal/passkeys/fido2-vault.component.html
  apps/desktop/src/modal/passkeys/fido2-vault.component.ts
  apps/desktop/src/scss/header.scss
  libs/common/spec/fake-account-service.ts
  libs/common/src/auth/abstractions/account.service.ts
  libs/common/src/auth/services/account.service.spec.ts
  libs/common/src/auth/services/account.service.ts
  libs/common/src/vault/abstractions/cipher.service.ts
  libs/common/src/vault/services/cipher.service.ts
Labels: needs-qa

#13841 [PM-19216] Properly handle message aborts during cleanup
  apps/browser/src/autofill/fido2/content/messaging/messenger.ts
Labels: community-pr

#14141 [PM-19914] PM-19913: Added max length to the generated_for and description peroperties in the FirefoxRelay API payload
  libs/common/src/tools/integration/integration-context.spec.ts
  libs/common/src/tools/integration/integration-context.ts
  libs/tools/generator/core/src/integration/addy-io.spec.ts
  libs/tools/generator/core/src/integration/addy-io.ts
  libs/tools/generator/core/src/integration/firefox-relay.spec.ts
  libs/tools/generator/core/src/integration/firefox-relay.ts
Labels: community-pr

#14246 PM-20106 Pass indicator data to notification bar cipher items
  apps/browser/src/autofill/background/notification.background.ts
  apps/browser/src/autofill/content/components/cipher/cipher-indicator-icons.ts
  apps/browser/src/autofill/content/components/cipher/cipher-info.ts
  apps/browser/src/autofill/content/components/cipher/types.ts
Labels: enhancement

#14029 [PM-17773] Added "Sponsored Families" dropdown nav item in the admin console
  apps/web/src/app/admin-console/organizations/layouts/organization-layout.component.html
  apps/web/src/app/admin-console/organizations/layouts/organization-layout.component.ts
  apps/web/src/app/admin-console/organizations/members/members-routing.module.ts
  apps/web/src/app/billing/services/free-families-policy.service.spec.ts
  apps/web/src/app/billing/services/free-families-policy.service.ts
  libs/common/src/admin-console/models/data/organization.data.spec.ts
  libs/common/src/admin-console/models/data/organization.data.ts
  libs/common/src/admin-console/models/domain/organization.ts
  libs/common/src/admin-console/models/response/profile-organization.response.ts
  libs/common/src/enums/feature-flag.enum.ts
Labels: feature-flag

#14089 [PM-19798] [PM-18807] Fix base64 encoding/decoding with special characters
  libs/common/src/platform/misc/utils.spec.ts
  libs/common/src/platform/misc/utils.ts
Labels: community-pr, needs-qa

#14327 PM-19281 localize relevant notification bar text
  apps/browser/src/autofill/content/components/cipher/cipher-action.ts
  apps/browser/src/autofill/content/components/cipher/cipher-item.ts
  apps/browser/src/autofill/content/components/lit-stories/ciphers/cipher-action.lit-stories.ts
  apps/browser/src/autofill/content/components/lit-stories/notification/body.lit-stories.ts
  apps/browser/src/autofill/content/components/notification/body.ts
  apps/browser/src/autofill/content/components/notification/button-row.ts
  apps/browser/src/autofill/content/components/notification/container.ts
  apps/browser/src/autofill/content/components/notification/footer.ts
  apps/browser/src/autofill/notification/bar.ts
Labels: enhancement

#14342 PM-20396 open view item vault pop out
  apps/browser/src/_locales/en/messages.json
  apps/browser/src/autofill/background/abstractions/notification.background.ts
  apps/browser/src/autofill/background/notification.background.spec.ts
  apps/browser/src/autofill/background/notification.background.ts
  apps/browser/src/autofill/content/components/notification/confirmation/body.ts
  apps/browser/src/autofill/content/components/notification/confirmation/container.ts
  apps/browser/src/autofill/content/components/notification/confirmation/message.ts
  apps/browser/src/autofill/notification/abstractions/notification-bar.ts
  apps/browser/src/autofill/notification/bar.ts
Labels: enhancement
